from __future__ import annotations

import json
from collections import Counter, defaultdict
from importlib.resources import files
from pathlib import Path
from typing import Any

from ..canon import canonical_sha256, write_json_atomic
from ..controller import register_runner
from ..hashing import sha256_file
from ..spectroscope import run_scout_spectroscope
from ..conveyor_chunks import (
    ChunkCheckpointStore,
    chunk_parent_ranges,
    compute_generation_chunk,
    load_fixture_primitive,
    load_fixture_sources,
    merge_generation_chunks,
)
from .scout_l16 import _canon, _vector
from .scout_l16_forward import _farthest_exact, _closure_breakdown, _forward_recognition

LANE_ORDER = ["D", "B", "S", "O", "L"]
PER_LANE = 256
PROHIBITIONS = [
    "NO_FIRST_OCCURRENCE_CLAIM",
    "NO_C_PROVED",
    "NO_POPULATION_WIDE_NEGATIVE",
    "NO_MECHANISM_PROMOTION",
    "NO_GEOMETRY_PROMOTION",
    "NO_TOPOLOGY_PROMOTION_FROM_CYCLE_RANK",
    "NO_LATTICE_OR_CLOSED_ALGEBRA_PROMOTION_FROM_AGGREGATE_CLOSURE_COUNTS",
    "NO_GRADUATION_PROMOTION",
]


def _resource_json(name: str) -> dict[str, Any]:
    p = files("infinity_grid").joinpath("resources/conveyor").joinpath(name)
    return json.loads(p.read_text(encoding="utf-8"))


def _spec_sha(name: str) -> str:
    obj = _resource_json(name)
    return canonical_sha256({k: v for k, v in obj.items() if k != "spec_sha256"})


def _assert_conveyor_specs(params: dict[str, Any]) -> None:
    expected = {
        "selection_rules_sha256": _spec_sha("SCOUT_CONVEYOR_SELECTION_RULES_v0.1.json"),
        "observer_sha256": _spec_sha("SCOUT_CONVEYOR_GENERIC_OBSERVER_v0.1.json"),
        "claim_boundary_sha256": _spec_sha("SCOUT_CONVEYOR_EVIDENCE_CLAIM_FIREWALL_v0.1.json"),
    }
    for key, val in expected.items():
        if key in params and params[key] != val:
            raise RuntimeError(f"generic Scout frozen resource mismatch: {key}")


def _rows_from_merged(merged: dict[str, Any]) -> tuple[list[dict[str, Any]], dict[str, set[str]], Counter[str], dict[str, set[str]]]:
    pars = {h: set(v) for h, v in merged["parents"].items()}
    wit = Counter({h: int(v) for h, v in merged["witness_count"].items()})
    src_child = {s: set(v) for s, v in merged["source_children"].items()}
    rows = []
    for h, raw in merged["children"].items():
        # Reuse the already-canonical repr generated by the composer.
        import ast
        rec = _canon(ast.literal_eval(raw))
        rows.append({"sha256": h, "record": rec, "parent_count_bounded": len(pars.get(h, set())), "witness_count": int(wit[h])})
    rows.sort(key=lambda x: x["sha256"])
    return rows, pars, wit, src_child


def exact_select_from_merged(merged: dict[str, Any], source_order: list[str], per_lane: int = PER_LANE) -> tuple[dict[str, Any], dict[str, Any], dict[str, Any]]:
    rows, pars, wit, src_child = _rows_from_merged(merged)
    if per_lane != PER_LANE:
        raise RuntimeError("conveyor scientific lane size is frozen at 256")
    N = min(per_lane, len(rows))
    row_by_sha = {x["sha256"]: x for x in rows}
    D, exact_meta = _farthest_exact(rows, N)
    B = sorted(rows, key=lambda x: (-x["parent_count_bounded"], -x["witness_count"], x["sha256"]))[:N]
    S = sorted(rows, key=lambda x: (len(set(x["record"][1])), max(Counter(x["record"][1]).values()), x["sha256"]))[:N]
    O = sorted(rows, key=lambda x: (-sum(v * (v - 1) // 2 for v in Counter(x["record"][1]).values()), -x["parent_count_bounded"], -x["witness_count"], x["sha256"]))[:N]
    line: list[dict[str, Any]] = []
    seen: set[str] = set()
    for ssha in source_order:
        hs = sorted(src_child.get(ssha, set()))
        if hs and len(line) < N and hs[0] not in seen:
            line.append(row_by_sha[hs[0]])
            seen.add(hs[0])
    for x in rows:
        if len(line) >= N:
            break
        if x["sha256"] not in seen:
            line.append(x)
            seen.add(x["sha256"])
    lanes = {"D": D, "B": B, "S": S, "O": O, "L": line}
    union = {x["sha256"]: x for lane in LANE_ORDER for x in lanes[lane]}
    selected = sorted(union.values(), key=lambda x: x["sha256"])
    selset = set(union)
    edges = sorted((s, h) for s in source_order for h in src_child.get(s, set()) if h in selset)
    pair = Counter()
    for s in source_order:
        hs = sorted(h for h in src_child.get(s, set()) if h in selset)
        for i in range(len(hs)):
            for j in range(i + 1, len(hs)):
                pair[(hs[i], hs[j])] += 1
    fib = Counter(tuple(sorted(pars[x["sha256"]])) for x in selected)
    br = {
        "selected_union": len(selected),
        "relation_edges": len(edges),
        "selected_multi_parent": sum(x["parent_count_bounded"] >= 2 for x in selected),
        "selected_max_parent_count": max((x["parent_count_bounded"] for x in selected), default=0),
        "shared_parent_pair_count": len(pair),
        "shared_parent_multiplicity_histogram": {str(k): v for k, v in sorted(Counter(pair.values()).items())},
        "distinct_exact_parent_fibers": len(fib),
        "selected_parent_histogram": {str(k): v for k, v in sorted(Counter(x["parent_count_bounded"] for x in selected).items())},
    }
    relation = {
        "selected": [
            {"sha256": x["sha256"], "record": repr(x["record"]), "bounded_parent_count": x["parent_count_bounded"], "witness_count": x["witness_count"]}
            for x in selected
        ],
        "edges": edges,
    }
    lane_seal = {
        "schema_id": "IG_SCOUT_GENERIC_SEALED_LANES_V0_1",
        "selection_rules_sha256": _spec_sha("SCOUT_CONVEYOR_SELECTION_RULES_v0.1.json"),
        "per_lane": N,
        "lane_order": LANE_ORDER,
        "lanes": {k: [x["sha256"] for x in lanes[k]] for k in LANE_ORDER},
        "selected_union": [x["sha256"] for x in selected],
        "selected_union_count": len(selected),
        "D_lane_exactness": exact_meta,
        "sealed_before_relation_analysis": True,
        "no_outcome_feedback": True,
    }
    wide = {
        "status": "SCOUT_COMPLETE",
        "evidence_label": "SCOUT_OBSERVED",
        "authority": "RECONNAISSANCE_ONLY",
        "population_complete": False,
        "generation": {
            "source_count": len(source_order),
            "attempts": int(merged["attempts"]),
            "lawful": int(merged["lawful"]),
            "unique_candidates": len(rows),
            "multi_parent_candidates": sum(len(v) >= 2 for v in pars.values()),
            "max_bounded_parent_count": max((len(v) for v in pars.values()), default=0),
        },
        "selection": {"per_lane": N, "union_selected": len(selected), "D_lane_exactness": exact_meta},
        "bounded_relation": br,
        "prohibitions": PROHIBITIONS,
    }
    return wide, relation, lane_seal


def normalize_parent_baseline(*, level: int, baseline: dict[str, Any], classification: dict[str, Any]) -> dict[str, Any]:
    r = baseline["relations"]
    closure = r["R_PARTIAL_CLOSURE"]["metrics"]
    ref = r["R_REFINEMENT_INDIVIDUATION"]["metrics"]
    return {
        "schema_id": "IG_SCOUT_NORMALIZED_PARENT_BASELINE_V0_1",
        "level": int(level),
        "evidence_label": "SCOUT_OBSERVED",
        "authority": "RECONNAISSANCE_ONLY",
        "population_complete": False,
        "relations": {
            "R_PARENT_FIBER": {"present": r["R_PARENT_FIBER"]["metrics"].get("distinct_parent_fibers", 0) > 0, "selected_max_parent_count": r["R_PARENT_FIBER"]["metrics"].get("selected_max_parent_count", 0)},
            "R_SHARED_SUPPORT": {"present": r["R_SHARED_SUPPORT"]["metrics"].get("shared_parent_pair_count", 0) > 0},
            "R_FIBER_INCLUSION": {"present": r["R_FIBER_INCLUSION"]["metrics"].get("strict_inclusion_pairs", 0) > 0, "height": r["R_FIBER_INCLUSION"]["metrics"].get("height", 0), "width": r["R_FIBER_INCLUSION"]["metrics"].get("width", 0)},
            "R_PARTIAL_CLOSURE": {"present": (closure.get("incomparable_intersection_realized", 0) + closure.get("incomparable_union_realized", 0)) > 0, "aggregate_intersection_fraction": closure.get("aggregate_intersection_realized_fraction", closure.get("intersection_realized_fraction", 0.0)), "aggregate_union_fraction": closure.get("aggregate_union_realized_fraction", closure.get("union_realized_fraction", 0.0))},
            "R_REFINEMENT_INDIVIDUATION": {"present": ref.get("stable_right_classes", 0) > 0, "right_singleton_fraction": ref.get("right_singleton_fraction", (ref.get("right_singletons", 0) / ref.get("right_nodes", 1) if ref.get("right_nodes", 0) else 0.0))},
            "R_LOCAL_DEPTH_REORGANIZATION": {"status": r["R_LOCAL_DEPTH_REORGANIZATION"].get("status", "UNRESOLVED_DEPTH_SCOPE")},
        },
        "classification": {
            "persistent": list(classification.get("persistent", [])),
            "current_level_escalated_for_review": list(classification.get("current_level_escalated_for_review", classification.get("escalated_for_review", []))),
            "summary": classification.get("summary", classification.get("classification_summary")),
        },
    }


def build_generic_baseline(*, wide: dict[str, Any], spec: dict[str, Any], parent: dict[str, Any], source_level: int, target_level: int) -> dict[str, Any]:
    br, order, ref, scope = wide["bounded_relation"], spec["order"], spec["refinement"], spec["scope"]
    inc = spec["closure_breakdown"]["incomparable"]
    pr = parent["relations"]
    right_frac = ref["right_singletons"] / scope["right_nodes"] if scope["right_nodes"] else 0.0
    rel = {
        "R_PARENT_FIBER": {"metrics": {"distinct_parent_fibers": br["distinct_exact_parent_fibers"], "selected_max_parent_count": br["selected_max_parent_count"], "selected_multi_parent": br["selected_multi_parent"], "selected_union": br["selected_union"], "multi_parent_fraction": br["selected_multi_parent"] / br["selected_union"] if br["selected_union"] else 0.0}, "parent": pr["R_PARENT_FIBER"]},
        "R_SHARED_SUPPORT": {"metrics": {"shared_parent_pair_count": br["shared_parent_pair_count"], "max_shared_parent_multiplicity": max(map(int, br["shared_parent_multiplicity_histogram"].keys()), default=0)}, "parent": pr["R_SHARED_SUPPORT"]},
        "R_FIBER_INCLUSION": {"metrics": {"strict_inclusion_pairs": order["strict_inclusion_pairs"], "cover_relations": order["cover_relations"], "height": order["height"], "width": order["width"]}, "parent": pr["R_FIBER_INCLUSION"]},
        "R_PARTIAL_CLOSURE": {"metrics": {"incomparable_pairs": inc["pairs"], "incomparable_intersection_realized": inc["intersection_realized"], "incomparable_union_realized": inc["union_realized"], "incomparable_both_realized": inc["both_realized"], "incomparable_intersection_fraction": inc["intersection_fraction"], "incomparable_union_fraction": inc["union_fraction"], "aggregate_intersection_realized_fraction": spec["closure"]["intersection_realized_fraction"], "aggregate_union_realized_fraction": spec["closure"]["union_realized_fraction"]}, "parent": pr["R_PARTIAL_CLOSURE"]},
        "R_REFINEMENT_INDIVIDUATION": {"metrics": {"left_nodes": scope["left_nodes"], "right_nodes": scope["right_nodes"], "left_singletons": ref["left_singletons"], "right_singletons": ref["right_singletons"], "right_singleton_fraction": right_frac, "stable_left_classes": ref["stable_left_classes"], "stable_right_classes": ref["stable_right_classes"]}, "parent": pr["R_REFINEMENT_INDIVIDUATION"]},
        "R_LOCAL_DEPTH_REORGANIZATION": {"status": "UNRESOLVED_DEPTH_SCOPE", "parent": pr["R_LOCAL_DEPTH_REORGANIZATION"]},
    }
    return {
        "schema_id": "IG_SCOUT_GENERIC_LEVEL_BASELINE_V0_1",
        "source_level": source_level,
        "level": target_level,
        "evidence_label": "SCOUT_OBSERVED",
        "authority": "RECONNAISSANCE_ONLY",
        "population_complete": False,
        "relations": rel,
        "scope": {"candidate_count": wide["generation"]["unique_candidates"], "relation_edges": br["relation_edges"], "selected_union": br["selected_union"]},
        "spectroscope": {"components": spec["incidence"]["components"], "abstract_cycle_rank_recognition_only": spec["incidence"]["abstract_cycle_rank"], "recognition_summary": spec["recognition_summary"], "closure_breakdown": spec["closure_breakdown"]},
        "prohibitions": PROHIBITIONS,
    }


def classify_generic(baseline: dict[str, Any]) -> dict[str, Any]:
    r = baseline["relations"]
    predicates = {
        "R_PARENT_FIBER.PERSISTS": r["R_PARENT_FIBER"]["metrics"]["distinct_parent_fibers"] > 0,
        "R_PARENT_FIBER.EXPANDS": r["R_PARENT_FIBER"]["metrics"]["selected_max_parent_count"] > r["R_PARENT_FIBER"]["parent"].get("selected_max_parent_count", 0),
        "R_SHARED_SUPPORT.PERSISTS": r["R_SHARED_SUPPORT"]["metrics"]["shared_parent_pair_count"] > 0,
        "R_FIBER_INCLUSION.PERSISTS": r["R_FIBER_INCLUSION"]["metrics"]["strict_inclusion_pairs"] > 0,
        "R_FIBER_INCLUSION.REORGANIZES": r["R_FIBER_INCLUSION"]["metrics"]["height"] != r["R_FIBER_INCLUSION"]["parent"].get("height", 0),
        "R_PARTIAL_CLOSURE.PERSISTS": (r["R_PARTIAL_CLOSURE"]["metrics"]["incomparable_intersection_realized"] + r["R_PARTIAL_CLOSURE"]["metrics"]["incomparable_union_realized"]) > 0,
        "R_PARTIAL_CLOSURE.REORGANIZES": (r["R_PARTIAL_CLOSURE"]["metrics"]["aggregate_intersection_realized_fraction"] != r["R_PARTIAL_CLOSURE"]["parent"].get("aggregate_intersection_fraction", 0.0) or r["R_PARTIAL_CLOSURE"]["metrics"]["aggregate_union_realized_fraction"] != r["R_PARTIAL_CLOSURE"]["parent"].get("aggregate_union_fraction", 0.0)),
        "R_REFINEMENT_INDIVIDUATION.PERSISTS": r["R_REFINEMENT_INDIVIDUATION"]["metrics"]["stable_right_classes"] > 0,
        "R_REFINEMENT_INDIVIDUATION.REORGANIZES": r["R_REFINEMENT_INDIVIDUATION"]["metrics"]["right_singleton_fraction"] != r["R_REFINEMENT_INDIVIDUATION"]["parent"].get("right_singleton_fraction", 0.0),
        "R_LOCAL_DEPTH_REORGANIZATION.UNRESOLVED_DEPTH_SCOPE": r["R_LOCAL_DEPTH_REORGANIZATION"]["status"] == "UNRESOLVED_DEPTH_SCOPE",
    }
    persistent = sorted({k.split(".")[0] for k, v in predicates.items() if v and k.endswith(".PERSISTS")})
    expanded = sorted({k.split(".")[0] for k, v in predicates.items() if v and k.endswith(".EXPANDS")})
    reorganized = sorted({k.split(".")[0] for k, v in predicates.items() if v and k.endswith(".REORGANIZES")})
    unresolved = sorted({k.split(".")[0] for k, v in predicates.items() if v and k.endswith(".UNRESOLVED_DEPTH_SCOPE")})
    parts = []
    if persistent:
        parts.append("PERSISTS")
    if expanded:
        parts.append("EXPANDS")
    if reorganized:
        parts.append("REORGANIZES")
    summary = " + ".join(parts) + " (bounded panel only)" if parts else "UNDEFINED"
    registered = {"PERSISTS", "PERSISTS + EXPANDS", "PERSISTS + REORGANIZES", "PERSISTS + EXPANDS + REORGANIZES"}
    base_summary = summary.replace(" (bounded panel only)", "")
    defined = base_summary in registered
    return {
        "schema_id": "IG_SCOUT_GENERIC_LEVEL_CLASSIFICATION_V0_1",
        "level": baseline["level"],
        "source_level": baseline["source_level"],
        "evidence_label": "SCOUT_OBSERVED",
        "authority": "RECONNAISSANCE_ONLY",
        "classification_method": "EXPLICIT_METRIC_PREDICATES",
        "classification_defined": defined,
        "predicates": predicates,
        "persistent": persistent,
        "expanded": expanded,
        "reorganized_or_refined": reorganized,
        "unresolved": unresolved,
        "observed_or_new": [],
        "destroyed_or_relieved": [],
        "current_level_escalated_for_review": [],
        "explicit_review_escalations": [],
        "review_escalation_policy": "EXPLICIT_REVIEW_PREDICATES_ONLY_NOT_ORDINARY_EXPANSION",
        "depth_status": r["R_LOCAL_DEPTH_REORGANIZATION"]["status"],
        "summary": summary,
        "prohibitions": PROHIBITIONS,
    }


@register_runner("adapter.scout_level.preflight")
def preflight_stage(*, controller, plan, stage, work_dir, run_dir):
    _assert_conveyor_specs(stage["params"])
    fixture = controller.datasets.materialize(stage["params"]["fixture_dataset_sha256"], work_dir / "fixture")
    src = fixture / "PARENT_SELECTED_RELATION.json"
    prim = fixture / "primitive.pkl"
    if sha256_file(src) != stage["params"]["root_sha256"]:
        raise RuntimeError("parent selected-relation file identity mismatch")
    if sha256_file(prim) != stage["params"]["primitive_sha256"]:
        raise RuntimeError("primitive identity mismatch")
    sources = load_fixture_sources(fixture)
    if len(sources) != int(stage["params"]["root_count"]):
        raise RuntimeError("parent root count mismatch")
    parent = json.loads((fixture / "PARENT_NORMALIZED_BASELINE.json").read_text(encoding="utf-8"))
    if int(parent["level"]) != int(stage["params"]["source_level"]):
        raise RuntimeError("parent normalized baseline level mismatch")
    result = {"status": "PASS", "source_level": int(stage["params"]["source_level"]), "target_level": int(stage["params"]["target_level"]), "root_count": len(sources), "root_sha256": stage["params"]["root_sha256"], "primitive_sha256": stage["params"]["primitive_sha256"], "evidence_label": "SCOUT_OBSERVED", "population_complete": False}
    p = work_dir / "SCOUT_LEVEL_PREFLIGHT_RESULT.json"
    write_json_atomic(p, result)
    return {"outputs": {"SCOUT_LEVEL_PREFLIGHT_RESULT.json": p}, "stage_result": result}


@register_runner("adapter.scout_level.wide_chunked")
def wide_chunked_stage(*, controller, plan, stage, work_dir, run_dir):
    _assert_conveyor_specs(stage["params"])
    fixture = controller.datasets.materialize(stage["params"]["fixture_dataset_sha256"], work_dir / "fixture")
    sources = load_fixture_sources(fixture)
    prim = load_fixture_primitive(fixture)
    chunk_size = int(stage["params"]["generation_chunk_parent_count"])
    binding = {
        "plan_sha256": plan["plan_sha256"],
        "stage_spec_sha256": canonical_sha256(stage),
        "fixture_dataset_sha256": stage["params"]["fixture_dataset_sha256"],
        "root_sha256": stage["params"]["root_sha256"],
        "primitive_sha256": stage["params"]["primitive_sha256"],
        "source_level": int(stage["params"]["source_level"]),
        "target_level": int(stage["params"]["target_level"]),
    }
    cpstore = ChunkCheckpointStore(Path(run_dir) / "chunks" / "wide", binding)
    chunks = []
    reused = computed = 0
    for rng in chunk_parent_ranges(sources, chunk_size):
        chunk_spec = {k: v for k, v in rng.items() if k != "sources"}
        result, was_reused = cpstore.get_or_compute(chunk_id=rng["chunk_id"], chunk_spec=chunk_spec, compute=lambda part=rng["sources"]: compute_generation_chunk(part, prim))
        chunks.append(result)
        reused += int(was_reused)
        computed += int(not was_reused)
    cpstore.verify_all()
    merged = merge_generation_chunks(chunks)
    wide, relation, lane_seal = exact_select_from_merged(merged, [x["sha256"] for x in sources], int(stage["params"]["per_lane"]))
    wide.update({"stage": "SCOUT_LEVEL_WIDE_CHUNKED", "source_level": int(stage["params"]["source_level"]), "target_level": int(stage["params"]["target_level"]), "chunking": {"chunk_size": chunk_size, "chunk_count": len(chunks), "computed_chunks": computed, "reused_chunks": reused, "merge_independent_of_chunk_size": True}})
    outs = {}
    for name, obj in [("SCOUT_LEVEL_WIDE_RESULT.json", wide), ("SELECTED_RELATION.json", relation), ("SEALED_LANE_SELECTION.json", lane_seal)]:
        p = work_dir / name
        write_json_atomic(p, obj)
        outs[name] = p
    return {"outputs": outs, "stage_result": {"status": "PASS", "target": "SCOUT_LEVEL_WIDE_CHUNKED", "source_level": wide["source_level"], "target_level": wide["target_level"], "candidate_count": wide["generation"]["unique_candidates"], "selected_union": wide["bounded_relation"]["selected_union"], "computed_chunks": computed, "reused_chunks": reused}}


@register_runner("adapter.scout_level.spectroscope")
def spectroscope_stage(*, controller, plan, stage, work_dir, run_dir):
    from .scout_l16 import _dependency_artifact
    if stage["params"].get("recognition_only") is not True or stage["params"].get("cannot_feedback") is not True:
        raise RuntimeError("Spectroscope non-feedback contract violated")
    relp = _dependency_artifact(controller, run_dir, "wide", "SELECTED_RELATION.json", work_dir / "inputs/SELECTED_RELATION.json")
    level = int(stage["params"]["target_level"])
    result = run_scout_spectroscope(relp, work_dir / "spectroscope", level)
    result = {k: v for k, v in result.items() if k != "cost"}
    relation = json.loads(relp.read_text(encoding="utf-8"))
    result["closure_breakdown"] = _closure_breakdown(relation)
    result["recognition_summary"] = _forward_recognition(result, result["closure_breakdown"])
    result["test_id"] = f"SCOUT_SPECTROSCOPE_L{level}_CONVEYOR_V0_1"
    out = work_dir / "SCOUT_SPECTROSCOPE_RESULT.json"
    write_json_atomic(out, result)
    return {"outputs": {"SCOUT_SPECTROSCOPE_RESULT.json": out}, "stage_result": {"status": "PASS", "recognition_only": True, "authority": "RECONNAISSANCE_ONLY", "recognition_summary": result["recognition_summary"]}}


@register_runner("adapter.scout_level.classify")
def classify_stage(*, controller, plan, stage, work_dir, run_dir):
    from .scout_l16 import _dependency_artifact
    _assert_conveyor_specs(stage["params"])
    fixture = controller.datasets.materialize(stage["params"]["fixture_dataset_sha256"], work_dir / "fixture")
    pwide = _dependency_artifact(controller, run_dir, "wide", "SCOUT_LEVEL_WIDE_RESULT.json", work_dir / "inputs/SCOUT_LEVEL_WIDE_RESULT.json")
    pspec = _dependency_artifact(controller, run_dir, "spectroscope", "SCOUT_SPECTROSCOPE_RESULT.json", work_dir / "inputs/SCOUT_SPECTROSCOPE_RESULT.json")
    wide = json.loads(pwide.read_text(encoding="utf-8"))
    spec = json.loads(pspec.read_text(encoding="utf-8"))
    parent = json.loads((fixture / "PARENT_NORMALIZED_BASELINE.json").read_text(encoding="utf-8"))
    baseline = build_generic_baseline(wide=wide, spec=spec, parent=parent, source_level=int(stage["params"]["source_level"]), target_level=int(stage["params"]["target_level"]))
    classification = classify_generic(baseline)
    projections = {
        "schema_id": "IG_SCOUT_GENERIC_LEVEL_SCIENCE_PROJECTIONS_V0_1",
        "source_level": baseline["source_level"],
        "level": baseline["level"],
        "wide_sha256": canonical_sha256(wide),
        "spectroscope_sha256": canonical_sha256(spec),
        "baseline_sha256": canonical_sha256(baseline),
        "classification_sha256": canonical_sha256(classification),
        "timing_independent": True,
        "evidence_label": "SCOUT_OBSERVED",
        "authority": "RECONNAISSANCE_ONLY",
        "population_complete": False,
    }
    outs = {}
    for name, obj in [("SCOUT_LEVEL_BASELINE.json", baseline), ("SCOUT_LEVEL_CLASSIFICATION.json", classification), ("SCOUT_LEVEL_SCIENCE_PROJECTIONS.json", projections)]:
        p = work_dir / name
        write_json_atomic(p, obj)
        outs[name] = p
    return {"outputs": outs, "stage_result": {"status": "PASS" if classification["classification_defined"] else "UNDEFINED", "summary": classification["summary"], "authority": "RECONNAISSANCE_ONLY"}}


@register_runner("adapter.scout_level.verify_independent")
def verify_stage(*, controller, plan, stage, work_dir, run_dir):
    from .scout_l16 import _dependency_artifact
    _assert_conveyor_specs(stage["params"])
    fixture = controller.datasets.materialize(stage["params"]["fixture_dataset_sha256"], work_dir / "fixture_replay")
    sources = load_fixture_sources(fixture)
    prim = load_fixture_primitive(fixture)
    # Independent monolithic recomputation of generation + lane selection.
    merged = compute_generation_chunk(sources, prim)
    iwide, irelation, ilanes = exact_select_from_merged(merged, [x["sha256"] for x in sources], int(stage["params"]["per_lane"]))
    pwide = _dependency_artifact(controller, run_dir, "wide", "SCOUT_LEVEL_WIDE_RESULT.json", work_dir / "inputs/SCOUT_LEVEL_WIDE_RESULT.json")
    prel = _dependency_artifact(controller, run_dir, "wide", "SELECTED_RELATION.json", work_dir / "inputs/SELECTED_RELATION.json")
    planes = _dependency_artifact(controller, run_dir, "wide", "SEALED_LANE_SELECTION.json", work_dir / "inputs/SEALED_LANE_SELECTION.json")
    pcl = _dependency_artifact(controller, run_dir, "classify", "SCOUT_LEVEL_CLASSIFICATION.json", work_dir / "inputs/SCOUT_LEVEL_CLASSIFICATION.json")
    wide = json.loads(pwide.read_text(encoding="utf-8"))
    relation = json.loads(prel.read_text(encoding="utf-8"))
    lanes = json.loads(planes.read_text(encoding="utf-8"))
    classification = json.loads(pcl.read_text(encoding="utf-8"))
    prod_projection = {"generation": wide["generation"], "selection": wide["selection"], "bounded_relation": wide["bounded_relation"]}
    indep_projection = {"generation": iwide["generation"], "selection": iwide["selection"], "bounded_relation": iwide["bounded_relation"]}
    comparisons = {
        "wide_science_projection": canonical_sha256(prod_projection) == canonical_sha256(indep_projection),
        "selected_relation": canonical_sha256(relation) == canonical_sha256(irelation),
        "sealed_lanes": canonical_sha256({k: v for k, v in lanes.items() if k != "schema_id"}) == canonical_sha256({k: v for k, v in ilanes.items() if k != "schema_id"}),
        "classification_defined": classification.get("classification_defined") is True,
        "authority_reconnaissance_only": classification.get("authority") == "RECONNAISSANCE_ONLY",
    }
    status = "PASS" if all(comparisons.values()) else "FAIL"
    verification = {"schema_id": "IG_SCOUT_GENERIC_LEVEL_TERMINAL_VERIFICATION_V0_1", "status": status, "source_level": int(stage["params"]["source_level"]), "level": int(stage["params"]["target_level"]), "comparisons": comparisons, "independent_recomputation": "MONOLITHIC_EXACT_D_B_S_O_L", "historical_golden_used": False}
    p = work_dir / "SCOUT_LEVEL_TERMINAL_VERIFICATION.json"
    write_json_atomic(p, verification)
    if status != "PASS":
        raise RuntimeError(f"generic Scout independent verification failed: {comparisons}")
    return {"outputs": {"SCOUT_LEVEL_TERMINAL_VERIFICATION.json": p}, "stage_result": verification}
