"""Package independently cold-audited historical terminal reconstruction."""
from pathlib import Path
import json,hashlib,zipfile,datetime
B=Path(__file__).resolve().parent;W=B.parent
A=json.loads((B/'AUDIT.json').read_text());assert A['status']=='PASS_COLD_HISTORICAL_TERMINAL100_CONTINUATION'
assert json.loads((B/'CHECKPOINT_PRESERVED.json').read_text())['pending_bytes']==0
(B/'REPORT.txt').write_text('Checkpoint 0229: historical depths 99–100, terminal reconstruction verified.\n2026-10-09\n\nStarts from saved and independently cold-audited bootstrap98 in checkpoint0228. Historical scientific helpers are byte-identical. Two native tasks commit193 candidates each:386 total. Depth99 selects24 roots; depth100 retains all193 candidates. The historical24 beam selection is independently checked against archived depth100 roots, skins and capacity vectors. All193 terminal public interface records, including all seven endpoint-reservation outcomes, match the frozen reference byte-for-byte as exact JSON structures.\n\nNative completion is authenticated and preserved with zero pending bytes. Fresh cold restoration checks all dependencies, both full saved-state identities,217 root DAG roundtrips, the24-root beam and all193 interface records. Audit generates no candidates. The exact terminal193-root bootstrap100 DAG is exported.\n\nThe public interface helper is an exact AST extraction of the frozen engine pure extraction closure; producer execution wrappers are excluded. Registered workspace and snapshot limits are8GiB before capture. No engine or historical scientific helper changes.\n\nMaster remains151; no admissions. This closes the bounded historical terminal reconstruction and reference comparison, not the entire L0–G8 replay. Q2 payloads and authority binding remain open. Next: bind exact earned G1 ancestry and Q2 authority before fresh carrier generation or admissions.\n\nRecovery: verify MANIFEST.json, retrieve CHECKPOINT_EXPORT.json dependencies by Drive IDs in READBACKS.json, and verify every raw hash/size. Use restore_current.py with the pinned CPython3.13.5 / SQLite3.51.3 runtime and frozen engine. RUNTIME_RECOVERY_VALIDATION.json and RECOVERY_RUNTIME_PARTS.json retain runtime recovery references. PREDECESSOR_HANDOFF_REFERENCE.json identifies accepted0228. Local paths may expire; Drive IDs and hashes are authoritative.\n')
s=json.loads((W/'CURRENT_STATUS.json').read_text());s.pop('latest_handoff',None)
s.update(status_as_of_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),latest_checkpoint=229,latest_capture_id=json.loads((B/'POINTER.json').read_text())['capture_id'],current_phase='G1_HISTORICAL_TERMINAL100_NATIVE_COLD_VERIFIED',in_flight_active=None,active_native_runtime=None,completed_depth=100,historical_verified_depth=100,historical_cold_audited_depth=100,historical_reconstructed_depth=100,historical_reconstruction_acceptance='THROUGH100_WITH193_TERMINAL_PUBLIC_INTERFACES_QUALIFIED',candidate_build_calls=386,generator_calls=2,committed_generator_tasks=2,interrupted_generator_attempts=0,interrupted_candidate_work='NONE',generator_calls_scope='0229:two committed193-candidate phase tasks; audit generated none',pending_bytes=0,master_slices=151,new_admissions=0,terminal_comparison='PASS193_EXACT_PUBLIC_INTERFACES',terminal_roots=193,historical_depth100_beam_roots=24,next_scope='G1_Q2_EXACT_ANCESTRY_AUTHORITY_BINDING',next_scope_status='NO_FRESH_CARRIER_GENERATION_BEFORE_AUTHORITY_BINDING',Q2_payload_available=False,Q2_payload_generated=False,latest_audit=A,checkpoint0229=A,catalog_path=str(B/'CATALOG_0151.json'))
if (B/'CODE_MIRROR.json').exists():s['code_mirror']=json.loads((B/'CODE_MIRROR.json').read_text())
(W/'CURRENT_STATUS.json').write_text(json.dumps(s,indent=2));(B/'STATUS_CANDIDATE.json').write_text(json.dumps(s,indent=2))
files={str(p.relative_to(W)):p for p in sorted(B.rglob('*')) if p.is_file() and p.suffix in ('.py','.json','.txt','.zip','.log') and '__pycache__' not in p.parts and not p.name.startswith('private_') and p.name not in ('MIRROR_ELEMENTS.json','DELIVERABLES.json','SAVE_RECEIPT.json')}
boot=Path(json.loads((B/'BOOTSTRAP100_META.json').read_text())['path']);files['continuation0229/BOOTSTRAP100_HISTORICAL.json']=boot
manifest={k:dict(bytes=p.stat().st_size,sha256=hashlib.file_digest(p.open('rb'),'sha256').hexdigest()) for k,p in files.items()}
out=W/'IG_MASTER151_G1_HISTORICAL_TERMINAL100_0229_HANDOFF_2026-10-09.zip'
with zipfile.ZipFile(out,'w',zipfile.ZIP_DEFLATED,compresslevel=6) as z:
 for k,p in files.items():z.write(p,k)
 z.writestr('MANIFEST.json',json.dumps(manifest,indent=2))
with zipfile.ZipFile(out) as z:
 assert z.testzip() is None
 for k,v in manifest.items():assert hashlib.sha256(z.read(k)).hexdigest()==v['sha256']
r=dict(path=str(out),sha256=hashlib.file_digest(out.open('rb'),'sha256').hexdigest(),bytes=out.stat().st_size,checkpoint=229,status=A['status'],historical_verified_depth=100,native_completion_status='VERIFIED',terminal_comparison=A['terminal_comparison'],master_slices=151,new_admissions=0,native_pending_bytes=0,next_scope=s['next_scope']);(B/'DELIVERABLES.json').write_text(json.dumps(r,indent=2));print(json.dumps(r))
