"""Preserve a failed terminal comparison without promoting scientific acceptance."""
from pathlib import Path
import json,hashlib,zipfile,datetime
B=Path(__file__).resolve().parent;W=B.parent
A=json.loads((B/'STOPPED_AUDIT.json').read_text());assert A['status']=='PASS_COLD_STOPPED_CAPTURE_DEPTH99'
assert json.loads((B/'CHECKPOINT_PRESERVED.json').read_text())['pending_bytes']==0
h='9a3501e39a5f9bcd8c138088380b906aaf3e2098d5ef48b6243ffa7e7f54d48b';r=json.loads((B/'READBACKS.json').read_text())[h];assert r['raw_readback_verified']
(B/'NATIVE_EXPORT_SAVE.json').write_text(json.dumps(dict(sha256=h,**r),indent=2))
f=dict(status='STOPPED_TERMINAL193_COMPARISON_FAILED',native_completion_status='FAILED',accepted_historical_depth=98,latest_accepted_checkpoint=228,depth99_committed=True,depth99_cold_restored=True,depth100_committed=False,observed_terminal_population_persisted=False,exact_differing_fields='UNKNOWN',terminal_comparison='FAILED_UNDIAGNOSED',committed_generator_tasks=1,failed_generator_attempts=1,committed_candidate_census=193,failed_attempt_candidate_census_inferred_from_failure_location=193,historical100_beam_gate='PASSED_BEFORE_FAILURE_INFERRED_FROM_EXECUTION_PATH',master_slices=151,new_admissions=0,next_scope='REGISTERED_TERMINAL193_DIAGNOSTIC_FROM_SAVED99')
(B/'FAILURE_STATUS.json').write_text(json.dumps(f,indent=2))
(B/'REPORT.txt').write_text('Checkpoint 0229: STOPPED at terminal193 public interface population comparison.\n\nDepth99 committed one193-candidate task selecting24 roots. Independent cold restoration verified exact saved-state identity and all24 root DAG roundtrips with zero candidate generation. Depth100 has zero committed tasks and states. Its archived24-beam gate passed before the whole-population comparison raised TERMINAL193_PUBLIC_INTERFACE_MISMATCH; this is inferred from the frozen execution path, not an independent depth100 audit. The observed terminal population was not persisted before the exception. Exact differing fields remain UNKNOWN; no metadata-only diagnosis is established.\n\nNative completion FAILED. Accepted historical depth remains98, accepted checkpoint0228. Master remains151; no admissions. Failure checkpoint dependencies and slim export are preserved with exact raw readbacks and zero pending bytes. The original failed live capture is retained.\n\nThe interface helper uses the exact AST extraction of the frozen engine pure closure. Historical helpers are byte-identical to0228. Registered workspace and snapshot budgets were8GiB before capture. No failed gate is relaxed. Planned package.py and audit_cold.py are retained as unused operator sources; they were not executed. Only audit_stopped.py and package_failure.py describe this stopped outcome.\n\nNext: a newly registered diagnostic capture starting from saved99, without regenerating99. Persist the observed full terminal population and exact diagnostic differences before making the gate decision. Keep admissions closed while reviewing reference authority and the mismatch.\n\nRecovery: verify every MANIFEST.json member; retrieve CHECKPOINT_EXPORT.json dependencies using READBACKS.json Drive IDs and exact hashes/sizes. Restore with the pinned CPython3.13.5 / SQLite3.51.3 runtime and frozen engine. Runtime recovery and predecessor references are included. BOOTSTRAP99_HISTORICAL.json is an exact cold-restored continuation input, not a promoted accepted boundary.\n')
s=json.loads((W/'CURRENT_STATUS.json').read_text());s.pop('latest_handoff',None)
s.update(status_as_of_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),latest_checkpoint=229,latest_accepted_checkpoint=228,latest_capture_id=json.loads((B/'POINTER.json').read_text())['capture_id'],active_capture_id=json.loads((B/'POINTER.json').read_text())['capture_id'],current_phase='G1_TERMINAL100_COMPARISON_STOPPED',in_flight_active=None,active_native_runtime=None,completed_depth=98,historical_verified_depth=98,historical_cold_audited_depth=98,historical_reconstructed_depth=98,candidate_build_calls=193,candidate_count_scope='Committed depth99 census only; failed100 census193 inferred from failure location',generator_calls=2,committed_generator_tasks=1,failed_generator_attempts=1,generator_calls_scope='0229:one committed task and one failed attempt; audit generated none',interrupted_generator_attempts=0,interrupted_candidate_work='No interrupted attempt; depth100 failed comparison before commit',pending_bytes=0,master_slices=151,new_admissions=0,terminal_comparison='FAILED_UNDIAGNOSED',depth99_committed_and_cold_restored=True,bootstrap99=json.loads((B/'BOOTSTRAP99_META.json').read_text()),next_scope=f['next_scope'],next_scope_status='FAILED_GATE_REQUIRES_DIAGNOSIS',Q2_payload_available=False,Q2_payload_generated=False,latest_audit=A,checkpoint0229=f,catalog_path=str(B/'CATALOG_0151.json'))
if (B/'CODE_MIRROR.json').exists():s['code_mirror']=json.loads((B/'CODE_MIRROR.json').read_text())
(W/'CURRENT_STATUS.json').write_text(json.dumps(s,indent=2));(B/'STATUS_CANDIDATE.json').write_text(json.dumps(s,indent=2))
files={str(p.relative_to(W)):p for p in sorted(B.rglob('*')) if p.is_file() and p.suffix in ('.py','.json','.txt','.zip','.log') and '__pycache__' not in p.parts and not p.name.startswith('private_') and p.name not in ('MIRROR_ELEMENTS.json','DELIVERABLES.json','SAVE_RECEIPT.json')}
files['continuation0229/BOOTSTRAP99_HISTORICAL.json']=Path(s['bootstrap99']['path'])
manifest={k:dict(bytes=p.stat().st_size,sha256=hashlib.file_digest(p.open('rb'),'sha256').hexdigest()) for k,p in files.items()}
out=W/'IG_MASTER151_G1_TERMINAL100_STOPPED_0229_HANDOFF_2026-10-09.zip'
with zipfile.ZipFile(out,'w',zipfile.ZIP_DEFLATED,compresslevel=6) as z:
 for k,p in files.items():z.write(p,k)
 z.writestr('MANIFEST.json',json.dumps(manifest,indent=2))
with zipfile.ZipFile(out) as z:
 assert z.testzip() is None
 for k,v in manifest.items():assert hashlib.sha256(z.read(k)).hexdigest()==v['sha256']
r=dict(path=str(out),sha256=hashlib.file_digest(out.open('rb'),'sha256').hexdigest(),bytes=out.stat().st_size,checkpoint=229,status=f['status'],historical_verified_depth=98,native_completion_status='FAILED',terminal_comparison='FAILED_UNDIAGNOSED',master_slices=151,new_admissions=0,native_pending_bytes=0,next_scope=f['next_scope']);(B/'DELIVERABLES.json').write_text(json.dumps(r,indent=2));print(json.dumps(r))
