"""Package cold-verified diagnostic evidence without scientific promotion."""
from pathlib import Path
import json,hashlib,zipfile,datetime
B=Path(__file__).resolve().parent;W=B.parent;A=json.loads((B/'AUDIT.json').read_text());assert A['status']=='PASS_COLD_DIAGNOSTIC_SAVED_BYTES';assert json.loads((B/'CHECKPOINT_PRESERVED.json').read_text())['pending_bytes']==0
D=json.loads((B/'TERMINAL100_DIAGNOSTIC_REPORT.json').read_text())
(B/'REPORT.txt').write_text('Checkpoint0230: terminal100 diagnostic only.\n\nOne193-candidate task reconstructed depth100 from exact cold-restored bootstrap99; depth99 was not regenerated. Observed full population and terminal delta state were persisted. Native completion verifies only the registered diagnostic execution, not historical scientific acceptance. Independent cold restoration checked full saved-state canonical identity, assembled DAG science hash, all193 saved interface rows, and exact difference report. Audit generated zero candidates. Full193 decoded-state DAG roundtrips were not performed in this diagnostic audit.\n\nBeam gate: '+A['beam_gate']+'\nTerminal whole population: '+A['terminal_comparison']+'\nInterface rows exact equal: '+str(A['interface_rows_exact_equal'])+'\nTop-level differing keys: '+str(A['top_level_differing_keys'])+'\nDifference counts: '+str(A['difference_counts'])+'\n\nAccepted historical depth remains98, latest accepted checkpoint0228. Prior failed0229 capture is retained without changes. Master151, no admissions. No failed gate was relaxed. Next: review exact differences and reference provenance, then register any justified correction or scientific requalification separately.\n\nRecovery: verify MANIFEST.json; obtain exact CHECKPOINT_EXPORT.json dependencies by READBACKS.json Drive IDs and raw hashes/sizes. restore_current.py uses pinned runtime and frozen engine. Runtime recovery references and predecessor handoff receipt are included.\n')
s=json.loads((W/'CURRENT_STATUS.json').read_text());s.pop('latest_handoff',None);s.update(status_as_of_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),latest_checkpoint=230,latest_accepted_checkpoint=228,latest_capture_id=json.loads((B/'POINTER.json').read_text())['capture_id'],in_flight_active=None,active_native_runtime=None,current_phase='G1_TERMINAL100_DIAGNOSTIC_RECORDED',completed_depth=98,historical_verified_depth=98,historical_cold_audited_depth=98,historical_reconstructed_depth=98,latest_audit=A,checkpoint0230=A,terminal_comparison=A['terminal_comparison'],terminal_diagnostic_only=True,candidate_build_calls=193,generator_calls=1,committed_generator_tasks=1,failed_generator_attempts=0,generator_calls_scope='0230:one committed diagnostic193-candidate task; zero audit generation',pending_bytes=0,master_slices=151,new_admissions=0,next_scope='TERMINAL_DIFFERENCE_AND_REFERENCE_PROVENANCE_REVIEW',next_scope_status='NO_SCIENTIFIC_PROMOTION_FROM_DIAGNOSTIC',catalog_path=str(B/'CATALOG_0151.json'))
if (B/'CODE_MIRROR.json').exists():s['code_mirror']=json.loads((B/'CODE_MIRROR.json').read_text())
(W/'CURRENT_STATUS.json').write_text(json.dumps(s,indent=2));(B/'STATUS_CANDIDATE.json').write_text(json.dumps(s,indent=2))
files={str(p.relative_to(W)):p for p in sorted(B.rglob('*')) if p.is_file() and p.suffix in ('.py','.json','.txt','.zip','.log','.gz') and '__pycache__' not in p.parts and not p.name.startswith('private_') and p.name not in ('MIRROR_ELEMENTS.json','DELIVERABLES.json','SAVE_RECEIPT.json')}
manifest={k:dict(bytes=p.stat().st_size,sha256=hashlib.file_digest(p.open('rb'),'sha256').hexdigest()) for k,p in files.items()};out=W/'IG_MASTER151_G1_TERMINAL100_DIAGNOSTIC_0230_HANDOFF_2026-10-09.zip'
with zipfile.ZipFile(out,'w',zipfile.ZIP_DEFLATED,compresslevel=6) as z:
 for k,p in files.items():z.write(p,k)
 z.writestr('MANIFEST.json',json.dumps(manifest,indent=2))
with zipfile.ZipFile(out) as z:
 assert z.testzip() is None
 for k,v in manifest.items():assert hashlib.sha256(z.read(k)).hexdigest()==v['sha256']
r=dict(path=str(out),sha256=hashlib.file_digest(out.open('rb'),'sha256').hexdigest(),bytes=out.stat().st_size,checkpoint=230,status=A['status'],diagnostic_only=True,historical_verified_depth=98,native_completion_status='VERIFIED_DIAGNOSTIC_ONLY',terminal_comparison=A['terminal_comparison'],master_slices=151,new_admissions=0,native_pending_bytes=0,next_scope=s['next_scope']);(B/'DELIVERABLES.json').write_text(json.dumps(r,indent=2));print(json.dumps(r))
