export function elapsed(record,now) {
  if(!record || typeof record.started_unix!=='number')return 'Unknown';
  const end=record.finished_unix ?? now;
  if(typeof end!=='number' || end<record.started_unix)return 'Unknown';
  const seconds=Math.floor(end-record.started_unix);return Math.floor(seconds/60)+'m '+seconds%60+'s';
}
export function explanation(code){return ({SAVE_REQUIRED:'Awaiting backup. Required objects must be uploaded, read back and confirmed by Decoder.',PRESERVATION_UNCONFIRMED:'Backup readiness is unknown. Refresh the native observation.',ENGINE_RUNTIME_MISMATCH:'The configured engine environment does not match the pinned profile.',ENGINE_RUNTIME_UNAVAILABLE:'The configured engine environment could not be verified.',NATIVE_ADMISSION_STILL_REQUIRED:'You can request execution. Decoder will validate all native prerequisites before starting.',NATIVE_STOP_REQUIRES_REVIEW:'The native stop requires review. Resume is blocked.',IDLE_WITH_RUNNING_RECORD:'A running record remains but the workspace is idle. Reconcile the retained request.',WEB_REQUEST_UNRESOLVED:'A saved request is pending or unresolved. Do not submit another start.',WAIT_FOR_NATIVE_PAUSE:'Pause has been requested. Waiting for acknowledgment at a native safe boundary.',VIEW_RESULTS:'Execution has finished. Scientific outcome, evidence and preservation remain separate.',CHECKPOINT_PUBLICATION_PENDING:'Completion is waiting for checkpoint publication.',COOPERATIVE_PAUSE_AVAILABLE:'The native controller reports this job running. Pause is cooperative.'})[code] || 'Action unavailable: '+code;}
export function mountRun(token,back) {
  const $=id=>document.getElementById(id),s={job:null,epoch:0,view:null,busy:false,fresh:false,pending:null,logRequest:null,offset:0,cursor:0,logBusy:false};
  const node=(tag,value)=>{const e=document.createElement(tag);e.textContent=value;return e;};
  async function api(path,method='GET',body){const c=new AbortController(),t=setTimeout(()=>c.abort(),70000);try{const r=await fetch('/api/v1/'+path,{method,headers:{Authorization:'Bearer '+token(),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store',credentials:'omit',redirect:'error',signal:c.signal});const v=await r.json();if(!r.ok)throw new Error(v.error?.code || 'SERVER_UNAVAILABLE');return v;}finally{clearTimeout(t);}}
  function controls(){const action=s.view?.state.action;const b=$('run-action');b.hidden=!action && !s.pending;b.textContent=s.pending?'Reconcile saved action':({start:'Request start',resume:'Request resume',pause:'Request pause'})[action] || 'Action unavailable';b.disabled=s.busy || !navigator.onLine || (!s.fresh && !s.pending);$('run-refresh').disabled=s.busy;$('run-reason').hidden=action!=='pause';}
  function render(v){s.view=v;s.fresh=true;$('run-name').textContent=v.job.name;$('run-question').textContent=v.job.question;$('run-state').textContent=v.state.execution;$('run-note').textContent=explanation(v.state.reason);$('run-observed').textContent='Observed '+new Date(v.observed_at*1000).toLocaleTimeString();
    const record=v.native_status.native?.last_record;const matching=record?.job_id===v.job.native_job_id;
    const facts=[['Job ID',v.job.native_job_id],['Backup',v.state.backup],['Stage / operation',matching?record.operation || 'Unknown':'Unknown'],['Elapsed at observation',matching?elapsed(record,v.observed_at):'Unknown'],['Progress','No total reported'],['Environment',v.runtime]];
    $('run-facts').replaceChildren();for(const [k,value] of facts){const d=node('div','');d.append(node('dt',k),node('dd',value));$('run-facts').append(d);}
    const b=$('run-backup');b.replaceChildren();for(const [name,o] of Object.entries(v.preservation)){const rows=o.native?.pending_objects;b.append(node('p',name+': '+(Array.isArray(rows)?rows.length+' pending obligations':'Unknown')));if(Array.isArray(rows))for(const r of rows.slice(0,20))b.append(node('p',(r.role || 'Object')+' · '+(r.logical_name || r.sha256 || 'Identity unknown')));if(rows?.length>20)b.append(node('p','Further obligations are available in technical details.'));}b.append(node('p','Drive transfer controls are planned for Block 4. A saved checkbox cannot verify backup.'));
    $('run-raw').textContent=JSON.stringify(v,null,2);$('run-requests').replaceChildren();for(const r of v.requests){const row=node('button',r.operation+' · '+r.status+' · '+r.id);row.addEventListener('click',()=>{s.logRequest=r.id;s.offset=0;s.cursor=0;$('run-log').textContent='';$('run-events').textContent='';$('run-request-detail').textContent='';$('run-activity').open=true;logs();});$('run-requests').append(row);}controls();
  }
  async function refresh(){if(s.busy || !s.job || !token())return;const epoch=s.epoch;s.busy=true;s.fresh=false;controls();try{const v=await api('jobs/'+encodeURIComponent(s.job.id)+'/run-view');if(epoch!==s.epoch)return;render(v);}catch(e){if(epoch!==s.epoch)return;$('run-note').textContent='Observation unavailable or stale: '+e.message+'. Execution may still continue.';}finally{if(epoch===s.epoch){s.busy=false;controls();}}}
  async function logs(){if(s.logBusy || !s.logRequest)return;const epoch=s.epoch,id=s.logRequest,stream=$('run-stream').value;s.logBusy=true;try{const [log,events,record]=await Promise.all([api('requests/'+id+'/logs/'+stream+'?offset='+s.offset+'&limit=16384'),api('requests/'+id+'/events?cursor='+s.cursor+'&limit=30'),api('requests/'+id)]);if(epoch!==s.epoch || id!==s.logRequest || stream!==$('run-stream').value)return;s.offset=log.next_offset;s.cursor=events.next_cursor;$('run-log').textContent=($('run-log').textContent+log.text).slice(-65536);$('run-events').textContent=($('run-events').textContent+events.items.map(e=>e.kind+' '+JSON.stringify(e.detail)).join('\n')+'\n').slice(-32768);$('run-request-detail').textContent=JSON.stringify(record,null,2);}catch(e){if(epoch===s.epoch)$('run-log').textContent='Unable to read request: '+e.message;}finally{if(epoch===s.epoch)s.logBusy=false;}}
  $('run-action').addEventListener('click',async()=>{if(s.busy || (!s.fresh && !s.pending))return;const epoch=s.epoch;const body=s.pending || {action:s.view.state.action,view_token:s.view.view_token,...(s.view.state.action==='pause'?{reason:$('run-reason-input').value}: {})};s.pending=body;s.busy=true;s.fresh=false;controls();try{const r=await api('jobs/'+encodeURIComponent(s.job.id)+'/run-actions','POST',body);if(epoch!==s.epoch)return;s.pending=null;s.logRequest=r.request_id;s.offset=0;s.cursor=0;$('run-note').textContent='Request saved: '+r.status+'. This is not native acknowledgment.';}catch(e){if(epoch!==s.epoch)return;if(['OBSERVATION_CHANGED_REFRESH_REQUIRED','ACTION_UNAVAILABLE','INVALID_REQUEST'].includes(e.message))s.pending=null;$('run-note').textContent='Action not confirmed: '+e.message+'. Use Reconcile saved action to retry the same request.';}finally{if(epoch===s.epoch){s.busy=false;controls();await refresh();}}});
  $('run-refresh').addEventListener('click',refresh);$('run-back').addEventListener('click',()=>{reset();$('jobs-panel').hidden=false;back();});$('run-log-more').addEventListener('click',logs);$('run-stream').addEventListener('change',()=>{s.offset=0;$('run-log').textContent='';logs();});
  window.addEventListener('offline',()=>{s.fresh=false;controls();if(s.job)$('run-note').textContent='Connection lost. Observations are stale; execution may still continue.';});window.addEventListener('online',refresh);
  setInterval(()=>{if(s.job && !document.hidden){refresh();if($('run-activity').open && $('run-follow').checked)logs();}},5000);
  function reset(){s.epoch++;s.job=null;s.view=null;s.busy=false;s.fresh=false;s.pending=null;s.logRequest=null;s.logBusy=false;s.offset=0;s.cursor=0;$('run-panel').hidden=true;for(const id of ['run-raw','run-log','run-events','run-request-detail','run-name','run-question','run-note'])$(id).textContent='';$('run-facts').replaceChildren();$('run-backup').replaceChildren();$('run-requests').replaceChildren();}
  return {reset,open(job){reset();s.job=job;$('jobs-panel').hidden=true;$('prepare-panel').hidden=true;$('job-detail').hidden=true;$('run-panel').hidden=false;$('run-name').textContent=job.name;$('run-state').textContent='Loading…';$('run-panel').focus();refresh();}};
}
