from __future__ import annotations

"""G5:R3 generic endpoint-typed recursive hidden-message law.

This is a non-promoting post-graduation structural stage.  R2 established that
no fixed finite local truncation depth is globally sufficient for the frozen
exact-child observer.  R3 asks the constructive next question: whether the
*complete* endpoint-typed rooted cavity message is generated by one fixed local
recursion on every finite hidden tree and whether exact hidden-canon equality is
stable under arbitrary finite continuations of the certified relation-valued
leaf-graft algebra.

Exact scientific equality is structural tuple equality.  Digests are audit
handles only.
"""

from collections import deque
from importlib.resources import files
from itertools import product
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence
import json

from .canon import canonical_sha256
from .adapters.g4_accepted import G4AcceptedAdapter, DecoratedG4Tree
from .typed_tree_messages import prepare_endpoint_decorated_tree
from .uplift_g3_r1 import _generate_tree_shapes


class G5R3Error(RuntimeError):
    pass


_SPEC = "G5_R3_GENERIC_ENDPOINT_TYPED_MESSAGE_CONGRUENCE_SPEC_V1.json"


def _resource(name: str) -> Path:
    return Path(str(files("infinity_grid").joinpath("resources/uplift").joinpath(name)))


def r3_spec() -> dict[str, Any]:
    obj = json.loads(_resource(_SPEC).read_text(encoding="utf-8"))
    if obj.get("schema_id") != "IG_G5_R3_GENERIC_ENDPOINT_TYPED_MESSAGE_CONGRUENCE_SPEC_V1":
        raise G5R3Error("bad G5:R3 spec schema")
    payload = {k: v for k, v in obj.items() if k != "science_sha256"}
    if canonical_sha256(payload) != obj.get("science_sha256"):
        raise G5R3Error("G5:R3 spec hash mismatch")
    return obj


def verify_authority(
    r2_primary: Mapping[str, Any],
    r2_verification: Mapping[str, Any],
    r2_closeout: Mapping[str, Any],
) -> dict[str, Any]:
    s = r3_spec(); a = s["authority"]; failures: list[str] = []
    if r2_primary.get("schema_id") != "IG_G5_R2_PREDICTIVE_HIDDEN_ACTION_READ_RESULT_V1" or r2_primary.get("status") != "PASS":
        failures.append("R2_PRIMARY_SCHEMA_OR_STATUS")
    if str(r2_primary.get("classification")) != str(a["required_r2_classification"]):
        failures.append("R2_CLASSIFICATION")
    if str(r2_primary.get("science_sha256")) != str(a["g5_r2_primary_science_sha256"]):
        failures.append("R2_PRIMARY_IDENTITY")
    if r2_primary.get("exact_reference_hidden_read") != a["required_r2_exact_reference_hidden_read"]:
        failures.append("R2_REFERENCE_READ")
    if r2_primary.get("g5_graduation_preserved") is not True or r2_primary.get("promotion") is not False:
        failures.append("R2_FIREWALL")
    if r2_primary.get("global_fixed_depth_lower_bound", {}).get("global_fixed_finite_local_depth_sufficient") is not False:
        failures.append("R2_FIXED_DEPTH_LOWER_BOUND")
    if r2_verification.get("status") != "PASS" or str(r2_verification.get("verification_sha256")) != str(a["g5_r2_independent_verification_sha256"]):
        failures.append("R2_VERIFICATION")
    if r2_closeout.get("schema_id") != "IG_G5_R2_CERTIFIED_CLOSEOUT_V1" or r2_closeout.get("status") != "CERTIFIED_PASS":
        failures.append("R2_CLOSEOUT_STATUS")
    if str(r2_closeout.get("closeout_sha256")) != str(a["g5_r2_closeout_sha256"]):
        failures.append("R2_CLOSEOUT_IDENTITY")
    out = {
        "schema_id": "IG_G5_R3_AUTHORITY_CHECK_V1",
        "status": "PASS" if not failures else "FAIL",
        "failures": failures,
        "r2_primary_science_sha256": r2_primary.get("science_sha256"),
        "r2_verification_sha256": r2_verification.get("verification_sha256"),
        "r2_closeout_sha256": r2_closeout.get("closeout_sha256"),
        "r2_exact_reference_hidden_read": r2_primary.get("exact_reference_hidden_read"),
        "public_descriptor": a["required_public_descriptor"],
        "g5_graduation_preserved": True,
        "promotion": False,
    }
    out["science_sha256"] = canonical_sha256(out)
    if failures:
        raise G5R3Error("R2 authority mismatch: " + ",".join(failures))
    return out


# ---------------------------------------------------------------------------
# Independent structural oracle used by the R3 support panel.  It deliberately
# does not call typed_tree_messages or the adapter's canon methods.
# ---------------------------------------------------------------------------

def _freeze(value: Any) -> tuple[Any, ...]:
    if value is None: return ("null",)
    if isinstance(value, bool): return ("bool", bool(value))
    if isinstance(value, int): return ("int", int(value))
    if isinstance(value, float): return ("float", value.hex())
    if isinstance(value, str): return ("str", value)
    if isinstance(value, bytes): return ("bytes", value.hex())
    if isinstance(value, Mapping):
        return ("map", tuple(sorted((_freeze(k), _freeze(v)) for k, v in value.items())))
    if isinstance(value, (list, tuple)):
        return ("seq", tuple(_freeze(x) for x in value))
    raise G5R3Error(f"independent oracle unsupported label type {type(value).__name__}")


def _independent_adjacency(
    n: int,
    edges: Sequence[Sequence[int]],
    vertex_keys: Sequence[Any],
    endpoint_ops: Sequence[Sequence[Any]],
) -> tuple[list[list[tuple[int, tuple[Any, ...]]]], tuple[tuple[Any, ...], ...]]:
    n = int(n)
    if n < 1 or len(vertex_keys) != n or len(edges) != n - 1 or len(endpoint_ops) != n - 1:
        raise G5R3Error("independent oracle arity/tree-size failure")
    adj: list[list[tuple[int, tuple[Any, ...]]]] = [[] for _ in range(n)]
    seen: set[tuple[int,int]] = set()
    for e, op in zip(edges, endpoint_ops):
        if len(e) != 2 or len(op) != 2: raise G5R3Error("independent oracle edge/operator arity")
        u,v = int(e[0]), int(e[1]); a,b = op[0], op[1]
        if not (0 <= u < n and 0 <= v < n) or u == v: raise G5R3Error("independent oracle bad edge")
        k=(min(u,v),max(u,v))
        if k in seen: raise G5R3Error("independent oracle duplicate edge")
        seen.add(k)
        adj[u].append((v, _freeze((a,b))))
        adj[v].append((u, _freeze((b,a))))
    q=deque([0]); reached={0}
    while q:
        v=q.popleft()
        for u,_ in adj[v]:
            if u not in reached: reached.add(u); q.append(u)
    if len(reached)!=n: raise G5R3Error("independent oracle disconnected")
    return adj, tuple(_freeze(x) for x in vertex_keys)


def independent_rooted_canon(n:int, edges, vertex_keys, endpoint_ops, root:int) -> tuple[Any, ...]:
    adj, vlabs = _independent_adjacency(n, edges, vertex_keys, endpoint_ops)
    root=int(root)
    def rec(v:int,parent:int) -> tuple[Any,...]:
        children=tuple(sorted((lab,rec(u,v)) for u,lab in adj[v] if u!=parent))
        return ("V",vlabs[v],children)
    return rec(root,-1)


def independent_unrooted_canon(n:int, edges, vertex_keys, endpoint_ops) -> tuple[Any, ...]:
    return min(independent_rooted_canon(n,edges,vertex_keys,endpoint_ops,r) for r in range(int(n)))


def _eccentricity(n:int, edges:Sequence[Sequence[int]], root:int) -> int:
    adj=[[] for _ in range(int(n))]
    for e in edges:
        u,v=map(int,e);adj[u].append(v);adj[v].append(u)
    dist=[-1]*int(n);dist[int(root)]=0;q=deque([int(root)])
    while q:
        v=q.popleft()
        for u in adj[v]:
            if dist[u]<0:dist[u]=dist[v]+1;q.append(u)
    if min(dist)<0: raise G5R3Error("eccentricity on disconnected tree")
    return max(dist)


def _relabel_tree(tree: DecoratedG4Tree, perm: Sequence[int]) -> DecoratedG4Tree:
    if len(perm)!=tree.n or sorted(map(int,perm))!=list(range(tree.n)):
        raise G5R3Error("bad relabel permutation")
    p=list(map(int,perm))
    colors=[None]*tree.n
    for old,c in enumerate(tree.H_classes): colors[p[old]]=c
    edges=[];ops=[]
    for (u,v),op in zip(tree.edges,tree.edge_operators):
        edges.append((p[u],p[v]));ops.append(tuple(op))
    return DecoratedG4Tree(tree.n,tuple(edges),tuple(colors),tuple(ops))


def _manual_graft_children(ad:G4AcceptedAdapter, tree:DecoratedG4Tree, *, new_H:str, op:Sequence[int]) -> list[DecoratedG4Tree]:
    op=tuple(map(int,op))
    if op not in set(ad.operator_basis()): raise G5R3Error("manual graft operator outside basis")
    local=[list(map(int,ad._rows[k]["caps7"])) for k in tree.H_classes]
    for (u,v),(a,b) in zip(tree.edges,tree.edge_operators): local[u][a]-=1;local[v][b]-=1
    new_caps=list(map(int,ad._rows[str(new_H)]["caps7"]))
    out=[]
    for root in range(tree.n):
        if local[root][op[0]]<=0 or new_caps[op[1]]<=0: continue
        out.append(DecoratedG4Tree(tree.n+1,tree.edges+((root,tree.n),),tree.H_classes+(str(new_H),),tree.edge_operators+(op,)))
    return out


def _relation_children(ad:G4AcceptedAdapter, tree:DecoratedG4Tree, *, new_H:str, op:Sequence[int]) -> dict[tuple[Any,...],DecoratedG4Tree]:
    out={}
    for root in range(tree.n):
        for child in ad.graft_relation(tree,root,new_H_class=str(new_H),operator=tuple(map(int,op))):
            out.setdefault(ad.unrooted_canon(child),child)
    return out


def _future_relation_set(ad:G4AcceptedAdapter, tree:DecoratedG4Tree, word:Sequence[Sequence[Any]]) -> tuple[tuple[Any,...], ...]:
    current={ad.unrooted_canon(tree):tree}
    for payload in word:
        new_H=str(payload[0]);op=tuple(map(int,payload[1]));nxt={}
        for t in current.values():
            for c,child in _relation_children(ad,t,new_H=new_H,op=op).items():nxt.setdefault(c,child)
        current=nxt
    return tuple(sorted(current.keys()))


def _manual_future_relation_set(ad:G4AcceptedAdapter, tree:DecoratedG4Tree, word:Sequence[Sequence[Any]]) -> tuple[tuple[Any,...], ...]:
    current={independent_unrooted_canon(tree.n,tree.edges,[ad._vertex_key(x) for x in tree.H_classes],tree.edge_operators):tree}
    for payload in word:
        new_H=str(payload[0]);op=tuple(map(int,payload[1]));nxt={}
        for t in current.values():
            for child in _manual_graft_children(ad,t,new_H=new_H,op=op):
                can=independent_unrooted_canon(child.n,child.edges,[ad._vertex_key(x) for x in child.H_classes],child.edge_operators)
                nxt.setdefault(can,child)
        current=nxt
    return tuple(sorted(current.keys()))


def theorem_certificate() -> dict[str, Any]:
    s=r3_spec()
    theorems=[
      {
        "theorem_id":"R3-T1-ROOTED-ENDPOINT-CAVITY-CANON-COMPLETENESS",
        "scope":"ALL_FINITE_VERTEX_H_LABELED_ENDPOINT_TYPED_EDGE_DECORATED_TREES",
        "statement":"The recursive rooted endpoint-typed cavity canon C(T,r) is a complete invariant of rooted endpoint-typed decorated-tree isomorphism.",
        "proof":"Structural induction on vertex count. Removing the root splits a finite tree into smaller rooted branches. Equality of the root H label and the multiset of local-to-remote endpoint-type/child-canon pairs gives a bijection of incident branches. By induction each matched child canon gives a rooted decoration-preserving isomorphism; these branch isomorphisms assemble at the root. The converse is direct from isomorphism invariance of the constructor.",
        "status":"PROVED_FROM_DEFINITIONS"
      },
      {
        "theorem_id":"R3-T2-UNROOTED-CANON-COMPLETENESS",
        "scope":"ALL_FINITE_VERTEX_H_LABELED_ENDPOINT_TYPED_EDGE_DECORATED_TREES",
        "statement":"U(T)=min_r C(T,r) is a complete invariant of unrooted endpoint-typed decorated-tree isomorphism.",
        "proof":"If U(T)=U(T'), choose roots attaining the common minimum. R3-T1 gives a rooted decorated isomorphism and therefore an unrooted one. Conversely an unrooted decorated isomorphism transports the multiset of rooted canons, so the minima agree.",
        "status":"PROVED_FROM_R3_T1"
      },
      {
        "theorem_id":"R3-T3-ECCENTRICITY-PROPAGATION-BOUND",
        "scope":"ALL_FINITE_ENDPOINT_TYPED_DECORATED_TREES",
        "statement":"The truncated nonbacktracking message at root r and depth ecc_T(r) equals the complete rooted canon C(T,r).",
        "proof":"Every vertex and decorated edge lies on the unique root path of length at most ecc_T(r). The nonbacktracking recursion crosses one new edge per round. At eccentricity depth every branch is complete, so truncated and full recursions coincide.",
        "status":"PROVED_FROM_DEFINITIONS"
      },
      {
        "theorem_id":"R3-T4-NO-FIXED-FINITE-LOCAL-DEPTH-BRIDGE",
        "scope":"R2_CERTIFIED_RESOURCE_REALIZABLE_C_ONLY_PATH_BROOM_SUBCARRIER",
        "statement":"No fixed finite truncation depth is globally sufficient for the frozen exact-child observer.",
        "proof":"Imported only as the exact certified R2 theorem under its recorded science identity; R3 does not enlarge or weaken that observer.",
        "status":"BOUND_TO_CERTIFIED_R2_AUTHORITY"
      },
      {
        "theorem_id":"R3-T5-EXPLICIT-OWNER-GRAFT-CONGRUENCE",
        "scope":"RESOURCE_LEGAL_G5_EXPLICIT_OWNER_GRAFTS",
        "statement":"Equal exact rooted canons at chosen owners, with equal fixed payload (new H class and directed operator), yield equal exact rooted child canons and equal public child reads whenever the graft is lawful.",
        "proof":"R3-T1 supplies a root-preserving endpoint-decoration-preserving parent isomorphism. Resource legality is an isomorphism-invariant function of H labels and incident endpoint types. Appending the same fixed decorated leaf at the corresponding roots extends the isomorphism to the children.",
        "status":"PROVED_FROM_R3_T1_AND_CERTIFIED_R1_GRAFT_RULE"
      },
      {
        "theorem_id":"R3-T6-RELATION-VALUED-GRAFT-CONGRUENCE",
        "scope":"RESOURCE_LEGAL_G5_OWNER_UNCONDITIONED_RELATION_VALUED_GRAFTS",
        "statement":"Equal exact unrooted hidden canons have identical deduplicated exact unrooted child-canon sets under the same fixed graft payload.",
        "proof":"R3-T2 gives a decorated-tree isomorphism. It bijects vertices and preserves local residual resources; therefore it bijects lawful owners. R3-T5 matches each corresponding explicit-owner child. Deduplication by exact isomorphism preserves equality of the resulting relation sets.",
        "status":"PROVED_FROM_R3_T2_AND_R3_T5"
      },
      {
        "theorem_id":"R3-T7-FINITE-FUTURE-CONGRUENCE",
        "scope":"EVERY_FINITE_WORD_OF_CERTIFIED_R1_LEAF_GRAFT_PAYLOADS_ON_RESOURCE_LEGAL_G5_TREES",
        "statement":"Equal exact unrooted hidden canons have identical deduplicated exact hidden outcome sets after every finite continuation word of relation-valued graft payloads.",
        "proof":"Induction on continuation length. Length zero is R3-T2. For the induction step, R3-T6 gives equal one-step child-canon sets; apply the induction hypothesis to each matched child canon and take the same union over relation-valued branches.",
        "status":"PROVED_FROM_R3_T6_BY_INDUCTION"
      }
    ]
    out={
      "schema_id":"IG_G5_R3_GENERIC_MESSAGE_THEOREM_CERTIFICATE_V1","status":"PASS",
      "operator":{
        "name":"NONBACKTRACKING_ENDPOINT_TYPED_DECORATED_CAVITY_MESSAGE_CANON",
        "directed_rule":s["theorem_scope"]["directed_message_rule"],
        "root_rule":s["theorem_scope"]["root_rule"],
        "unrooted_rule":s["theorem_scope"]["unrooted_rule"],
        "fixed_local_constructor_across_all_finite_sizes":True,
        "iteration_depth_may_grow_with_tree":True,
        "hash_required_for_exactness":False,
      },
      "theorems":theorems,
      "r2_fixed_depth_lower_bound_preserved":True,
      "finite_future_congruence_earned":True,
      "global_minimality_claim":False,
      "promotion":False,"physical_geometry_claim":False
    }
    out["science_sha256"]=canonical_sha256(out);return out


def exhaustive_support_panel() -> dict[str, Any]:
    s=r3_spec()["support_panel"];ad=G4AcceptedAdapter();shapes=_generate_tree_shapes(4)
    palette=[tuple(map(int,x)) for x in s["existing_edge_operator_palette"]]
    expected_shapes={1:1,2:1,3:1,4:2}
    rows=[];total_parents=0;rooted_cases=0;future_word_checks=0;failures=[]
    for n in range(1,5):
        if len(shapes[n])!=expected_shapes[n]: failures.append(f"SHAPE_COUNT_N{n}")
        nparents=0;nroots=0;nfuture=0
        for edges in shapes[n].values():
            for colors in product(tuple(s["vertex_H_palette"]),repeat=n):
                edge_products=[tuple()] if n==1 else product(palette,repeat=n-1)
                for ops in edge_products:
                    tree=DecoratedG4Tree(n,tuple(edges),tuple(colors),tuple(ops))
                    pub=ad.public_read(tree)
                    if not pub.get("legal"): failures.append(f"UNEXPECTED_ILLEGAL_PARENT_N{n}");continue
                    nparents+=1;total_parents+=1
                    keys=[ad._vertex_key(x) for x in tree.H_classes]
                    prep=prepare_endpoint_decorated_tree(tree.n,tree.edges,keys,tree.edge_operators)
                    impl_u=prep.unrooted_canon();ind_u=independent_unrooted_canon(tree.n,tree.edges,keys,tree.edge_operators)
                    if impl_u!=ind_u: failures.append(f"UNROOTED_ORACLE_N{n}")
                    for root in range(n):
                        nroots+=1;rooted_cases+=1
                        impl=prep.rooted_canon(root);ind=independent_rooted_canon(tree.n,tree.edges,keys,tree.edge_operators,root)
                        if impl!=ind: failures.append(f"ROOTED_ORACLE_N{n}")
                        ecc=_eccentricity(tree.n,tree.edges,root)
                        if prep.rooted_truncated(root,ecc)!=impl: failures.append(f"ECC_BOUND_N{n}")
                    perm=tuple(reversed(range(n)))
                    rel=_relabel_tree(tree,perm)
                    if ad.unrooted_canon(rel)!=ad.unrooted_canon(tree): failures.append(f"RELABEL_CANON_N{n}")
                    if ad.public_read(rel)!=pub: failures.append(f"RELABEL_PUBLIC_N{n}")
                    for word in s["payload_words"]:
                        a=_future_relation_set(ad,tree,word);b=_future_relation_set(ad,rel,word);m=_manual_future_relation_set(ad,tree,word)
                        nfuture+=1;future_word_checks+=1
                        if a!=b: failures.append(f"RELABEL_FUTURE_N{n}")
                        if a!=m: failures.append(f"INDEPENDENT_FUTURE_N{n}")
        rows.append({"n":n,"unlabelled_shape_count":len(shapes[n]),"decorated_parent_count":nparents,"rooted_canon_cases":nroots,"future_word_checks":nfuture})
    # Exact preregistered combinatorial counts for this palette/scope.
    expected_parents=2+12+72+864
    expected_roots=2+24+216+3456
    expected_future=expected_parents*len(s["payload_words"])
    if total_parents!=expected_parents: failures.append(f"PARENT_COUNT:{total_parents}")
    if rooted_cases!=expected_roots: failures.append(f"ROOT_COUNT:{rooted_cases}")
    if future_word_checks!=expected_future: failures.append(f"FUTURE_COUNT:{future_word_checks}")
    out={
      "schema_id":"IG_G5_R3_EXHAUSTIVE_SUPPORT_PANEL_V1","status":"PASS" if not failures else "FAIL",
      "scope":{"n_min":1,"n_max":4,"vertex_H_palette":s["vertex_H_palette"],"existing_edge_operator_palette":s["existing_edge_operator_palette"],"payload_words":s["payload_words"]},
      "rows":rows,"decorated_parent_count":total_parents,"rooted_canon_case_count":rooted_cases,"future_word_check_count":future_word_checks,
      "expected_parent_count":expected_parents,"expected_rooted_case_count":expected_roots,"expected_future_word_check_count":expected_future,
      "independent_structural_oracle_used":True,"relabelling_invariance_checked":True,"public_read_invariance_checked":True,
      "structural_equality_used":True,"digest_only_equality_used":False,"failures":failures[:50]
    }
    out["science_sha256"]=canonical_sha256(out)
    if failures: raise G5R3Error("support panel failed: "+",".join(failures[:10]))
    return out


def all_operator_sentinel() -> dict[str, Any]:
    ad=G4AcceptedAdapter();ops=list(ad.operator_basis());failures=[];rows=[]
    if len(ops)!=31: failures.append("OPERATOR_BASIS_SIZE")
    for op in ops:
        a,b=op
        t=DecoratedG4Tree(2,((0,1),),("C","D"),(op,))
        rev=DecoratedG4Tree(2,((1,0),),("C","D"),((b,a),))
        can=ad.unrooted_canon(t);can_rev=ad.unrooted_canon(rev)
        if can!=can_rev: failures.append(f"STORAGE_REVERSAL:{a}>{b}")
        asym=None
        if a!=b:
            swapped=DecoratedG4Tree(2,((0,1),),("C","D"),((b,a),))
            asym=ad.unrooted_canon(swapped)!=can
            if not asym: failures.append(f"ASYMMETRIC_COLLAPSE:{a}>{b}")
        # Relabel both endpoints and transport the edge storage without changing
        # endpoint positions inside the stored operator tuple.
        rel=_relabel_tree(t,(1,0))
        if ad.unrooted_canon(rel)!=can: failures.append(f"RELABEL_CANON:{a}>{b}")
        for root in (0,1):
            ch=ad.graft_relation(t,root,new_H_class="C",operator=(0,0))
            chr_=ad.graft_relation(rel,1-root,new_H_class="C",operator=(0,0))
            ca=tuple(sorted(ad.unrooted_canon(x) for x in ch));cb=tuple(sorted(ad.unrooted_canon(x) for x in chr_))
            if ca!=cb: failures.append(f"GRAFT_RELABEL:{a}>{b}:{root}")
        rows.append({"operator":[a,b],"storage_reversal_equal":can==can_rev,"asymmetric_endpoint_assignment_distinguished":asym,"relabel_graft_transport_pass":True})
    out={"schema_id":"IG_G5_R3_ALL_31_OPERATOR_MESSAGE_SENTINEL_V1","status":"PASS" if not failures else "FAIL","operator_count":len(ops),"rows":rows,"failures":failures,"endpoint_direction_semantics_preserved":not failures}
    out["science_sha256"]=canonical_sha256(out)
    if failures: raise G5R3Error("all-operator sentinel failed: "+",".join(failures[:8]))
    return out


def r2_bridge(r2_primary: Mapping[str,Any]) -> dict[str,Any]:
    lower=r2_primary.get("global_fixed_depth_lower_bound",{})
    pA=r2_primary.get("fresh_n8_color_panel",{});pB=r2_primary.get("endpoint_typed_n5_panel",{})
    failures=[]
    if lower.get("global_fixed_finite_local_depth_sufficient") is not False: failures.append("LOWER_BOUND")
    if int(pA.get("first_predictive_depth",-1))!=6 or pA.get("nontrivial_reduction_candidate_survived") is not False: failures.append("N8_BRIDGE")
    if int(pB.get("first_predictive_depth",-1))!=4 or pB.get("nontrivial_reduction_candidate_survived") is not False: failures.append("N5_BRIDGE")
    if pA.get("structural_equality_used") is not True or pB.get("structural_equality_used") is not True: failures.append("EXACTNESS_BRIDGE")
    out={"schema_id":"IG_G5_R3_R2_RESULT_BRIDGE_V1","status":"PASS" if not failures else "FAIL","r2_primary_science_sha256":r2_primary.get("science_sha256"),"fixed_depth_global_sufficiency":False,"fresh_n8_first_predictive_depth":pA.get("first_predictive_depth"),"endpoint_n5_first_predictive_depth":pB.get("first_predictive_depth"),"no_nontrivial_local_compression_on_both_registered_panels":not failures,"failures":failures}
    out["science_sha256"]=canonical_sha256(out)
    if failures: raise G5R3Error("R2 bridge failed: "+",".join(failures))
    return out


def run_g5_r3_generic_message_congruence(*, engine:Any, r2_primary:Mapping[str,Any], r2_verification:Mapping[str,Any], r2_closeout:Mapping[str,Any]) -> dict[str,Any]:
    s=r3_spec();auth=verify_authority(r2_primary,r2_verification,r2_closeout);bridge=r2_bridge(r2_primary)
    theorem=theorem_certificate();panel=exhaustive_support_panel();sentinel=all_operator_sentinel()
    classification="G5_R3_GENERIC_ENDPOINT_TYPED_CAVITY_CANON_AND_FINITE_GRAFT_FUTURE_CONGRUENCE_EARNED_R2_FIXED_DEPTH_LOWER_BOUND_PRESERVED_NO_PROMOTION_R4_DESIGN_AUTHORIZED"
    out={
      "schema_id":"IG_G5_R3_GENERIC_ENDPOINT_TYPED_MESSAGE_CONGRUENCE_RESULT_V1","status":"PASS","stage_ref":"G5:R3","classification":classification,
      "promotion":False,"g5_graduation_preserved":True,"g6_started":False,"authority":auth,"r2_bridge":bridge,"generic_message_theorem":theorem,"exhaustive_support_panel":panel,"all_operator_sentinel":sentinel,
      "exact_reference_hidden_read":"ENDPOINT_TYPED_DECORATED_TREE_CANON","generic_recursive_hidden_message":"NONBACKTRACKING_ENDPOINT_TYPED_DECORATED_CAVITY_MESSAGE_CANON","finite_future_congruence_earned":True,
      "compact_hidden_read_promoted":False,"topology_promoted":False,"public_descriptor_changed":False,"next_authorized_stage":"G5:R4_DESIGN_AFTER_HUMAN_REVIEW","cost_control":s["cost_control"],"nonclaims":s["nonclaims"]
    }
    out["science_sha256"]=canonical_sha256(out);return out


def stable_payload(result:Mapping[str,Any])->dict[str,Any]:
    return {k:v for k,v in result.items() if k not in {"source_sha256","source_version","registry_sha256","execution_metadata"}}


def compare_cold_replay(primary:Mapping[str,Any], cold:Mapping[str,Any])->dict[str,Any]:
    p=canonical_sha256(stable_payload(primary));c=canonical_sha256(stable_payload(cold));fail=[]
    if primary.get("science_sha256")!=cold.get("science_sha256"):fail.append("SCIENCE_SHA")
    if primary.get("classification")!=cold.get("classification"):fail.append("CLASSIFICATION")
    if p!=c:fail.append("STABLE_PAYLOAD")
    out={"schema_id":"IG_G5_R3_COLD_REPLAY_COMPARISON_V1","status":"PASS" if not fail else "FAIL","certification":"CERTIFIED_PASS" if not fail else "CERTIFICATION_FAILED","failures":fail,"primary_science_sha256":primary.get("science_sha256"),"cold_science_sha256":cold.get("science_sha256"),"stable_scientific_payload_exact_equal":p==c,"stable_scientific_payload_sha256":p}
    out["comparison_sha256"]=canonical_sha256(out);return out


def certified_closeout(primary:Mapping[str,Any],cold:Mapping[str,Any],comparison:Mapping[str,Any],independent:Mapping[str,Any])->dict[str,Any]:
    ok=primary.get("status")=="PASS" and cold.get("status")=="PASS" and comparison.get("certification")=="CERTIFIED_PASS" and independent.get("status")=="PASS"
    out={"schema_id":"IG_G5_R3_CERTIFIED_CLOSEOUT_V1","status":"CERTIFIED_PASS" if ok else "CERTIFICATION_FAILED","experiment_id":"G5:R3.GENERIC_ENDPOINT_TYPED_MESSAGE_CONGRUENCE","classification":primary.get("classification") if ok else "G5_R3_REVIEW_REQUIRED_NO_PROMOTION","science_sha256":primary.get("science_sha256"),"stable_science_payload_sha256":comparison.get("stable_scientific_payload_sha256"),"comparison_sha256":comparison.get("comparison_sha256"),"independent_verification_sha256":independent.get("verification_sha256"),"source_sha256":primary.get("source_sha256"),"registry_sha256":primary.get("registry_sha256"),"promotion":False,"g5_graduation_preserved":True,"finite_future_congruence_earned":bool(primary.get("finite_future_congruence_earned")) if ok else False,"compact_hidden_read_promoted":False,"topology_promoted":False,"g6_started":False,"next_authorized_stage":"G5:R4_DESIGN_AFTER_HUMAN_REVIEW" if ok else None,"failures":comparison.get("failures",[])}
    out["closeout_sha256"]=canonical_sha256(out);return out
