from __future__ import annotations

"""Execution provenance primitives for the 0.30.88 L1 DEVELOPMENT checkpoint.

This module is not a Python sandbox. Official execution is deliberately OFF until
an isolated controller service is installed. Test keys only sign ENGINEERING_ONLY
receipts. A production verifier must get its trusted keys from protected policy,
never from a receipt, result, environment variable or downloaded bundle.
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Mapping
import base64
import hashlib
import json
import math
import uuid

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey, Ed25519PublicKey
from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat

RECEIPT_SCHEMA = "IG_DECODER_EXECUTION_RECEIPT_V1"
ENGINEERING_ROLE = "ENGINEERING_ONLY"
OFFICIAL_ROLE = "OFFICIAL_CONTROLLER"
_RECEIPT_DOMAIN = b"IG-DECODER-EXECUTION-RECEIPT-V1\x00"
_BINDING_FIELDS = frozenset({
    "chain_id", "registration_sha256", "stage_id", "handler_key", "handler_ref",
    "question_sha256", "source_sha256", "handler_source_sha256", "parameters_sha256",
    "authority_sha256", "dependencies_sha256", "evidence_store_id", "run_id",
})
_HASH_FIELDS = frozenset(k for k in _BINDING_FIELDS if k.endswith("sha256") or k == "evidence_store_id")
_TELEMETRY_NAMES = frozenset({
    "wall_seconds", "duration_seconds", "elapsed_seconds", "cpu_seconds", "pid",
    "started_utc", "finished_utc", "committed_utc", "updated_utc", "run_id",
    "source_path", "output_path", "workspace_path", "runtime_root", "telemetry",
})


class ExecutionAuthorityError(RuntimeError):
    """Fail-closed admission/receipt error; never a scientific outcome."""
    def __init__(self, code: str, detail: str = "") -> None:
        self.code = code
        super().__init__(f"{code}: {detail}" if detail else code)


def _json_value(value: Any, path: str = "$", *, science: bool = False) -> None:
    if value is None or type(value) in (str, bool, int):
        return
    if type(value) is float:
        if not math.isfinite(value):
            raise ExecutionAuthorityError("NONFINITE_JSON", path)
        return
    if type(value) is list:
        for i, child in enumerate(value):
            _json_value(child, f"{path}/{i}", science=science)
        return
    if type(value) is dict:
        for key, child in value.items():
            if type(key) is not str:
                raise ExecutionAuthorityError("NONSTRING_JSON_KEY", path)
            if science and (key in _TELEMETRY_NAMES or key.endswith("_wall_seconds") or key.endswith("_cpu_seconds")):
                raise ExecutionAuthorityError("TELEMETRY_IN_SCIENCE_PAYLOAD", f"{path}/{key}")
            _json_value(child, f"{path}/{key}", science=science)
        return
    raise ExecutionAuthorityError("NON_JSON_PAYLOAD", f"{path}: {type(value).__name__}")


def canonical_bytes(value: Any) -> bytes:
    _json_value(value)
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"), allow_nan=False).encode("utf-8")


def digest(value: Any) -> str:
    return hashlib.sha256(canonical_bytes(value)).hexdigest()


def science_digest(result: dict[str, Any]) -> str:
    """Explicit result-only digest; no implicit field deletion or telemetry mixing."""
    _json_value(result, science=True)
    return digest({"schema_id": "IG_DECODER_SCIENCE_PAYLOAD_V1", "result": result})


def _sha(value: Any, label: str) -> None:
    if type(value) is not str or len(value) != 64 or any(c not in "0123456789abcdef" for c in value):
        raise ExecutionAuthorityError("BAD_SHA256", label)


def validate_bindings(bindings: Mapping[str, Any]) -> dict[str, str]:
    obj = dict(bindings)
    if set(obj) != _BINDING_FIELDS:
        raise ExecutionAuthorityError("RECEIPT_BINDING_FIELDS")
    for key, value in obj.items():
        if type(value) is not str or not value or len(value) > 4096:
            raise ExecutionAuthorityError("BAD_BINDING", key)
        if key in _HASH_FIELDS:
            _sha(value, key)
    if len(obj["run_id"]) != 32 or any(c not in "0123456789abcdef" for c in obj["run_id"]):
        raise ExecutionAuthorityError("BAD_RUN_ID")
    return obj


def source_tree_digest(package_dir: Path) -> str:
    """Hash executable sources/resources without machine paths or generated bytecode."""
    root = package_dir.resolve(strict=True)
    files = []
    for path in sorted(root.rglob("*")):
        if "__pycache__" in path.parts or path.suffix in {".pyc", ".pyo"}:
            continue
        if path.is_symlink():
            raise ExecutionAuthorityError("SYMLINK_IN_APPROVED_SOURCE", str(path))
        if path.is_file():
            files.append([path.relative_to(root).as_posix(), hashlib.sha256(path.read_bytes()).hexdigest()])
    return digest({"schema_id": "IG_DECODER_EXECUTABLE_SOURCE_TREE_V1", "files": files})


def verify_execution_receipt(
    receipt: Mapping[str, Any], *, expected_bindings: Mapping[str, Any],
    result: dict[str, Any], trusted_public_keys: Mapping[str, bytes],
    required_role: str = OFFICIAL_ROLE,
) -> dict[str, Any]:
    """Verify exact, caller-policy-pinned provenance. No trust-on-first-use."""
    if not isinstance(receipt, Mapping) or set(receipt) != {"schema_id", "algorithm", "role", "key_id", "payload", "signature"}:
        raise ExecutionAuthorityError("MISSING_OR_MALFORMED_EXECUTION_RECEIPT")
    obj = dict(receipt)
    if obj["schema_id"] != RECEIPT_SCHEMA or obj["algorithm"] != "Ed25519":
        raise ExecutionAuthorityError("RECEIPT_SCHEMA_OR_ALGORITHM")
    if required_role not in {OFFICIAL_ROLE, ENGINEERING_ROLE} or obj["role"] != required_role:
        raise ExecutionAuthorityError("RECEIPT_ROLE_NOT_AUTHORIZED")
    key_id = obj["key_id"]
    _sha(key_id, "key_id")
    key = trusted_public_keys.get(key_id)
    if not isinstance(key, bytes) or len(key) != 32 or hashlib.sha256(key).hexdigest() != key_id:
        raise ExecutionAuthorityError("UNTRUSTED_RECEIPT_KEY")
    expected = validate_bindings(expected_bindings)
    payload = obj["payload"]
    if type(payload) is not dict or set(payload) != {"bindings", "result_sha256", "science_sha256"}:
        raise ExecutionAuthorityError("RECEIPT_PAYLOAD_FIELDS")
    if validate_bindings(payload["bindings"]) != expected:
        raise ExecutionAuthorityError("EXECUTION_BINDING_MISMATCH")
    if payload["result_sha256"] != digest(result) or payload["science_sha256"] != science_digest(result):
        raise ExecutionAuthorityError("SIGNED_RESULT_MISMATCH")
    signature = obj["signature"]
    if type(signature) is not str or len(signature) != 88:
        raise ExecutionAuthorityError("INVALID_EXECUTION_SIGNATURE")
    try:
        raw = base64.b64decode(signature, validate=True)
        if len(raw) != 64:
            raise ValueError("signature length")
        signed = {k: v for k, v in obj.items() if k != "signature"}
        Ed25519PublicKey.from_public_bytes(key).verify(raw, _RECEIPT_DOMAIN + canonical_bytes(signed))
    except (InvalidSignature, ValueError, TypeError) as exc:
        raise ExecutionAuthorityError("INVALID_EXECUTION_SIGNATURE") from exc
    return {"status": "VERIFIED", "role": required_role, "science_sha256": payload["science_sha256"]}


# Process-local tickets prevent accidental API misuse. They are NOT a security
# boundary against arbitrary Python/root access. Official authority is not minted.
_PERMIT_CONSTRUCTOR = object()


class RuntimePermit:
    __slots__ = ("_bindings", "_active", "_evaluator_refs")
    def __init__(self, bindings: Mapping[str, Any], *, _constructor: object = None,
                 _evaluator_refs: tuple[str, ...] | None = None) -> None:
        if _constructor is not _PERMIT_CONSTRUCTOR:
            raise ExecutionAuthorityError("CONTROLLER_PERMIT_REQUIRED")
        self._bindings = validate_bindings(bindings)
        self._active = True
        self._evaluator_refs = _evaluator_refs

    def require(self, *, chain_dir: Path, chain_id: str, stage_id: str, question_sha256: str) -> None:
        if not self._active:
            raise ExecutionAuthorityError("EXECUTION_PERMIT_REVOKED")
        expected_store = digest({"chain_dir": str(chain_dir.resolve(strict=True))})
        for key, value in {"chain_id": chain_id, "stage_id": stage_id,
                           "question_sha256": question_sha256, "evidence_store_id": expected_store}.items():
            if self._bindings[key] != value:
                raise ExecutionAuthorityError("EXECUTION_PERMIT_BINDING_MISMATCH", key)

    def require_evaluator(self, ref: str) -> None:
        if not self._active:
            raise ExecutionAuthorityError("EXECUTION_PERMIT_REVOKED")
        if self._evaluator_refs is not None and ref not in self._evaluator_refs:
            raise ExecutionAuthorityError("SERVICE_EVALUATOR_NOT_ADMITTED")

    def revoke(self) -> None:
        self._active = False


def issue_controller_event_runtime_permit(
    *, chain_dir: Path, chain_id: str, stage_id: str, question_sha256: str,
    registration_sha256: str, source_sha256: str, handler_key: str, handler_ref: str,
    handler_source_sha256: str, parameters_sha256: str, authority_sha256: str,
    dependencies_sha256: str, run_id: str, evaluator_refs: tuple[str, ...],
) -> RuntimePermit:
    """Mint a stage-runtime permit only inside the live controller-root event.

    This is not a public execution surface.  Direct callers and workers fail at
    the C2/C5 origin guard before a permit exists.  The evaluator set is fixed by
    the accepted controller operation, not supplied by passive request data.
    """
    from .v05_origin_guard import CONTROLLER_ROOT_ROLE, current_execution_context_snapshot, require_controller_execution_origin
    require_controller_execution_origin("issue_controller_event_runtime_permit")
    from .v05_origin_guard import require_registered_output, require_native_caller, _live_context
    require_native_caller('infinity_grid.v05_controller_event_loop', {'_dispatch_workspace_job'}, 'runtime-permit')
    require_registered_output(chain_dir, 'runtime-permit')
    binding = _live_context().binding
    if registration_sha256 != binding['registration_sha256'] or source_sha256 != binding['source_sha256'] or chain_id != binding['job_id']:
        raise ExecutionAuthorityError('ATTEMPT_BINDING_MISMATCH', 'runtime-permit')
    ctx=current_execution_context_snapshot()
    if ctx is None or ctx.get("role") != CONTROLLER_ROOT_ROLE:
        raise ExecutionAuthorityError("CONTROLLER_ROOT_CONTEXT_REQUIRED")
    cdir=Path(chain_dir).resolve(strict=True)
    bindings={
        "chain_id":str(chain_id), "registration_sha256":str(registration_sha256),
        "stage_id":str(stage_id), "handler_key":str(handler_key), "handler_ref":str(handler_ref),
        "question_sha256":str(question_sha256), "source_sha256":str(source_sha256),
        "handler_source_sha256":str(handler_source_sha256), "parameters_sha256":str(parameters_sha256),
        "authority_sha256":str(authority_sha256), "dependencies_sha256":str(dependencies_sha256),
        "evidence_store_id":digest({"chain_dir":str(cdir)}), "run_id":str(run_id),
    }
    return RuntimePermit(bindings, _constructor=_PERMIT_CONSTRUCTOR, _evaluator_refs=tuple(evaluator_refs))


def require_runtime_permit(permit: Any, **bindings: Any) -> None:
    if type(permit) is not RuntimePermit:
        raise ExecutionAuthorityError("CONTROLLER_PERMIT_REQUIRED")
    permit.require(**bindings)


@dataclass
class EngineeringAuthority:
    """Explicit NONAUTHORITATIVE controller fixture session. Never signs OFFICIAL."""
    enabled: bool = False
    _key: Any = field(init=False, repr=False, default=None)
    _public: bytes = field(init=False, repr=False, default=b"")

    def __post_init__(self) -> None:
        if self.enabled:
            self._key = Ed25519PrivateKey.generate()
            self._public = self._key.public_key().public_bytes(Encoding.Raw, PublicFormat.Raw)

    def require_run(self, registration: Mapping[str, Any]) -> None:
        if not self.enabled:
            raise ExecutionAuthorityError("OFFICIAL_AUTHORITY_NOT_CONFIGURED", "protected controller/signer deployment required; no local fallback")
        if (registration.get("subject") or {}).get("hierarchy") != "ENGINEERING":
            raise ExecutionAuthorityError("ENGINEERING_MODE_CANNOT_RUN_SCIENCE")
        if (registration.get("subject") or {}).get("level") != 0:
            raise ExecutionAuthorityError("ENGINEERING_LEVEL_MUST_BE_ZERO")
        for st in registration.get("stages", []):
            if not str(st.get("stage_id", "")).startswith("ENG:"):
                raise ExecutionAuthorityError("ENGINEERING_STAGE_PREFIX_REQUIRED")
            if st.get("series") == "R" or st.get("promotion_effect") != "NONE" or st.get("stage_kind") not in {"DECODER_STAGE", "HUMAN_REVIEW"}:
                raise ExecutionAuthorityError("ENGINEERING_STAGE_NOT_ADMITTED", str(st.get("stage_id")))

    def begin(self, bindings: Mapping[str, Any]) -> RuntimePermit:
        if not self.enabled:
            raise ExecutionAuthorityError("OFFICIAL_AUTHORITY_NOT_CONFIGURED")
        return RuntimePermit(bindings, _constructor=_PERMIT_CONSTRUCTOR)

    @property
    def public_keys(self) -> dict[str, bytes]:
        if not self.enabled:
            return {}
        return {hashlib.sha256(self._public).hexdigest(): self._public}

    def receipt(self, bindings: Mapping[str, Any], result: dict[str, Any]) -> dict[str, Any]:
        if not self.enabled or self._key is None:
            raise ExecutionAuthorityError("OFFICIAL_AUTHORITY_NOT_CONFIGURED")
        body = {"schema_id": RECEIPT_SCHEMA, "algorithm": "Ed25519", "role": ENGINEERING_ROLE,
                "key_id": hashlib.sha256(self._public).hexdigest(),
                "payload": {"bindings": validate_bindings(bindings), "result_sha256": digest(result), "science_sha256": science_digest(result)}}
        return dict(body, signature=base64.b64encode(self._key.sign(_RECEIPT_DOMAIN + canonical_bytes(body))).decode("ascii"))


def new_run_id() -> str:
    return uuid.uuid4().hex


def main() -> int:
    """Read-only diagnostic command. It cannot launch or certify a stage."""
    import argparse
    from . import __version__
    parser = argparse.ArgumentParser(prog="ig-execution-status")
    parser.add_argument("command", choices=["status"])
    parser.parse_args()
    print(json.dumps({
        "version": __version__,
        "checkpoint": "L2_REGISTERED_SERVICE_CONNECTION_DEVELOPMENT",
        "official_execution": "PAUSED_PENDING_SERVICE_ACCEPTANCE",
        "reason": "OFFICIAL_AUTHORITY_NOT_CONFIGURED",
        "production_key_created": False,
        "production_privilege_boundary_verified": False,
        "engineering_receipts_are_authoritative": False,
        "release_accepted": False,
    }, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
