from pathlib import Path
import json,hashlib,zipfile,shutil,datetime
B=Path('o6_export0165');load=lambda n:json.load(open(B/n));n=load('NATIVE_RESULT.json');c=load('COLD_REUSE_RESULT.json');assert n['status']=='COMPLETED' and n['evidence_status']=='VERIFIED' and n['result']['outcome']=='PASS' and c['status']=='PASS' and c['pending_bytes']==0 and load('CHECKPOINT_ACK.json')['outbox']['pending_bytes']==0
sha=lambda b:hashlib.sha256(b).hexdigest();report='''INFINITY GRID REGISTERED SAVED O6 EXPORT/READER GATE0165 — 2026-10-06

PASS:COMPLETED/VERIFIED. Saved132 selected nonseed O6 carriers and2 external rank0 seeds across HET4(m6=0..5),HOM6(m6=0..6). All134 occurrence routes,682 nested O5 owner routes and172 nontrivial component routes verified. Typed E6 edge multiset432;133 pool/pin prototype bindings resolve ordered resource coordinates, original typed E5 component incidence, nested typed E4/E3 incidence and full admitted O5 source roots. Original selected-state/lane/prototype metadata, edge-only digest and full literal payload hashes preserved losslessly. State digest preserves prefix IG-E6-STATE-v1| followed by sorted twelve unsigned32-bit big-endian edge integers. HOM6 runtime pin alias is bound to the canonical pool ID. All132 O5 pool classes and169 component occurrences are rechecked, including the six-prototype selector. Lane/rank qualifies original edge-only digest, which alone omits owner identity; no global isomorphism-label claim.

Typed E6 compatibility/capacity, saved rank/digest and component accounting pass. Missing/excluded lane/rank/digest, invalid owner indices, unavailable derivation ancestry, root/nested/component copy isolation and closed-reader checks pass. Capture and terminal checkpoint saved with exact raw readbacks. Cold restore/exact completion reuse PASS;pending bytes0;generation calls0. Historical generators and graduation audits not rerun. Original O6 module is retained as source evidence; reader uses AST-identical pure helper extraction, with function closure and original/pure hashes verified.

Scope:Saved selected states; not full candidate census or complete parent/action occurrence lineage. Nested O5/O4/O3 still uses external anonymous(p,u2) Q bank;76 microscopic O2 panels and bank selection provenance remain unresolved. Full L0-G8 completion remains false.
MASTER:MASTER_DATA_V1_0146/146 scientific slices unchanged; no O6 scoped admission yet.
NEXT:Saved O6 scoped admission and registered catalog/unified reader integration, preserving all146 predecessor slices and routes. Do not regenerate completed constructions.
''';(B/'REPORT.txt').write_text(report);s=json.load(open('CURRENT_STATUS.json'));s.update(status_as_of_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),next_scope='SAVED_O6_TYPED_INCIDENCE_SCOPED_ADMISSION_AND_CATALOG_INTEGRATION',next_scope_status='REGISTERED_EXPORT_READER_VERIFIED_PRESERVED_COLD_REUSED',o6_export_result='o6_export0165/NATIVE_RESULT.json',code_mirror=load('CODE_MIRROR.json'));Path('CURRENT_STATUS.json').write_text(json.dumps(s,indent=2));D=Path('handoff0165_o6_export');D.mkdir(exist_ok=True);dest=D/B;dest.mkdir(exist_ok=True)
for p in B.iterdir():
 if p.is_file() and p.suffix in ['.json','.py','.txt'] and not p.name.startswith('TO_SAVE'):shutil.copy2(p,dest/p.name)
shutil.copytree(B/'project',dest/'project',ignore=shutil.ignore_patterns('__pycache__'),dirs_exist_ok=True)
for name in ['SCIENTIFIC_EXPORT.zip','FINAL_CHECKPOINT_SLIM.zip']:shutil.copy2(B/name,dest/name)
(D/'o3_export0156').mkdir(exist_ok=True);shutil.copy2('o3_export0156/SCIENTIFIC_EXPORT.zip',D/'o3_export0156/SCIENTIFIC_EXPORT.zip')
(D/'o4_export0159').mkdir(exist_ok=True);shutil.copy2('o4_export0159/SCIENTIFIC_EXPORT.zip',D/'o4_export0159/SCIENTIFIC_EXPORT.zip')
(D/'o5_export0162').mkdir(exist_ok=True);shutil.copy2('o5_export0162/SCIENTIFIC_EXPORT.zip',D/'o5_export0162/SCIENTIFIC_EXPORT.zip')
for name,hashes in [('READBACKS.json',{r['sha256'] for r in load('PENDING.json')['pending_objects']}),('CHECKPOINT_READBACKS.json',{r['sha256'] for r in load('EXPORT.json')['dependencies']}|{load('EXPORT.json')['sha256']})]:
 m=load(name);(dest/name).write_text(json.dumps({h:m[h] for h in sorted(hashes)},indent=2))
refs={'master0146_restore':{'name':'IG_MASTER_DATA_V1_0146_O5_HANDOFF_2026-10-06.zip','sha256':'b402b8b2ed0f665cddd6996579ac560e86f5175d91b1b22620bbea62608b7a80','drive_file_id':'1nYMBOKyUapLp9aHAHMXMUXIQKTbOWgBw'},'readiness_restore':{'name':'IG_O6_SOURCE_BOUND_READINESS_HANDOFF_2026-10-06.zip','sha256':'d280358f81b56f93d43ef821b0edaeaada86be5885b1aa697c9f78c411359528','drive_file_id':'1-ZJOS5OpcuYv9sAoXrdNa5ra-NS2DwLM'},'native_restore':'EXPORT.json and CHECKPOINT_READBACKS.json pin exact saved dependency IDs/hashes. Rebind local paths only, restore checkpoint in pinned runtime then reuse completion;do not regenerate.'};(D/'RECOVERY_DEPENDENCIES.json').write_text(json.dumps(refs,indent=2));(D/'READ_FIRST.txt').write_text(report);(D/'STATUS.json').write_text(json.dumps(s,indent=2));(D/'CONTINUATION_CURSOR.json').write_text(json.dumps({'master_release':'MASTER_DATA_V1_0146','scientific_slices':146,'completed_gate':'0165_SAVED_O6_EXPORT_READER','next_scope':s['next_scope'],'scientific_admission_issued':False,'capture_id':load('POINTER.json')['capture_id'],'completion_sha256':n['completion_sha256'],'result_sha256':n['result_sha256'],'pending_bytes':0,'generation_calls':0},indent=2));(D/'TEMPLATE_COMPLIANCE.json').write_text(json.dumps({'read_first':True,'status':True,'cursor':True,'scientific_bytes_and_code':True,'hash_manifest':True,'native_checkpoint_and_dependency_receipts':True,'lower_O5_incidence_bindings':True,'scope_limits_explicit':True,'completed_constructions_regenerated':False},indent=2));(D/'MANIFEST.json').unlink(missing_ok=True);m={str(p.relative_to(D)):{'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size} for p in D.rglob('*') if p.is_file()};(D/'MANIFEST.json').write_text(json.dumps(m,indent=2));p=Path('IG_O6_GATE_0165_VERIFIED_HANDOFF_2026-10-06.zip')
with zipfile.ZipFile(p,'w',zipfile.ZIP_DEFLATED) as z:
 for name in [*m,'MANIFEST.json']:z.write(D/name,name)
with zipfile.ZipFile(p) as z:
 for name,x in m.items():assert sha(z.read(name))==x['sha256']
Path('CURRENT_START.txt').write_text(str(D/'READ_FIRST.txt')+'\n');Path('IG_O6_GATE_0165_START_2026-10-06.txt').write_text(report+'\nBundle:'+p.name+'\nBundle SHA256:'+sha(p.read_bytes())+'\n');meta={'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size,'manifest_files':len(m)};(B/'DELIVERY_BINDINGS.json').write_text(json.dumps(meta,indent=2));print(meta)
