from pathlib import Path
import json,hashlib,zipfile,shutil,datetime
B=Path('o4_export0159');load=lambda n:json.load(open(B/n));n=load('NATIVE_RESULT.json');c=load('COLD_REUSE_RESULT.json');assert n['status']=='COMPLETED' and n['evidence_status']=='VERIFIED' and n['result']['outcome']=='PASS' and c['status']=='PASS' and c['pending_bytes']==0 and load('CHECKPOINT_ACK.json')['outbox']['pending_bytes']==0
sha=lambda b:hashlib.sha256(b).hexdigest();report='''INFINITY GRID REGISTERED SAVED O4 EXPORT/READER GATE0159 — 2026-10-06

PASS:COMPLETED/VERIFIED. Saved352 selected nonseed O4 carriers and2 external rank0 seeds across HET4(m4=0..5),HOM6(m4=0..6). All354 occurrence routes,1802 nested O3 owner routes and442 nontrivial component routes verified. Typed E4 edge multiset1152;seven prototype bindings resolve ordered resource coordinates, original typed E3 component incidence and full admitted O3 source roots. Original selected-state/lane/prototype metadata, edge-only digest and full literal payload hashes preserved losslessly. Lane/rank qualifies original edge-only digest, which alone omits owner identity; no global isomorphism-label claim.

Typed E4 compatibility/capacity, saved rank/digest and component accounting pass. Missing/excluded lane/rank/digest, invalid owner indices, unavailable derivation ancestry, root/nested/component copy isolation and closed-reader checks pass. Capture and terminal checkpoint saved with exact raw readbacks. Cold restore/exact completion reuse PASS;pending bytes0;generation calls0. Historical generators and graduation audits not rerun.

Scope:Saved selected states; not full candidate census or complete parent/action occurrence lineage. Nested O3 still uses external anonymous(p,u2) Q bank;76 microscopic O2 panels and bank selection provenance remain unresolved. Full L0-G8 completion remains false.
MASTER:MASTER_DATA_V1_0144/144 scientific slices unchanged; no O4 scoped admission yet.
NEXT:Saved O4 scoped admission and registered catalog/unified reader integration, preserving all144 predecessor slices and routes. Do not regenerate completed constructions.
''';(B/'REPORT.txt').write_text(report);s=json.load(open('CURRENT_STATUS.json'));s.update(status_as_of_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),next_scope='SAVED_O4_TYPED_INCIDENCE_SCOPED_ADMISSION_AND_CATALOG_INTEGRATION',next_scope_status='REGISTERED_EXPORT_READER_VERIFIED_PRESERVED_COLD_REUSED',o4_export_result='o4_export0159/NATIVE_RESULT.json',code_mirror=load('CODE_MIRROR.json'));Path('CURRENT_STATUS.json').write_text(json.dumps(s,indent=2));D=Path('handoff0159_o4_export');D.mkdir(exist_ok=True);dest=D/B;dest.mkdir(exist_ok=True)
for p in B.iterdir():
 if p.is_file() and p.suffix in ['.json','.py','.txt'] and not p.name.startswith('TO_SAVE'):shutil.copy2(p,dest/p.name)
shutil.copytree(B/'project',dest/'project',ignore=shutil.ignore_patterns('__pycache__'),dirs_exist_ok=True)
for name in ['SCIENTIFIC_EXPORT.zip','FINAL_CHECKPOINT_SLIM.zip']:shutil.copy2(B/name,dest/name)
(D/'o3_export0156').mkdir(exist_ok=True);shutil.copy2('o3_export0156/SCIENTIFIC_EXPORT.zip',D/'o3_export0156/SCIENTIFIC_EXPORT.zip')
for name,hashes in [('READBACKS.json',{r['sha256'] for r in load('PENDING.json')['pending_objects']}),('CHECKPOINT_READBACKS.json',{r['sha256'] for r in load('EXPORT.json')['dependencies']}|{load('EXPORT.json')['sha256']})]:
 m=load(name);(dest/name).write_text(json.dumps({h:m[h] for h in sorted(hashes)},indent=2))
refs={'master0144_restore':{'name':'IG_MASTER_DATA_V1_0144_O3_HANDOFF_2026-10-06.zip','sha256':'acdf876b9feeabac3ad09baa0d98623c5d88c69cb25837d8a57a59238407fe46','drive_file_id':'1HaNha5aXCjks43IVmmkVCHLCDt7_1t2j'},'readiness_restore':{'name':'IG_O4_SOURCE_BOUND_READINESS_HANDOFF_2026-10-06.zip','sha256':'90d2d33536a5263ad0dc9e832745c703089dde96f3561a585db27456ca40aeac','drive_file_id':'1Q1flImNUfUsqjeDAaguySy8FyrTL05-J'},'native_restore':'EXPORT.json and CHECKPOINT_READBACKS.json pin exact saved dependency IDs/hashes. Rebind local paths only, restore checkpoint in pinned runtime then reuse completion; do not regenerate.'};(D/'RECOVERY_DEPENDENCIES.json').write_text(json.dumps(refs,indent=2));(D/'READ_FIRST.txt').write_text(report);(D/'STATUS.json').write_text(json.dumps(s,indent=2));(D/'CONTINUATION_CURSOR.json').write_text(json.dumps({'master_release':'MASTER_DATA_V1_0144','scientific_slices':144,'completed_gate':'0159_SAVED_O4_EXPORT_READER','next_scope':s['next_scope'],'scientific_admission_issued':False,'capture_id':load('POINTER.json')['capture_id'],'completion_sha256':n['completion_sha256'],'result_sha256':n['result_sha256'],'pending_bytes':0,'generation_calls':0},indent=2));(D/'TEMPLATE_COMPLIANCE.json').write_text(json.dumps({'read_first':True,'status':True,'cursor':True,'scientific_bytes_and_code':True,'hash_manifest':True,'native_checkpoint_and_dependency_receipts':True,'lower_O3_incidence_bindings':True,'scope_limits_explicit':True,'completed_constructions_regenerated':False},indent=2));(D/'MANIFEST.json').unlink(missing_ok=True);m={str(p.relative_to(D)):{'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size} for p in D.rglob('*') if p.is_file()};(D/'MANIFEST.json').write_text(json.dumps(m,indent=2));p=Path('IG_O4_GATE_0159_VERIFIED_HANDOFF_2026-10-06.zip')
with zipfile.ZipFile(p,'w',zipfile.ZIP_DEFLATED) as z:
 for name in [*m,'MANIFEST.json']:z.write(D/name,name)
with zipfile.ZipFile(p) as z:
 for name,x in m.items():assert sha(z.read(name))==x['sha256']
Path('CURRENT_START.txt').write_text(str(D/'READ_FIRST.txt')+'\n');Path('IG_O4_GATE_0159_START_2026-10-06.txt').write_text(report+'\nBundle:'+p.name+'\nBundle SHA256:'+sha(p.read_bytes())+'\n');meta={'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size,'manifest_files':len(m)};(B/'DELIVERY_BINDINGS.json').write_text(json.dumps(meta,indent=2));print(meta)
