from pathlib import Path
import json,hashlib,zipfile,shutil,datetime
R=Path.cwd();B=R/'o7_integrate0170';load=lambda n:json.loads((B/n).read_bytes());sha=lambda b:hashlib.sha256(b).hexdigest()
def dump(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
n=load('NATIVE_RESULT.json');cold=load('COLD_REUSE_RESULT.json');ack=load('CHECKPOINT_ACK.json');assert n['status']=='COMPLETED' and n['execution_status']=='FINISHED' and n['evidence_status']=='VERIFIED' and n['result']['outcome']=='PASS' and cold['reused'] and cold['pending_bytes']==0 and ack['outbox']['pending_bytes']==0
r=n['result'];expected={'all_o7_routes_checked':74,'all_o7_owner_routes_checked':322,'all_o7_component_routes_checked':82,'all_o6_routes_checked':134,'all_o6_owner_routes_checked':682,'all_o6_component_routes_checked':172,'all_o5_routes_checked':134,'all_o5_owner_routes_checked':682,'all_o5_component_routes_checked':169,'all_o4_routes_checked':354,'all_o4_owner_routes_checked':1802,'all_o4_component_routes_checked':442,'all_o3_routes_checked':4867,'all_o3_parent_routes_checked':6031,'all_nested_Q_routes_checked':25057,'all_o3_component_routes_checked':4927,'all_o2_routes_checked':26267,'all_o2_parent_routes_checked':63885,'all_node_routes_checked':32545,'all_node_parent_routes_checked':134714,'prior_slices_unchanged':147,'all_pair_routes_checked':1458}
for k,x in expected.items():assert r[k]==x
cat=load('CATALOG_0148.json');prev=json.loads((R/'o6_integrate0166/CATALOG_0147.json').read_bytes());assert cat['slices'][:-1]==prev['slices']
v={'schema':'IG_SAVED_O7_INTEGRATION_RELEASE_V1','release_id':'MASTER_DATA_V1_0148','catalog_sha256':sha((B/'CATALOG_0148.json').read_bytes()),'scientific_slices':148,'status':'VERIFIED_PRESERVED_COLD_REUSED','counts':dict(expected,prior_reader_modules_checked=r['prior_reader_modules_checked']),'o7_scope':cat['slices'][-1]['scope'],'prior_reader_bytes_unchanged':True,'native_completion_sha256':n['completion_sha256'],'native_result_sha256':n['result_sha256'],'cold_reuse':True,'pending_bytes':0,'generation_calls':0,'o7_graduated':False,'automatic_o8_authorized':False,'full_l0_to_g8_complete':False};dump(B/'RELEASE_VERIFICATION.json',v)
report='''INFINITY GRID MASTER_DATA_V1_0148 SAVED O7 ADMITTED/INTEGRATED — 2026-10-06

Release0148,148 scientific slices. Finite scoped admission for72 recovered saved O7 nonseed states and2 external rank0 seeds,HET4 m7=0..5,HOM6 m7=0..1.192 typed E7 edges,322 nested O6 owner occurrences,82 nontrivial component occurrences. Eight selected O6 prototypes retain exact admitted O6 roots/components and ordered O5/O4/O3 resources. Two saved O6 topology twins preserved as external adversarial evidence only. Unrecovered HOM6 m7=2..6 and TWIN4 O7 campaign states are excluded. Lane/rank/binary E7 digest plus full literal payload hashes qualify identity;no global canonicality claim.

Registered gate0170 COMPLETED/FINISHED/VERIFIED. All74 O7 state routes,322 O6 owner routes,82 components and remaining resources pass against master bindings. All134 O6/682 owners/172 components;134 O5/682 owners/169 components;354 O4/1802 owners/442 components;4867 O3/6031 parents/25057 Q routes/4927 components pass. All26267 O2/63885 parents and32545 NODE/134714 parents pass. All147 predecessor catalog slices and reader source bytes unchanged;1458 pair routes and recursive depth1/2 samples pass. Existing300696 J3 and199579 recursive constructions retained;no fresh full legacy science replay claimed.

Capture/checkpoint saved with exact raw readbacks;cold restore/exact result reuse PASS;pending0,generation0. This is finite saved-data reuse. Full final O7 survivor/profile coverage,closeout D1-D6,complete parent/action occurrence ancestry and76 missing microscopic O2 panels remain unresolved. No O7 graduation or automatic O8 authorization. Full L0-G8 completion remains false;WP5 is not globally complete.

NEXT:WP5_SAVED_SCOPE_COVERAGE_AND_PLAN_RECONCILIATION. Reconcile admitted O1-O7 finite scopes against the population plan and saved source inventory. Identify recoverable coverage gaps and explicit remaining gates before proceeding to WP6;do not regenerate completed constructions.
''';(B/'REPORT.txt').write_text(report);(B/'READ_O7_ROUTES.txt').write_text('O7MasterReader adds lookup_o7(lane,rank,digest),o7_owner(...,index),o7_components(...),o7_resources(...),o7_parents(*args). Parent/action ancestry fails explicitly as unavailable. Owner returns exact O6 component/root and nested O5 owners. All predecessor routes delegate through byte-preserved O6MasterReader. Constructor pins0148 catalog,0147 predecessor,scoped admission and inherited archive dependencies. No O7 TWIN4 or unrecovered HOM6 rank2..6 routes.\n')
s=json.loads((R/'CURRENT_STATUS.json').read_bytes());s.update(status_as_of_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),latest_committed_release='MASTER_DATA_V1_0148',catalog_sha256=v['catalog_sha256'],catalog_path='o7_integrate0170/CATALOG_0148.json',scientific_slices=148,next_scope='WP5_SAVED_SCOPE_COVERAGE_AND_PLAN_RECONCILIATION',next_scope_status='NOT_PREPARED',admitted_o7_recovered_saved_typed_carriers={'lanes':{'HET4':[1,5],'HOM6':[1,1]},'external_seed_rank':0,'seed_carriers':2,'carriers':72,'typed_edges':192,'O6_owner_occurrences':322,'component_occurrences':82,'selected_O6_bindings':8,'external_adversarial_O6_twins_evidence_only':2,'complete_derivation_lineage':False,'o7_graduated':False,'automatic_o8_authorized':False,'status':'SCOPED_ADMITTED_AND_UNIFIED_READER_INTEGRATED'},o7_integration_result='o7_integrate0170/NATIVE_RESULT.json',code_mirror=load('CODE_MIRROR.json'));dump(R/'CURRENT_STATUS.json',s)
D=R/'handoff0148_o7';D.mkdir(exist_ok=True);dest=D/B.name;dest.mkdir(exist_ok=True)
for p in B.iterdir():
 if p.is_file() and p.suffix in ['.json','.py','.txt'] and not p.name.startswith('TO_SAVE') and p.name not in ['SAVE_RECEIPT.json','DELIVERY_BINDINGS.json','FRESH_UNPACK_VERIFICATION.json']:shutil.copy2(p,dest/p.name)
shutil.copytree(B/'project',dest/'project',ignore=shutil.ignore_patterns('__pycache__'),dirs_exist_ok=True);shutil.copy2(B/'FINAL_CHECKPOINT_SLIM.zip',dest/'FINAL_CHECKPOINT_SLIM.zip')
for folder in ['o7_export0169','o6_export0165','o5_export0162','o4_export0159','o3_export0156']:
 t=D/folder;t.mkdir(exist_ok=True);shutil.copy2(R/folder/'SCIENTIFIC_EXPORT.zip',t/'SCIENTIFIC_EXPORT.zip')
t=D/'o6_integrate0166';t.mkdir(exist_ok=True);shutil.copy2(R/'o6_integrate0166/CATALOG_0147.json',t/'CATALOG_0147.json')
for name,hashes in [('READBACKS.json',{r['sha256'] for r in load('PENDING.json')['pending_objects']}),('CHECKPOINT_READBACKS.json',{r['sha256'] for r in load('EXPORT.json')['dependencies']}|{load('EXPORT.json')['sha256']})]:
 m=load(name);dump(dest/name,{h:m[h] for h in sorted(hashes)})
dump(D/'RECOVERY_DEPENDENCIES.json',{'master147_base':{'drive_file_id':'1EcDvoG2BozFXbLN08T1fSmZoMF8rzs34','sha256':'9f3d5bb4b413ebb6dfecacd3f5adc53535caf5869af417a836665d9b6e338b34'},'O7_export_gate':{'drive_file_id':'1EGQLYN104kTMnLgkWMukouJ0oZLAlnaL','sha256':'536f5dc6d9c3e09ff985f4264af3d21daf666315a8f62470ce4d194ff94889f9'},'recovery':'Restore0147 base and its pinned dependencies then overlay this compact0148 delta. Latest STATUS/cursor override ancestor prose. Native restore uses exact dependency IDs/hashes and completion reuse;never regenerate.'})
dump(D/'STATUS.json',s);(D/'READ_FIRST.txt').write_text(report+'\nVerify MANIFEST.json,then recover pinned predecessor dependencies.\n');dump(D/'CONTINUATION_CURSOR.json',{'master_release':'MASTER_DATA_V1_0148','scientific_slices':148,'completed_gate':'0170_O7_SCOPED_ADMISSION_AND_CATALOG_INTEGRATION','next_scope':s['next_scope'],'next_job_captured':False,'pending_bytes':0,'generation_calls':0});dump(D/'TEMPLATE_COMPLIANCE.json',{'current_release':'MASTER_DATA_V1_0148','registered_gate':'0170','read_first':True,'status':True,'cursor':True,'code_and_new_scientific_bytes':True,'prior_scientific_bytes_pinned_restore_reference':True,'manifest':True,'native_checkpoint_receipts':True,'full_l0_to_g8_complete':False})
(D/'MANIFEST.json').unlink(missing_ok=True);m={str(p.relative_to(D)):{'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size} for p in D.rglob('*') if p.is_file()};dump(D/'MANIFEST.json',m);p=R/'IG_MASTER_DATA_V1_0148_O7_HANDOFF_2026-10-06.zip'
with zipfile.ZipFile(p,'w',zipfile.ZIP_DEFLATED) as z:
 for name in [*m,'MANIFEST.json']:z.write(D/name,name)
with zipfile.ZipFile(p) as z:
 for name,x in m.items():assert sha(z.read(name))==x['sha256']
(R/'CURRENT_START.txt').write_text('handoff0148_o7/READ_FIRST.txt\n');(R/'IG_MASTER_DATA_V1_0148_O7_START_2026-10-06.txt').write_text(report+'\nBundle:'+p.name+'\nBundle SHA256:'+sha(p.read_bytes())+'\n');meta={'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size,'manifest_files':len(m)};dump(B/'DELIVERY_BINDINGS.json',meta);print(json.dumps(meta))
