from pathlib import Path
import json,hashlib,shutil,datetime
B=Path(__file__).resolve().parent;R=B.parent;E=R/'o7_export0169';sha=lambda b:hashlib.sha256(b).hexdigest();load=lambda p:json.loads(p.read_bytes())
n=load(E/'NATIVE_RESULT.json');cold=load(E/'COLD_REUSE_RESULT.json');ack=load(E/'CHECKPOINT_ACK.json');r=n['result']
assert n['status']=='COMPLETED' and n['evidence_status']=='VERIFIED' and r['outcome']=='PASS' and cold['reused'] and cold['completion_sha256']==n['completion_sha256'] and cold['result_sha256']==n['result_sha256'] and ack['outbox']['pending_bytes']==0
assert r['carriers']==72 and r['seed_carriers']==2 and r['all_occurrence_routes_checked']==74 and r['all_O6_owner_routes_checked']==322 and r['all_component_routes_checked']==82 and not r['complete_derivation_lineage']
oldp=R/'o6_integrate0166/CATALOG_0147.json';old=load(oldp);oldsha=sha(oldp.read_bytes());assert oldsha=='22b45a2479c7f3022a57e25971cd7235951d877c881d2bd378f6fef3ac99c21e'
v=load(R/'o7_readiness0168/READINESS_VALIDATION.json');ad={'schema_id':'IG_MASTER_SCOPED_DATA_ADMISSION_V1','decision':'ACCEPTED_FOR_REUSE_WITHIN_RECOVERED_SAVED_O7_TYPED_INCIDENCE_AND_ADMITTED_O6_COMPONENT_SCOPE','authority':'EXTERNAL_OPERATOR_DECISION_UNDER_USER_AUTHORIZED_MASTER_CAMPAIGN','admitted_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'dataset_id':'O7_RECOVERED_SAVED_TYPED_CARRIERS_HET4_0_5_HOM6_0_1_WITH_O6_BINDINGS_V1','scientific_root_sha256':r['scientific_root_sha256'],'scientific_archive_sha256':r['archive_sha256'],'predecessor_catalog_sha256':oldsha,'scope':{'lanes':{'HET4':{'ranks':[1,5]},'HOM6':{'ranks':[1,1]}},'external_seed_rank':0,'population':'Immutable recovered saved selected O7 typed E7 incidence;ordered admitted O6 components and full source roots','external_twin_roots':'Two source-bound adversarial O6 witnesses retained as evidence only; no TWIN4 O7 state admission','missing_microscopic_O2_panels':76,'complete_derivation_lineage':False,'state_hash_encoding':'SHA256(prefix IG-E7-STATE-v1| plus fourteen uint32 big-endian integers per sorted edge)'},'counts':{k:r[k] for k in ['carriers','seed_carriers','typed_edges','components','O6_owner_occurrences','selected_O6_bindings','external_twin_roots','all_occurrence_routes_checked','all_O6_owner_routes_checked','all_component_routes_checked']},'identity':'LANE_RANK_QUALIFIED_BINARY_E7_DIGEST_PLUS_FULL_LITERAL_STATE_PAYLOAD_SHA256;FROZEN_ORDERED_O6_OWNER_IDENTITIES','native_capture_id':ack['capture_id'],'native_completion_sha256':n['completion_sha256'],'native_result_sha256':n['result_sha256'],'cold_reuse':True,'pending_bytes':0,'generator_calls':0,'o7_graduated':False,'automatic_o8_authorized':False,'not_covered':['Unrecovered HOM6 m7=2..6 and TWIN4 campaign state/profile coverage','Historical closeout D1-D6 certification','Full O7 candidate census or parent/action occurrence ancestry','Global isomorphism canonicalization','Microscopic O2 source closure/Q-bank reproduction','O7 graduation/automatic O8','Geometry/actualization/full L0-G8 completion'],'evidence':[]}
for p in [E/'NATIVE_RESULT.json',E/'COLD_REUSE_RESULT.json',E/'CHECKPOINT_ACK.json',E/'SAVE_RECEIPT.json',R/'o7_readiness0168/EXPORT_CONTRACT.json',R/'o7_readiness0168/READINESS_VALIDATION.json']:ad['evidence'].append({'file_name':str(p.relative_to(R)),'sha256':sha(p.read_bytes())})
p=B/'SCOPED_ADMISSION.json'
if p.exists():ad=load(p)
else:p.write_text(json.dumps(ad,indent=2)+'\n')
cat=json.loads(json.dumps(old));cat.update(release_id='MASTER_DATA_V1_0148',previous_release_id='MASTER_DATA_V1_0147',previous_catalog_sha256=oldsha);a=load(E/'READBACKS.json')[r['archive_sha256']]
cat['slices'].append({'dataset_id':ad['dataset_id'],'scientific_root_sha256':r['scientific_root_sha256'],'format':'IG_SAVED_O7_TYPED_CARRIERS_EXPORT_V1','identity_profile':ad['identity'],'scope':ad['scope'],'counts':ad['counts'],'scoped_admission_sha256':sha(p.read_bytes()),'scientific_dependencies':[{'role':'ADMITTED_O6_COMPONENT_ROOT_BINDINGS','catalog_sha256':oldsha,'scientific_root_sha256':old['slices'][-1]['scientific_root_sha256'],'bindings':load(R/'o7_readiness0168/O6_BINDINGS.json')},{'role':'EXTERNAL_RANK0_SELECTED_SEEDS','records':2,'lanes':['HET4','HOM6']},{'role':'EXTERNAL_ADVERSARIAL_O6_TWIN_EVIDENCE_ONLY','records':2}],'archive':{'file_name':'IG_O7_RECOVERED_SAVED_TYPED_CARRIER_SCIENTIFIC_EXPORT_2026-10-06.zip','sha256':r['archive_sha256'],'size_bytes':(E/'SCIENTIFIC_EXPORT.zip').stat().st_size,'drive_file_id':a['id'],'drive_folder_id':'1ALFgcEwVXK7r4yzkP1tJQsOMUPilsAzZ'}})
cat['coverage_summary']['o7_recovered_saved_typed_carriers']=ad['counts'];cat['coverage_summary']['o7_complete_derivation_lineage']=False;cat['coverage_summary']['o7_graduated']=False;(B/'CATALOG_0148.json').write_text(json.dumps(cat,indent=2)+'\n')
shutil.copytree(R/'o6_integrate0166/project',B/'project/previous_o6',ignore=shutil.ignore_patterns('__pycache__'),dirs_exist_ok=True)
for name in ['reader.py','frozen_o7.py']:shutil.copy2(E/'project'/name,B/'project'/name)
(B/'project/__init__.py').write_text('');bindings={'CATALOG_SHA256':sha((B/'CATALOG_0148.json').read_bytes()),'PREVIOUS_SHA256':oldsha,'ADMISSION_SHA256':sha(p.read_bytes())};(B/'project/bindings.py').write_text('\n'.join(k+'='+repr(v) for k,v in bindings.items())+'\n')
manifest={str(p.relative_to(B/'project/previous_o6')):sha(p.read_bytes()) for p in (B/'project/previous_o6').rglob('*.py')};(B/'PREDECESSOR_SOURCE_HASHES.json').write_text(json.dumps(manifest,indent=2))
for name,h in manifest.items():assert sha((R/'o6_integrate0166/project'/name).read_bytes())==h
s=load(R/'o6_integrate0166/SPEC.json');s.update(job_id='MASTER.O7.RECOVERED.SAVED.TYPED.CARRIERS.CATALOG.INTEGRATION.V1',project_source=str(B/'project'));s['question'].update(stage_id='MASTER:O7:RECOVERED:SAVED:TYPED:CARRIERS:CATALOG:INTEGRATION:V1',description='Finite recovered saved O7 typed incidence integrates into0148;preserve147 predecessor slices/readers',stopping_rule='All74 O7 state/322 owner/82 component routes and all inherited routes;unchanged147 predecessor slices/reader bytes. Stop first mismatch;no generation.');s['execution']['parameters']={};s['inputs']=[x for x in s['inputs'] if x['logical_name'] not in ['new_catalog','predecessor_sources']]
for name,p in [('new_catalog',B/'CATALOG_0148.json'),('o7_admission',B/'SCOPED_ADMISSION.json'),('o7_archive',E/'SCIENTIFIC_EXPORT.zip'),('catalog0147',oldp),('predecessor_sources',B/'PREDECESSOR_SOURCE_HASHES.json'),('prior_o6_sources',R/'o6_integrate0166/PREDECESSOR_SOURCE_HASHES.json')]:s['inputs'].append({'logical_name':name,'path':str(p),'sha256':sha(p.read_bytes())})
checks={x['pointer']:x['equals'] for x in s['output_contract']['result_checks']};checks.update({'/all_o7_routes_checked':74,'/all_o7_owner_routes_checked':322,'/all_o7_component_routes_checked':82,'/prior_slices_unchanged':147,'/scientific_slices':148,'/release_id':'MASTER_DATA_V1_0148'});s['output_contract']['result_checks']=[{'pointer':k,'equals':v} for k,v in checks.items()];(B/'SPEC.json').write_text(json.dumps(s,indent=2))
for name in ['operate.py','cold_ops.py']:shutil.copy2(E/name,B/name)
print(json.dumps(bindings))
