from pathlib import Path
import json,hashlib,zipfile,shutil,datetime
B=Path('o5_integrate0163');load=lambda n:json.load(open(B/n));n=load('NATIVE_RESULT.json');cold=load('COLD_REUSE_RESULT.json');ack=load('CHECKPOINT_ACK.json');assert n['status']=='COMPLETED' and n['execution_status']=='FINISHED' and n['evidence_status']=='VERIFIED' and n['result']['outcome']=='PASS' and cold['reused'] and cold['pending_bytes']==0 and ack['outbox']['pending_bytes']==0
r=n['result'];expected={'all_o5_routes_checked':134,'all_o5_owner_routes_checked':682,'all_o5_component_routes_checked':169,'all_o4_routes_checked':354,'all_o4_owner_routes_checked':1802,'all_o4_component_routes_checked':442,'all_o3_routes_checked':4867,'all_o3_parent_routes_checked':6031,'all_nested_Q_routes_checked':25057,'all_o3_component_routes_checked':4927,'all_o2_routes_checked':26267,'all_o2_parent_routes_checked':63885,'all_node_routes_checked':32545,'all_node_parent_routes_checked':134714,'prior_slices_unchanged':145,'all_pair_routes_checked':1458}
for k,x in expected.items():assert r[k]==x
sha=lambda b:hashlib.sha256(b).hexdigest();cat=load('CATALOG_0146.json');prev=json.load(open('o4_integrate0160/CATALOG_0145.json'));assert cat['slices'][:-1]==prev['slices']
v={'schema':'IG_SAVED_O5_INTEGRATION_RELEASE_V1','release_id':'MASTER_DATA_V1_0146','catalog_sha256':sha((B/'CATALOG_0146.json').read_bytes()),'scientific_slices':146,'status':'VERIFIED_PRESERVED_COLD_REUSED','counts':dict(expected,prior_reader_modules_checked=r['prior_reader_modules_checked']),'o5_scope':cat['slices'][-1]['scope'],'prior_reader_bytes_unchanged':True,'native_completion_sha256':n['completion_sha256'],'native_result_sha256':n['result_sha256'],'cold_reuse':True,'pending_bytes':0,'generation_calls':0,'full_l0_to_g8_complete':False};(B/'RELEASE_VERIFICATION.json').write_text(json.dumps(v,indent=2))
report='''INFINITY GRID MASTER_DATA_V1_0146 SAVED O5 ADMITTED/INTEGRATED — 2026-10-06

Release0146,146 scientific slices. Scoped admission for132 saved O5 nonseed selected states and2 external rank0 seeds in HET4(m5=0..5) and HOM6(m5=0..6),432 typed E5 edges,682 nested O4 owner occurrences and169 nontrivial connected-component occurrences. Seven ordered-resource prototype bindings resolve exact admitted O4 component incidence and full source roots, with nested O3 component/root references. All typed E5 ten-coordinate endpoints, parallel multiplicity, original owner order, component incidence/accounting and remaining resources retained. Identity includes lane/rank/edge digest plus full literal payload SHA256; edge-only digest alone omits owner identity. No global canonical-isomorphism claim.

Registered integration gate0163 COMPLETED/FINISHED/VERIFIED. All134 O5 root routes,682 owner routes and169 component routes pass, including master O4 and nested O3 bindings and remaining-resource routes. Existing354 O4 routes/1802 owners/442 components and4867 O3 routes/6031 parents/25057 Q routes/4927 components pass. Existing26267 O2 routes/63885 parents and32545 NODE routes/134714 parents pass. All145 predecessor catalog slices and reader source bytes unchanged;1458 pair object routes and recursive depth1/2 samples pass. Existing300696 J3/199579 recursive constructions retained. No fresh full legacy science replay claimed.

Capture and checkpoint saved with raw readbacks; cold restore/exact completion reuse PASS;pending bytes0;generation calls0. This is scoped saved-data reuse, not a new full O5 census or fresh graduation. Saved O5 rows lack complete parent/action occurrence ancestry. Inherited anonymous(p,u2) Qbank does not close microscopic O2 incidence or bank-selection provenance;76 missing panels remain unresolved. Full L0-G8 completion remains false.

NEXT:WP5_SAVED_O6_SOURCE_BOUND_READINESS. Bind original selected O5 prototypes and pinned component to this admitted O5 slice, verify retained nested coordinates/incidences and identify a finite lossless saved export scope. Do not regenerate completed constructions or claim WP5 complete.
''';(B/'REPORT.txt').write_text(report);(B/'READ_O5_ROUTES.txt').write_text('O5MasterReader adds lookup_o5(lane,rank,digest),o5_owner(...,index),o5_components(...),o5_resources(...),o5_parents(*args). Parent/action ancestry fails explicitly as unavailable. Owner routes return ordered prototype resources, exact O4 component/root binding and nested O3 owners. Components retain typed E5 parallel multiplicity and original root owner indices. Existing O4/O3/O2/NODE/J3/pair/recursive routes delegate through byte-preserved previous readers. Constructor pins0146 catalog,0145 predecessor, scoped admission and all inherited archive dependencies. Recover native checkpoint using exact saved dependency IDs/hashes; rebind paths only. No generation/repair path.\n')
s=json.load(open('CURRENT_STATUS.json'));s.update(status_as_of_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),latest_committed_release='MASTER_DATA_V1_0146',catalog_sha256=v['catalog_sha256'],catalog_path='o5_integrate0163/CATALOG_0146.json',scientific_slices=146,next_scope='WP5_SAVED_O6_SOURCE_BOUND_READINESS',next_scope_status='NOT_PREPARED',admitted_o5_saved_typed_carriers={'lanes':{'HET4':[1,5],'HOM6':[1,6]},'external_seed_rank':0,'seed_carriers':2,'carriers':132,'typed_edges':432,'O4_owner_occurrences':682,'component_occurrences':169,'prototype_bindings':7,'complete_derivation_lineage':False,'microscopic_O2_source_closed':False,'status':'SCOPED_ADMITTED_AND_UNIFIED_READER_INTEGRATED'},o5_integration_result='o5_integrate0163/NATIVE_RESULT.json',code_mirror=load('CODE_MIRROR.json'));Path('CURRENT_STATUS.json').write_text(json.dumps(s,indent=2));D=Path('handoff0146_o5');D.mkdir(exist_ok=True);dest=D/B;dest.mkdir(exist_ok=True)
for p in B.iterdir():
 if p.is_file() and p.suffix in ['.json','.py','.txt'] and not p.name.startswith('TO_SAVE'):shutil.copy2(p,dest/p.name)
shutil.copytree(B/'project',dest/'project',ignore=shutil.ignore_patterns('__pycache__'),dirs_exist_ok=True);shutil.copy2(B/'FINAL_CHECKPOINT_SLIM.zip',dest/'FINAL_CHECKPOINT_SLIM.zip')
for folder,name in [('o5_export0162','SCIENTIFIC_EXPORT.zip'),('o4_export0159','SCIENTIFIC_EXPORT.zip'),('o3_export0156','SCIENTIFIC_EXPORT.zip'),('o4_integrate0160','CATALOG_0145.json')]:
 target=D/folder;target.mkdir(exist_ok=True);shutil.copy2(Path(folder)/name,target/name)
for name,hashes in [('READBACKS.json',{r['sha256'] for r in load('PENDING.json')['pending_objects']}),('CHECKPOINT_READBACKS.json',{r['sha256'] for r in load('EXPORT.json')['dependencies']}|{load('EXPORT.json')['sha256']})]:
 m=load(name);(dest/name).write_text(json.dumps({h:m[h] for h in sorted(hashes)},indent=2))
receipt=json.load(open('o5_export0162/SAVE_RECEIPT.json'));export_bundle=next(x for x in receipt['files'] if x['name'].endswith('.zip'))
refs={'master0145_base':{'name':'IG_MASTER_DATA_V1_0145_O4_HANDOFF_2026-10-06.zip','sha256':'5fc9acdf7f7b4d62fc07467924d98a30d1c188cab3d5d6b5aecca4919643c7ac','drive_file_id':'1jG069nObAHMoSJHnXmGUeM9KjIuzn7fZ'},'O5_export_gate':{'name':export_bundle['name'],'sha256':export_bundle['sha256'],'drive_file_id':export_bundle['id']},'higher_O_sources':{'name':'IG_O4_SOURCE_BOUND_READINESS_HANDOFF_2026-10-06.zip','sha256':'90d2d33536a5263ad0dc9e832745c703089dde96f3561a585db27456ca40aeac','drive_file_id':'1Q1flImNUfUsqjeDAaguySy8FyrTL05-J'},'recovery':'Compact master delta contains0146 catalog/admission, current reader code, O5/O4/O3 scientific bytes and native checkpoint receipts. Restore0145 base and its dependencies for earlier science, then overlay this delta. Current STATUS/cursor override ancestor prose. Native restore uses exact saved dependency IDs/hashes, then completion reuse;never regenerate.'};(D/'RECOVERY_DEPENDENCIES.json').write_text(json.dumps(refs,indent=2));(D/'STATUS.json').write_text(json.dumps(s,indent=2));(D/'READ_FIRST.txt').write_text(report+'\nRestore:RECOVERY_DEPENDENCIES.json. Verify MANIFEST.json first.\n');(D/'CONTINUATION_CURSOR.json').write_text(json.dumps({'master_release':'MASTER_DATA_V1_0146','scientific_slices':146,'completed_gate':'0163_O5_SCOPED_ADMISSION_AND_CATALOG_INTEGRATION','next_scope':s['next_scope'],'next_job_captured':False,'pending_bytes':0,'generation_calls':0},indent=2));(D/'TEMPLATE_COMPLIANCE.json').write_text(json.dumps({'current_release':'MASTER_DATA_V1_0146','registered_gate':'0163','read_first':True,'status':True,'cursor':True,'code_and_new_scientific_bytes':True,'prior_scientific_bytes_pinned_restore_reference':True,'manifest':True,'native_checkpoint_receipts':True,'full_l0_to_g8_complete':False},indent=2));(D/'MANIFEST.json').unlink(missing_ok=True);m={str(p.relative_to(D)):{'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size} for p in D.rglob('*') if p.is_file()};(D/'MANIFEST.json').write_text(json.dumps(m,indent=2));p=Path('IG_MASTER_DATA_V1_0146_O5_HANDOFF_2026-10-06.zip')
with zipfile.ZipFile(p,'w',zipfile.ZIP_DEFLATED) as z:
 for name in [*m,'MANIFEST.json']:z.write(D/name,name)
with zipfile.ZipFile(p) as z:
 for name,x in m.items():assert sha(z.read(name))==x['sha256']
Path('CURRENT_START.txt').write_text(str(D/'READ_FIRST.txt')+'\n');Path('IG_MASTER_DATA_V1_0146_O5_START_2026-10-06.txt').write_text(report+'\nBundle:'+p.name+'\nBundle SHA256:'+sha(p.read_bytes())+'\n');meta={'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size,'manifest_files':len(m)};(B/'DELIVERY_BINDINGS.json').write_text(json.dumps(meta,indent=2));print(meta)
