from pathlib import Path
import json,hashlib,shutil,datetime
B=Path(__file__).resolve().parent;R=B.parent;E=R/'o5_export0162';sha=lambda b:hashlib.sha256(b).hexdigest();load=lambda p:json.load(open(p));n=load(E/'NATIVE_RESULT.json');cold=load(E/'COLD_REUSE_RESULT.json');ack=load(E/'CHECKPOINT_ACK.json');r=n['result'];assert n['status']=='COMPLETED' and n['evidence_status']=='VERIFIED' and r['outcome']=='PASS' and cold['reused'] and cold['completion_sha256']==n['completion_sha256'] and cold['result_sha256']==n['result_sha256'] and ack['outbox']['pending_bytes']==0
assert r['carriers']==132 and r['seed_carriers']==2 and r['all_occurrence_routes_checked']==134 and r['all_O4_owner_routes_checked']==682 and r['all_component_routes_checked']==169 and not r['microscopic_O2_source_closed'] and not r['complete_derivation_lineage']
oldp=R/'o4_integrate0160/CATALOG_0145.json';old=load(oldp);oldsha=sha(oldp.read_bytes());assert oldsha=='69399952d69963c9ddbf8ba278fba3cb2052ff2725c0cb8155d286f9a24bd304'
v=load(R/'o5_readiness0161/READINESS_VALIDATION.json');ad={'schema_id':'IG_MASTER_SCOPED_DATA_ADMISSION_V1','decision':'ACCEPTED_FOR_REUSE_WITHIN_SAVED_O5_TYPED_INCIDENCE_AND_ADMITTED_O4_COMPONENT_SCOPE','authority':'EXTERNAL_OPERATOR_DECISION_UNDER_USER_AUTHORIZED_MASTER_CAMPAIGN','admitted_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'dataset_id':'O5_SAVED_TYPED_CARRIERS_HET4_HOM6_WITH_EXTERNAL_RANK0_SEEDS_AND_O4_BINDINGS_V1','scientific_root_sha256':r['scientific_root_sha256'],'scientific_archive_sha256':r['archive_sha256'],'predecessor_catalog_sha256':oldsha,'scope':{'lanes':{'HET4':{'ranks':[1,5]},'HOM6':{'ranks':[1,6]}},'external_seed_rank':0,'population':'Immutable saved selected O5 typed E5 incidence; ordered O4 owner components and full source roots retained through admitted bindings','entity_boundary':'Inherited anonymous local(p,u2) Q bank; microscopic O2 incidence and bank-selection reproduction external','missing_microscopic_O2_panels':76,'complete_derivation_lineage':False},'counts':{k:r[k] for k in ['carriers','seed_carriers','typed_edges','components','O4_owner_occurrences','prototype_bindings','all_occurrence_routes_checked','all_O4_owner_routes_checked','all_component_routes_checked']},'identity':'LANE_RANK_QUALIFIED_EDGE_DIGEST_PLUS_FULL_LITERAL_STATE_PAYLOAD_SHA256; ORDERED_OWNER_IDENTITIES_AND_TYPED_EDGE_MULTISET','native_capture_id':ack['capture_id'],'native_completion_sha256':n['completion_sha256'],'native_result_sha256':n['result_sha256'],'cold_reuse':True,'pending_bytes':0,'generator_calls':0,'historical_audit_reexecuted':False,'not_covered':['Full O5 candidate census','Stored parent/action occurrence ancestry or action multiplicity','Global isomorphism canonicalization from edge-only digest','Microscopic O2 source closure and Q-bank selection reproduction','Fresh O5 graduation authority','Geometry/actualization','Full L0-to-G8 completion'],'evidence':[]}
for p in [E/'NATIVE_RESULT.json',E/'COLD_REUSE_RESULT.json',E/'CHECKPOINT_ACK.json',E/'SAVE_RECEIPT.json',R/'o5_readiness0161/EXPORT_CONTRACT.json',R/'o5_readiness0161/READINESS_VALIDATION.json']:ad['evidence'].append({'file_name':str(p.relative_to(R)),'sha256':sha(p.read_bytes())})
p=B/'SCOPED_ADMISSION.json'
if p.exists():ad=load(p)
else:p.write_text(json.dumps(ad,indent=2))
cat=json.loads(json.dumps(old));cat.update(release_id='MASTER_DATA_V1_0146',previous_release_id='MASTER_DATA_V1_0145',previous_catalog_sha256=oldsha);a=load(E/'READBACKS.json')[r['archive_sha256']];cat['slices'].append({'dataset_id':ad['dataset_id'],'scientific_root_sha256':r['scientific_root_sha256'],'format':'IG_SAVED_O5_TYPED_CARRIERS_EXPORT_V1','identity_profile':ad['identity'],'scope':ad['scope'],'counts':ad['counts'],'scoped_admission_sha256':sha(p.read_bytes()),'scientific_dependencies':[{'role':'ADMITTED_O4_COMPONENT_ROOT_BINDINGS','catalog_sha256':oldsha,'scientific_root_sha256':old['slices'][-1]['scientific_root_sha256'],'bindings':v['prototype_bindings']},{'role':'EXTERNAL_RANK0_SELECTED_SEEDS','records':2,'lanes':['HET4','HOM6']}],'archive':{'file_name':'IG_O5_SAVED_TYPED_CARRIER_SCIENTIFIC_EXPORT_2026-10-06.zip','sha256':r['archive_sha256'],'size_bytes':(E/'SCIENTIFIC_EXPORT.zip').stat().st_size,'drive_file_id':a['id'],'drive_folder_id':'1ALFgcEwVXK7r4yzkP1tJQsOMUPilsAzZ'}});cat['coverage_summary']['o5_saved_typed_carriers']=ad['counts'];cat['coverage_summary']['o5_complete_derivation_lineage']=False;(B/'CATALOG_0146.json').write_text(json.dumps(cat,indent=2)+'\n')
shutil.copytree(R/'o4_integrate0160/project',B/'project/previous_o4',ignore=shutil.ignore_patterns('__pycache__'),dirs_exist_ok=True)
for name in ['reader.py','frozen_o5.py']:shutil.copy2(E/'project'/name,B/'project'/name)
(B/'project/__init__.py').write_text('');bindings={'CATALOG_SHA256':sha((B/'CATALOG_0146.json').read_bytes()),'PREVIOUS_SHA256':oldsha,'ADMISSION_SHA256':sha(p.read_bytes())};(B/'project/bindings.py').write_text('\n'.join(k+'='+repr(v) for k,v in bindings.items())+'\n')
manifest={str(p.relative_to(B/'project/previous_o4')):sha(p.read_bytes()) for p in (B/'project/previous_o4').rglob('*.py')};(B/'PREDECESSOR_SOURCE_HASHES.json').write_text(json.dumps(manifest,indent=2))
for name,h in manifest.items():assert sha((R/'o4_integrate0160/project'/name).read_bytes())==h
s=load(R/'o4_integrate0160/SPEC.json');s.update(job_id='MASTER.O5.SAVED.TYPED.CARRIERS.CATALOG.INTEGRATION.V1',project_source=str(B/'project'));s['question'].update(stage_id='MASTER:O5:SAVED:TYPED:CARRIERS:CATALOG:INTEGRATION:V1',description='Scoped saved O5 typed incidence with admitted O4 component bindings integrates into0146; preserve145 predecessor slices/readers',stopping_rule='All O5 state/owner/component routes and inherited O3/O2/NODE routes; unchanged145 predecessor slices and reader bytes. Stop first mismatch; no generation.');s['execution']['parameters']={};s['inputs']=[x for x in s['inputs'] if x['logical_name'] not in ['new_catalog','predecessor_sources']]
for name,p in [('new_catalog',B/'CATALOG_0146.json'),('o5_admission',B/'SCOPED_ADMISSION.json'),('o5_archive',E/'SCIENTIFIC_EXPORT.zip'),('catalog0145',oldp),('predecessor_sources',B/'PREDECESSOR_SOURCE_HASHES.json')]:s['inputs'].append({'logical_name':name,'path':str(p),'sha256':sha(p.read_bytes())})
s['output_contract']['result_checks']=[{'pointer':'/'+k,'equals':v} for k,v in {'outcome':'PASS','all_o5_routes_checked':134,'all_o5_owner_routes_checked':682,'all_o5_component_routes_checked':169,'all_o4_routes_checked':354,'all_o4_owner_routes_checked':1802,'all_o4_component_routes_checked':442,'all_o3_routes_checked':4867,'all_o3_parent_routes_checked':6031,'all_nested_Q_routes_checked':25057,'all_o3_component_routes_checked':4927,'all_o2_routes_checked':26267,'all_o2_parent_routes_checked':63885,'all_node_routes_checked':32545,'all_node_parent_routes_checked':134714,'prior_slices_unchanged':145,'prior_reader_bytes_unchanged':True,'generation_calls':0}.items()];(B/'SPEC.json').write_text(json.dumps(s,indent=2))
for name in ['operate.py','cold_ops.py']:shutil.copy2(E/name,B/name)
print(bindings)
