"""Preserve scoped historical terminal qualification without master admission."""
from pathlib import Path
import json,hashlib,zipfile,datetime
B=Path(__file__).resolve().parent;W=B.parent;P=Path('/workspace/scratch/75d85ae95659');A=json.loads((B/'AUDIT.json').read_text());assert A['status']=='PASS_COLD_HISTORICAL_V1_TERMINAL100_REQUALIFICATION'
assert json.loads((B/'CHECKPOINT_PRESERVED.json').read_text())['pending_bytes']==0
N=json.loads((B/'NATIVE_RESULT.json').read_text());assert N['status']=='COMPLETED' and N['evidence_status']=='VERIFIED'
assert json.loads((B/'NATIVE_EXPORT_SAVE.json').read_text())['raw_readback_verified']
(B/'REPORT.txt').write_text('Checkpoint 0231: historical V1 terminal100 requalification complete.\n\nAccepted historical replay depth advances from98 to100 under the explicit historical V1 scope. Master remains151; no admissions; no G2 promotion. Prior failed0229 and diagnostic0230 evidence remains unchanged.\n\nOne registered native RESTORATION task decoded all193 saved terminal roots. The full193-root DAG roundtrip passed. All193 V1 interface rows and the complete population object equal the untouched historical reference exactly. The archived24-root beam matches construction digest, boundary skin and capacities. The separately retained current V2 extractor exactly reproduces the saved0230 V2 population. The engine and current V2 resource were not modified.\n\nIndependent cold restoration verified saved native result identity, repeated all193 DAG roundtrips, all193 V1 interface rows, complete population equality, current V2 population equality and the archived24 beam gate. Candidate generation: zero in input recovery, native restoration and cold audit. Base O7 kernel loading is required to decode the saved DAG; no depth8-100 candidate recipes were executed.\n\nThe mismatch was a specification provenance binding: the historical reference uses V1, while the current extractor uses V2. The correction binds the historical adapter explicitly to V1, preserves V2 separately and retains full exact equality as the gate. It does not strip fields or overwrite the reference.\n\nRecovery: verify MANIFEST.json; recover CHECKPOINT_EXPORT.json dependencies from READBACKS.json Drive IDs with exact raw hashes and sizes. restore_current.py uses the pinned CPython3.13.5/SQLite3.51.3 runtime and frozen engine. The exact compressed193-root saved input and source-input derivation record are bundled. Runtime recovery and predecessor handoff references are included.\n\nNext: seal the qualified G1 terminal population and prepare its scoped master admission and downstream G2 source binding review. Reuse saved populations; do not regenerate. Historical V1 qualification does not approve current V2 S1 repairs or confer G2 graduation.\n')
s=json.loads((P/'CURRENT_STATUS.json').read_text());s.pop('latest_handoff',None);s.update(status_as_of_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),latest_checkpoint=231,latest_accepted_checkpoint=231,latest_capture_id=json.loads((B/'POINTER.json').read_text())['capture_id'],in_flight_active=None,active_native_runtime=None,current_phase='G1_HISTORICAL_V1_TERMINAL100_REQUALIFIED',completed_depth=100,historical_verified_depth=100,historical_cold_audited_depth=100,historical_reconstructed_depth=100,historical_qualification_scope=A['qualification_scope'],latest_audit=A,checkpoint0231=A,terminal_comparison=A['terminal_comparison'],terminal_diagnostic_only=False,candidate_build_calls=0,generator_calls=0,committed_restoration_tasks=1,generator_calls_scope='0231: restoration only; zero candidate generation',pending_bytes=0,master_slices=151,new_admissions=0,next_scope='G1_TERMINAL_POPULATION_SEAL_AND_SCOPED_ADMISSION_PREPARATION',next_scope_status='G1_HISTORICAL_V1_QUALIFIED_NO_MASTER_ADMISSION_NO_G2_PROMOTION',catalog_path=str(B/'CATALOG_0151.json'),candidate_count_scope='Saved terminal100 cohort193 restored without generation; complete reference equality under historical V1',prior_bounded_replay_claim_scope='Historical V1 terminal193 exact population qualification established at0231')
if (B/'CODE_MIRROR.json').exists():s['code_mirror']=json.loads((B/'CODE_MIRROR.json').read_text())
(B/'STATUS_CANDIDATE.json').write_text(json.dumps(s,indent=2));(W/'CURRENT_STATUS.json').write_text(json.dumps(s,indent=2));(P/'CURRENT_STATUS.json').write_text(json.dumps(s,indent=2))
files={str(p.relative_to(W)):p for p in sorted(B.rglob('*')) if p.is_file() and p.suffix in ('.py','.json','.txt','.zip','.log','.gz') and '__pycache__' not in p.parts and not p.name.startswith('private_') and p.name not in ('MIRROR_ELEMENTS.json','DELIVERABLES.json','SAVE_RECEIPT.json')}
manifest={k:dict(bytes=p.stat().st_size,sha256=hashlib.file_digest(p.open('rb'),'sha256').hexdigest()) for k,p in files.items()};out=W/'IG_MASTER151_G1_HISTORICAL_V1_TERMINAL100_0231_HANDOFF_2026-10-09.zip'
with zipfile.ZipFile(out,'w',zipfile.ZIP_DEFLATED,compresslevel=6) as z:
 for k,p in files.items():z.write(p,k)
 z.writestr('MANIFEST.json',json.dumps(manifest,indent=2))
with zipfile.ZipFile(out) as z:
 assert z.testzip() is None
 for k,v in manifest.items():assert hashlib.sha256(z.read(k)).hexdigest()==v['sha256']
r=dict(path=str(out),sha256=hashlib.file_digest(out.open('rb'),'sha256').hexdigest(),bytes=out.stat().st_size,checkpoint=231,status=A['status'],historical_verified_depth=100,qualification_scope=A['qualification_scope'],native_completion_status='VERIFIED',terminal_comparison=A['terminal_comparison'],master_slices=151,new_admissions=0,native_pending_bytes=0,next_scope=s['next_scope']);(B/'DELIVERABLES.json').write_text(json.dumps(r,indent=2));print(json.dumps(r))
