from pathlib import Path
import json,hashlib,zipfile,shutil,datetime
B=Path('o5_export0162');load=lambda n:json.load(open(B/n));n=load('NATIVE_RESULT.json');c=load('COLD_REUSE_RESULT.json');assert n['status']=='COMPLETED' and n['evidence_status']=='VERIFIED' and n['result']['outcome']=='PASS' and c['status']=='PASS' and c['pending_bytes']==0 and load('CHECKPOINT_ACK.json')['outbox']['pending_bytes']==0
sha=lambda b:hashlib.sha256(b).hexdigest();report='''INFINITY GRID REGISTERED SAVED O5 EXPORT/READER GATE0162 — 2026-10-06

PASS:COMPLETED/VERIFIED. Saved132 selected nonseed O5 carriers and2 external rank0 seeds across HET4(m5=0..5),HOM6(m5=0..6). All134 occurrence routes,682 nested O5 owner routes and169 nontrivial component routes verified. Typed E5 edge multiset432;seven prototype bindings resolve ordered resource coordinates, original typed E4 component incidence, nested typed E3 incidence and full admitted O4 source roots. Original selected-state/lane/prototype metadata, edge-only digest and full literal payload hashes preserved losslessly. Lane/rank qualifies original edge-only digest, which alone omits owner identity; no global isomorphism-label claim.

Typed E4 compatibility/capacity, saved rank/digest and component accounting pass. Missing/excluded lane/rank/digest, invalid owner indices, unavailable derivation ancestry, root/nested/component copy isolation and closed-reader checks pass. Capture and terminal checkpoint saved with exact raw readbacks. Cold restore/exact completion reuse PASS;pending bytes0;generation calls0. Historical generators and graduation audits not rerun.

Scope:Saved selected states; not full candidate census or complete parent/action occurrence lineage. Nested O4/O3 still uses external anonymous(p,u2) Q bank;76 microscopic O2 panels and bank selection provenance remain unresolved. Full L0-G8 completion remains false.
MASTER:MASTER_DATA_V1_0145/145 scientific slices unchanged; no O5 scoped admission yet.
NEXT:Saved O5 scoped admission and registered catalog/unified reader integration, preserving all145 predecessor slices and routes. Do not regenerate completed constructions.
''';(B/'REPORT.txt').write_text(report);s=json.load(open('CURRENT_STATUS.json'));s.update(status_as_of_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),next_scope='SAVED_O5_TYPED_INCIDENCE_SCOPED_ADMISSION_AND_CATALOG_INTEGRATION',next_scope_status='REGISTERED_EXPORT_READER_VERIFIED_PRESERVED_COLD_REUSED',o4_export_result='o5_export0162/NATIVE_RESULT.json',code_mirror=load('CODE_MIRROR.json'));Path('CURRENT_STATUS.json').write_text(json.dumps(s,indent=2));D=Path('handoff0162_o5_export');D.mkdir(exist_ok=True);dest=D/B;dest.mkdir(exist_ok=True)
for p in B.iterdir():
 if p.is_file() and p.suffix in ['.json','.py','.txt'] and not p.name.startswith('TO_SAVE'):shutil.copy2(p,dest/p.name)
shutil.copytree(B/'project',dest/'project',ignore=shutil.ignore_patterns('__pycache__'),dirs_exist_ok=True)
for name in ['SCIENTIFIC_EXPORT.zip','FINAL_CHECKPOINT_SLIM.zip']:shutil.copy2(B/name,dest/name)
(D/'o3_export0156').mkdir(exist_ok=True);shutil.copy2('o3_export0156/SCIENTIFIC_EXPORT.zip',D/'o3_export0156/SCIENTIFIC_EXPORT.zip')
(D/'o4_export0159').mkdir(exist_ok=True);shutil.copy2('o4_export0159/SCIENTIFIC_EXPORT.zip',D/'o4_export0159/SCIENTIFIC_EXPORT.zip')
for name,hashes in [('READBACKS.json',{r['sha256'] for r in load('PENDING.json')['pending_objects']}),('CHECKPOINT_READBACKS.json',{r['sha256'] for r in load('EXPORT.json')['dependencies']}|{load('EXPORT.json')['sha256']})]:
 m=load(name);(dest/name).write_text(json.dumps({h:m[h] for h in sorted(hashes)},indent=2))
refs={'master0145_restore':{'name':'IG_MASTER_DATA_V1_0145_O4_HANDOFF_2026-10-06.zip','sha256':'5fc9acdf7f7b4d62fc07467924d98a30d1c188cab3d5d6b5aecca4919643c7ac','drive_file_id':'1jG069nObAHMoSJHnXmGUeM9KjIuzn7fZ'},'readiness_restore':{'name':'IG_O5_SOURCE_BOUND_READINESS_HANDOFF_2026-10-06.zip','sha256':'7e7e6960d70a0c5be406ccabce9bbbc855ce44d5706ea5a93ed929849278d5c3','drive_file_id':'1IogiQ5MjxuLLx-VjfGBMLIjIjS4J9sKy'},'native_restore':'EXPORT.json and CHECKPOINT_READBACKS.json pin exact saved dependency IDs/hashes. Rebind local paths only, restore checkpoint in pinned runtime then reuse completion;do not regenerate.'};(D/'RECOVERY_DEPENDENCIES.json').write_text(json.dumps(refs,indent=2));(D/'READ_FIRST.txt').write_text(report);(D/'STATUS.json').write_text(json.dumps(s,indent=2));(D/'CONTINUATION_CURSOR.json').write_text(json.dumps({'master_release':'MASTER_DATA_V1_0145','scientific_slices':145,'completed_gate':'0162_SAVED_O5_EXPORT_READER','next_scope':s['next_scope'],'scientific_admission_issued':False,'capture_id':load('POINTER.json')['capture_id'],'completion_sha256':n['completion_sha256'],'result_sha256':n['result_sha256'],'pending_bytes':0,'generation_calls':0},indent=2));(D/'TEMPLATE_COMPLIANCE.json').write_text(json.dumps({'read_first':True,'status':True,'cursor':True,'scientific_bytes_and_code':True,'hash_manifest':True,'native_checkpoint_and_dependency_receipts':True,'lower_O4_incidence_bindings':True,'scope_limits_explicit':True,'completed_constructions_regenerated':False},indent=2));(D/'MANIFEST.json').unlink(missing_ok=True);m={str(p.relative_to(D)):{'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size} for p in D.rglob('*') if p.is_file()};(D/'MANIFEST.json').write_text(json.dumps(m,indent=2));p=Path('IG_O5_GATE_0162_VERIFIED_HANDOFF_2026-10-06.zip')
with zipfile.ZipFile(p,'w',zipfile.ZIP_DEFLATED) as z:
 for name in [*m,'MANIFEST.json']:z.write(D/name,name)
with zipfile.ZipFile(p) as z:
 for name,x in m.items():assert sha(z.read(name))==x['sha256']
Path('CURRENT_START.txt').write_text(str(D/'READ_FIRST.txt')+'\n');Path('IG_O5_GATE_0162_START_2026-10-06.txt').write_text(report+'\nBundle:'+p.name+'\nBundle SHA256:'+sha(p.read_bytes())+'\n');meta={'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size,'manifest_files':len(m)};(B/'DELIVERY_BINDINGS.json').write_text(json.dumps(meta,indent=2));print(meta)
