from pathlib import Path
import json,hashlib,shutil,ast
R=Path.cwd();B=R/'scope_reconcile0171';sha=lambda b:hashlib.sha256(b).hexdigest();load=lambda p:json.loads(p.read_bytes())
def dump(n,d):(B/n).write_text(json.dumps(d,indent=2)+'\n')
plan=R/'handoff0143_readiness/population_plan/IG_L0_TO_G8_MASTER_POPULATION_PLAN_2026-10-06.txt';shutil.copy2(plan,B/'ORIGINAL_POPULATION_PLAN.txt')
catpath=R/'o7_integrate0170/CATALOG_0148.json';cat=load(catpath);assert len(cat['slices'])==148 and sha(catpath.read_bytes())=='21e55dac42946a8949fb0cb3a5ce2bd3a5bf0c9624c734c539d754a89b3a0712';v=load(B/'RECOVERY_VALIDATION.json');search=load(B/'SOURCE_SEARCH.json')
rows=[{'family':'L0/L1 H66 foundation','status':'COMPLETE_IN_DECLARED_ADMITTED_SCOPE','scope':'66 exact primitive states,264 internal moves;50116 H66 unordered triples','gap':'Raw15625 graph/other basis conditional on exact consumer need;no automatic expansion'},
{'family':'L2 J3/case5/AB-BC','status':'COMPLETE_IN_DECLARED_ADMITTED_SCOPE','scope':'300696 permutation-labelled J3;19683 case5 objects/formations;729 AB and729 BC objects/formations','gap':'Additional lawful construction recipes remain unbound;no J3 repeat'},
{'family':'Recursive depth1/depth2','status':'COMPLETE_IN_DECLARED_ADMITTED_SCOPE','scope':'199579 exact rows','gap':'Historical weighted/L13 claims excluded'},
{'family':'NODE selected panels','status':'COMPLETE_IN_DECLARED_SAVED_SCOPE','scope':'32545 routes,134714 parents;original selected scopes','gap':'Saved scope does not assert all fresh NODE/SCOUT recipes'},
{'family':'O1 recipe mapping','status':'EXPLICIT_RECIPE_MAPPING_PENDING','scope':'Admitted foundation and mature NODE selected scopes are available','gap':'Do not equate NODE labels with every O1 recipe;pin explicit producer/identity mapping for any additional required O1 population'},
{'family':'O2 selected panels','status':'COMPLETE_IN_DECLARED_SAVED_SCOPE','scope':'26267 routes,63885 parents','gap':'76 microscopic input panels required for O3 bank reproduction remain missing'},
{'family':'O3 nested carriers','status':'COMPLETE_IN_DECLARED_SAVED_SCOPE','scope':'4867 states,6031 parents,25057 Q routes,4927 components','gap':'Anonymous local(p,u2) Q-bank and missing76 microscopic O2 panels'},
{'family':'O4','status':'COMPLETE_IN_DECLARED_SAVED_SCOPE','scope':'354 states,1802 O3 owners,442 components','gap':'No complete parent/action occurrence ancestry or full candidate census'},
{'family':'O5','status':'COMPLETE_IN_DECLARED_SAVED_SCOPE','scope':'134 states,682 O4 owners,169 components','gap':'No complete parent/action occurrence ancestry or full candidate census'},
{'family':'O6','status':'COMPLETE_IN_DECLARED_SAVED_SCOPE','scope':'134 states,682 O5 owners,172 components,133 resource bindings','gap':'No complete parent/action occurrence ancestry or full candidate census'},
{'family':'O7 admitted0148','status':'COMPLETE_IN_DECLARED_SAVED_SCOPE','scope':'74 states,322 O6 owners,82 components,HET4 rank0..5/HOM6 rank0..1','gap':'New recovered24 HOM6 rank2/3 roots and205 component records awaiting scoped export/admission;whole HOM6 rank4..6/TWIN4 root forests still missing'},
{'family':'O7 additional saved roots/components','status':'READY_FOR_SAVED_SCOPE_EXPORT_BINDING','scope':'24 new whole roots at HOM6 ranks2/3;205 literal components with512 E7 edges,HET4/HOM6/TWIN4;summary profiles only','gap':'Must define separate root/component identities;external twin roots must remain distinguished;not full Counter certification'},
{'family':'G1','status':'SOURCE_LEAD_BOUND_READINESS_NOT_ESTABLISHED','scope':'Current UpliftCampaignEngine.ensure_g1_r100_population names193-candidate R100 cohort after selected maturation to99','gap':'Uses MaterializedDiscoverySession,exact O7 material-root and rebuild_selected_states;recover saved exact G1 cohort and pin authorities/recipe before materialization. Never call ensure merely to read stored data'},
{'family':'G2','status':'EXACT_INPUT_AND_AUTHORITY_BINDING_PENDING','scope':'g2_relation finite relation semantics;uplift_r0 is reconnaissance observer','gap':'Exact G1 roots,finite declared scope,and G2 graduation/R0 authority need binding;module presence is not readiness'},
{'family':'G3-G5','status':'EXACT_INPUT_EXPORT_BINDING_PENDING','scope':'Existing current source modules provide leads','gap':'Exact G2-unit trees/fibers,graft occurrences and authority chain must resolve;public interfaces insufficient'},
{'family':'G6-G8','status':'RECIPE_AUTHORITY_FRONTIER_BINDING_PENDING','scope':'Existing adapters/historical partialfrontiers are leads','gap':'Original G7/G8 producer/finite frontier binding not established by this review;G6:S7/S8 are not G7/G8'}]
source_roles=[]
for name,role in [('regime_scanner.py','O-depth exploratory synthetic scanner;not standalone G1 admission'),('g2_relation.py','G2 exact relation-valued reservation/composition'),('uplift_r0.py','post-graduation G2 reconnaissance;not population generator'),('uplift_campaign.py','campaign materialization controller with193-candidate G1:R100 recipe lead'),('materialized_discovery.py','exact reconstruction/generation path from packaged205 O7 survivor seed;not a stored master read'),('uplift_g3_s0.py','G3 source lead'),('uplift_g4_s0.py','G4 source lead'),('uplift_g5_r1.py','G5 source lead')]:
 p=R/'engine/infinity_grid'/name;d=B/'current_source_leads'/name;d.parent.mkdir(exist_ok=True);shutil.copy2(p,d);tree=ast.parse(p.read_bytes());source_roles.append({'source':str(p.relative_to(R)),'sha256':sha(p.read_bytes()),'role':role,'top_level_functions':[n.name for n in tree.body if isinstance(n,(ast.FunctionDef,ast.ClassDef))],'executed':False})
seeds=[]
for p in sorted((R/'engine/infinity_grid/resources/decoder').glob('O7_MATERIAL_ROOT*.zip')):seeds.append({'path':str(p.relative_to(R)),'sha256':sha(p.read_bytes()),'role':'Exact seed file named by current MaterializedDiscoverySession;archive inventory checked,no runtime materialization invoked'})
dump('G_SOURCE_ROLES.json',{'sources':source_roles,'O7_material_root_seeds':seeds,'regime_scanner_phase8_seed_expected':'b28dc2c306f389a5191a9f512e6cbeeb03251e8b1234df187524f331ad3b0c9b','note':'Current materialized G1 path uses a separate compact O7 seed;do not conflate it with the older regime_scanner phase8 seed','generation_calls':0})
register={'schema':'IG_MASTER_POPULATION_PLAN_RECONCILIATION_V1','master_release':'MASTER_DATA_V1_0148','scientific_slices':148,'catalog_sha256':sha(catpath.read_bytes()),'original_plan_sha256':sha(plan.read_bytes()),'families':rows,'work_packages':{'WP1':'PARTIAL:scope/source bindings recorded;later exact recipes still pending','WP2':'ADMITTED_H66_PREFIX_REUSED;extensions conditional','WP3':'DECLARED_J3_CASE5_PAIRS_AND_RECURSIVE_SCOPES_COMPLETE;additional recipes unbound','WP4':'SAVED_NODE_SCOPES_ADMITTED;fresh recipe census not globally complete','WP5':'FINITE_SAVED_O2_O7_SCOPES_ADMITTED;additional O7 data now recoverable;not globally complete','WP6':'STATIC_SOURCE_LEADS_BOUND;population/export readiness not established','WP7':'PENDING_EXACT_INPUT_AND_EXPORT_BINDINGS','WP8':'PENDING_RECIPE_AUTHORITY_AND_FRONTIER_BINDINGS','WP9':'ONGOING_SCOPED_READER_INTEGRATION;global closure not complete'},'new_saved_data':v,'search_scope':{'unique_archives':search['unique_archives'],'chain_occurrences':search['chain_occurrences'],'candidate_hits':len(search['hits']),'errors':len(search['errors']),'bounded_filename_search':True},'generation_calls':0,'new_admissions':0,'full_l0_to_g8_complete':False,'next_scope':v['next_scope'],'next_scope_status':'SAVED_BYTES_AND_TYPED_BINDINGS_VERIFIED_EXPORT_NOT_PREPARED'};dump('FAMILY_REGISTER.json',register)
text='INFINITY GRID MASTER0148 COVERAGE/PLAN RECONCILIATION — ACTION0171 — 2026-10-06\n\nMaster0148 retained;no admission or generation. Original population plan preserved unchanged;this register records current scoped progress,not global completion.\n\n'
text+=f"Bounded source search: {search['unique_archives']} unique ZIPs/{search['chain_occurrences']} archive-chain occurrences;{len(search['hits'])} candidate hits;{len(search['errors'])} errors. Filename-directed scope is not global absence proof. Prior missing-O2 panel search was not repeated.\n\n"
text+='NEW RECOVERY:24 saved HOM6 O7 whole roots at ranks2/3 (60 E7 edges) verify against admitted O6 bindings.205 saved O7 component records (70 HET4,97 HOM6,38 TWIN4;512 E7 edges) verify binary digests,ordered parent colors,typed capacity/compatibility,accounting,and exact R7 Merkle resource hashes. Profile and survivor record arrays agree;profile source SHA matches the earlier closeout pin.87 duplicate root occurrences agree with master0148. No full Counter entries or fresh profile/graduation certification claimed. Missing whole-root forests at HOM6 ranks4..6/TWIN4 remain distinct from recovered component states.\n\n'
for row in rows:text+=row['family']+': '+row['status']+'\nScope:'+row['scope']+'\nRemaining:'+row['gap']+'\n\n'
text+='Current G1/G2 source roles pinned statically. G1 campaign ensure_g1_r100_population performs maturation/materialization and must not be used as a master read. The current exact O7 material-root seed is inventoried;recover/pin saved G1 populations before considering new generation. No module executed.\n\nNEXT:'+v['next_scope']+'. Prepare separate source-bound root/component export scopes and exact O6/twin bindings;retain profile summaries as external evidence. Recover later authority bytes without assuming archive titles confer admission. Do not regenerate completed constructions.\n';(B/'REPORT.txt').write_text(text);print(json.dumps({'master':'0148','families':len(rows),'new_root_states':v['new_root_states'],'component_records':v['survivor_component_records'],'next_scope':v['next_scope']}))
