from pathlib import Path
import json,hashlib,shutil,datetime
B=Path(__file__).resolve().parent;R=B.parent;E=R/'o2_export0151';sha=lambda b:hashlib.sha256(b).hexdigest();load=lambda p:json.load(open(p));n=load(E/'NATIVE_RESULT.json');cold=load(E/'COLD_REUSE_RESULT.json');ack=load(E/'CHECKPOINT_ACK.json');r=n['result'];assert n['status']=='COMPLETED' and n['evidence_status']=='VERIFIED' and r['outcome']=='PASS' and cold['reused'] and cold['completion_sha256']==n['completion_sha256'] and cold['result_sha256']==n['result_sha256'] and ack['outbox']['pending_bytes']==0
assert r['carriers']==25474 and r['seed_carriers']==793 and r['all_occurrence_routes_checked']==26267 and r['all_parent_routes_checked']==r['parent_links']==63885
oldp=R/'node_integrate0149/CATALOG_0142.json';old=load(oldp);oldsha=sha(oldp.read_bytes());assert oldsha=='b8d63919fe8177d2b0da26a107a2b45f902f1e1a19e4f968c5b1ae126f976f44'
ad={'schema_id':'IG_MASTER_SCOPED_DATA_ADMISSION_V1','decision':'ACCEPTED_FOR_CANONICAL_REUSE_WITHIN_DECLARED_O2_SELECTED_CARRIER_SCOPE','authority':'EXTERNAL_OPERATOR_DECISION_UNDER_USER_AUTHORIZED_MASTER_CAMPAIGN','admitted_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'dataset_id':'O2_SAVED_SELECTED_CARRIERS_D78_D109_WITH_EXTERNAL_D77_SEED_V1','scientific_root_sha256':r['scientific_root_sha256'],'scientific_archive_sha256':r['archive_sha256'],'predecessor_catalog_sha256':oldsha,'scope':{'depths':[78,109],'external_seed_depth':77,'population':'Immutable saved selected typed carriers; not full candidate census'},'counts':{k:r[k] for k in ['carriers','seed_carriers','parent_links','observer_sidecars','all_occurrence_routes_checked','all_parent_routes_checked']},'identity':'FROZEN_EXACT_KEY_AND_ROLE_HASH; DEPTH_QUALIFIED_OCCURRENCE; FULL16_COUNTERS_TYPED_EDGES_AND_ORIGINAL_METADATA','native_capture_id':ack['capture_id'],'native_completion_sha256':n['completion_sha256'],'native_result_sha256':n['result_sha256'],'cold_reuse':True,'pending_bytes':0,'generator_calls':0,'historical_audit_reexecuted':False,'not_covered':['Full O2 census','d77 and earlier derivation provenance','Fresh O2 science/graduation authority','Unique microscopic occurrence lineage','Geometry/actualization','Full L0-to-G8 completion'],'evidence':[]}
for p in [E/'NATIVE_RESULT.json',E/'COLD_REUSE_RESULT.json',E/'CHECKPOINT_ACK.json',R/'inter_node0150/EXPORT_CONTRACT.json',R/'inter_node0150/READINESS_VALIDATION.json']:
 ad['evidence'].append({'file_name':str(p.relative_to(R)),'sha256':sha(p.read_bytes())})
p=B/'SCOPED_ADMISSION.json'
if p.exists():ad=load(p)
else:p.write_text(json.dumps(ad,indent=2))
cat=json.loads(json.dumps(old));cat.update(release_id='MASTER_DATA_V1_0143',previous_release_id='MASTER_DATA_V1_0142',previous_catalog_sha256=oldsha);a=load(E/'READBACKS.json')[r['archive_sha256']];cat['slices'].append({'dataset_id':ad['dataset_id'],'scientific_root_sha256':r['scientific_root_sha256'],'format':'IG_O2_SELECTED_CARRIERS_EXPORT_V1','identity_profile':ad['identity'],'scope':ad['scope'],'counts':ad['counts'],'scoped_admission_sha256':sha(p.read_bytes()),'scientific_dependencies':[{'role':'ADMITTED_NODE_INPUT_BINDINGS','catalog_sha256':oldsha,'readiness_sha256':sha((R/'inter_node0150/READINESS_VALIDATION.json').read_bytes())},{'role':'EXTERNAL_D77_SELECTED_SEED','panel_sha256':load(R/'inter_node0150/EXPORT_CONTRACT.json')['checkpoint_refs'][0]['sha256'],'records':793}],'archive':{'file_name':'IG_O2_SELECTED_CARRIER_SCIENTIFIC_EXPORT_2026-10-06.zip','sha256':r['archive_sha256'],'size_bytes':(E/'SCIENTIFIC_EXPORT.zip').stat().st_size,'drive_file_id':a['id'],'drive_folder_id':'1ALFgcEwVXK7r4yzkP1tJQsOMUPilsAzZ'}});cat['coverage_summary']['o2_selected_carriers']=ad['counts'];(B/'CATALOG_0143.json').write_text(json.dumps(cat,indent=2)+'\n')
shutil.copytree(R/'node_integrate0149/project',B/'project/previous_node',dirs_exist_ok=True)
for name in ['reader.py','frozen_in9.py']:shutil.copy2(E/'project'/name,B/'project'/name)
(B/'project/__init__.py').write_text('');bindings={'CATALOG_SHA256':sha((B/'CATALOG_0143.json').read_bytes()),'PREVIOUS_SHA256':oldsha,'ADMISSION_SHA256':sha(p.read_bytes())};(B/'project/bindings.py').write_text('\n'.join(k+'='+repr(v) for k,v in bindings.items())+'\n')
manifest={str(p.relative_to(B/'project/previous_node')):sha(p.read_bytes()) for p in (B/'project/previous_node').rglob('*.py')};(B/'PREDECESSOR_SOURCE_HASHES.json').write_text(json.dumps(manifest,indent=2))
for name,h in manifest.items():assert sha((R/'node_integrate0149/project'/name).read_bytes())==h
s=load(R/'node_integrate0149/SPEC.json');s.update(job_id='MASTER.O2.SELECTED.CARRIERS.CATALOG.INTEGRATION.V1',project_source=str(B/'project'));s['question'].update(stage_id='MASTER:O2:SELECTED:CARRIERS:CATALOG:INTEGRATION:V1',description='Scoped-admitted O2 selected carriers integrate into0143; preserve142 predecessor slices/readers',stopping_rule='All O2 occurrences and parent routes; all saved NODE routes; unchanged142 predecessor slices and reader bytes. Stop first mismatch; no generation.');s['execution']['parameters']={};s['inputs']=[x for x in s['inputs'] if x['logical_name'] not in ['new_catalog','predecessor_sources']]
for name,p in [('new_catalog',B/'CATALOG_0143.json'),('o2_admission',B/'SCOPED_ADMISSION.json'),('o2_archive',E/'SCIENTIFIC_EXPORT.zip'),('catalog0142',oldp),('predecessor_sources',B/'PREDECESSOR_SOURCE_HASHES.json')]:s['inputs'].append({'logical_name':name,'path':str(p),'sha256':sha(p.read_bytes())})
s['output_contract']['result_checks']=[{'pointer':'/'+k,'equals':v} for k,v in {'outcome':'PASS','all_o2_routes_checked':26267,'all_o2_parent_routes_checked':63885,'all_node_routes_checked':32545,'all_node_parent_routes_checked':134714,'prior_slices_unchanged':142,'prior_reader_bytes_unchanged':True,'generation_calls':0}.items()];(B/'SPEC.json').write_text(json.dumps(s,indent=2))
for name in ['operate.py','cold_ops.py']:shutil.copy2(E/name,B/name)
print(bindings)
