from pathlib import Path
import json,hashlib,zipfile,shutil,datetime
R=Path.cwd();B=R/'o7_additional_integrate0174';sha=lambda b:hashlib.sha256(b).hexdigest();load=lambda n:json.loads((B/n).read_bytes())
def dump(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
n=load('NATIVE_RESULT.json');c=load('COLD_REUSE_RESULT.json');ack=load('CHECKPOINT_ACK.json')
assert n['status']=='COMPLETED' and n['execution_status']=='FINISHED' and n['evidence_status']=='VERIFIED' and n['result']['outcome']=='PASS' and c['reused'] and c['pending_bytes']==0 and ack['outbox']['pending_bytes']==0
r=n['result'];expected={'all_additional_o7_root_routes_checked':24,'all_additional_o7_component_occurrence_routes_checked':205,'all_additional_o7_object_routes_checked':164,'all_additional_o7_owner_routes_checked':677,'all_o7_routes_checked':74,'all_o7_owner_routes_checked':322,'all_o7_component_routes_checked':82,'all_o6_routes_checked':134,'all_o6_owner_routes_checked':682,'all_o6_component_routes_checked':172,'all_o5_routes_checked':134,'all_o5_owner_routes_checked':682,'all_o5_component_routes_checked':169,'all_o4_routes_checked':354,'all_o4_owner_routes_checked':1802,'all_o4_component_routes_checked':442,'all_o3_routes_checked':4867,'all_o3_parent_routes_checked':6031,'all_nested_Q_routes_checked':25057,'all_o3_component_routes_checked':4927,'all_o2_routes_checked':26267,'all_o2_parent_routes_checked':63885,'all_node_routes_checked':32545,'all_node_parent_routes_checked':134714,'all_pair_routes_checked':1458,'prior_slices_unchanged':148}
for k,v in expected.items():assert r[k]==v
cat=load('CATALOG_0149.json');prev=json.loads((R/'o7_integrate0170/CATALOG_0148.json').read_bytes());assert cat['slices'][:-1]==prev['slices'] and len(cat['slices'])==149
verification={'schema':'IG_ADDITIONAL_SAVED_O7_INTEGRATION_RELEASE_V1','release_id':'MASTER_DATA_V1_0149','catalog_sha256':sha((B/'CATALOG_0149.json').read_bytes()),'admission_sha256':sha((B/'SCOPED_ADMISSION.json').read_bytes()),'scientific_slices':149,'status':'VERIFIED_PRESERVED_COLD_REUSED','counts':dict(expected,prior_reader_modules_checked=r['prior_reader_modules_checked']),'total_saved_whole_O7_roots':98,'literal_root_component_occurrences_added':r['o7_new_literal_root_component_occurrences'],'prior_reader_bytes_unchanged':True,'native_completion_sha256':n['completion_sha256'],'native_result_sha256':n['result_sha256'],'pending_bytes':0,'generation_calls':0,'o7_graduated':False,'automatic_o8_authorized':False,'full_l0_to_g8_complete':False};dump(B/'RELEASE_VERIFICATION.json',verification)
report='INFINITY GRID MASTER_DATA_V1_0149 ADDITIONAL SAVED O7 SCOPED ADMISSION/INTEGRATION — 2026-10-07\n\nRelease0149,149 scientific slices.24 additional saved whole HOM6 roots at ranks2 and3,60 E7 edges,144 O6 owner occurrences.98 total saved whole O7 roots including2 external rank0 seeds.205 saved component occurrences retain164 distinct exact contextual objects,512 edge occurrences,533 O6 owner occurrences. Four admitted O6 prototype bindings plus two external adversarial O6 twins with admitted O5 bindings. TWIN4 component occurrences are admitted in their exact saved owner contexts; absent TWIN4 whole forests are not admitted or synthesized.\n\nRegistered gate0174 COMPLETED/FINISHED/VERIFIED. All24 new root/205 component/164 object/677 owner routes checked against master bindings. All predecessor O7/O6/O5/O4/O3/O2/NODE/pair routes and recursive depth1/2 samples pass.148 predecessor catalog slices and reader module bytes unchanged. Deterministic components of24 literal whole roots are exposed separately from original saved component profile occurrences; no source-owner mapping is invented.\n\nCapture and terminal checkpoint byte readbacks verified. Cold restore/exact completion reuse PASS,pending0,generation0. Restored CPython3.13.5/SQLite3.51.3 verified after transient workspace loss. No original generator main or canonicalization search executed. Saved profile summaries are source evidence only; full Counter/fresh profile certification,68 source whole-root references,complete action ancestry,original source-owner mapping,76 microscopic O2 panels and historical graduation authority remain unresolved. No O7 graduation or automatic O8. Full L0-G8 completion false.\n\nNEXT: reconcile additional admitted O7 scope with WP5 register and prepare WP6 G1/G2 current-producer/admitted-component-root readiness. Do not regenerate completed constructions.\n'
(B/'REPORT.txt').write_text(report)
s=json.loads((R/'CURRENT_STATUS.json').read_bytes());s.update(status_as_of_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),latest_committed_release='MASTER_DATA_V1_0149',scientific_slices=149,catalog_sha256=verification['catalog_sha256'],catalog_path='o7_additional_integrate0174/CATALOG_0149.json',in_flight_active='NONE',pending_bytes=0,generator_calls=0,next_scope='WP5_ADDITIONAL_O7_SCOPE_RECONCILIATION_AND_WP6_G1_G2_READINESS',next_scope_status='NOT_PREPARED',additional_O7_integration_result='o7_additional_integrate0174/NATIVE_RESULT.json',admitted_additional_O7_roots_and_components=cat['slices'][-1]['counts'],code_mirror=load('CODE_MIRROR.json'));dump(R/'CURRENT_STATUS.json',s)
D=R/'handoff0149_o7_additional';D.mkdir(exist_ok=True);dest=D/B.name;dest.mkdir(exist_ok=True)
for p in B.iterdir():
 if p.is_file() and p.suffix in ['.json','.py','.txt'] and not p.name.startswith('TO_SAVE') and p.name not in ['SAVE_RECEIPT.json','DELIVERY_BINDINGS.json','FRESH_UNPACK_VERIFICATION.json']:shutil.copy2(p,dest/p.name)
shutil.copytree(B/'project',dest/'project',ignore=shutil.ignore_patterns('__pycache__'),dirs_exist_ok=True);shutil.copy2(B/'FINAL_CHECKPOINT_SLIM.zip',dest/'FINAL_CHECKPOINT_SLIM.zip')
for folder in ['o7_additional_export0173','o7_export0169','o6_export0165','o5_export0162','o4_export0159','o3_export0156']:
 t=D/folder;t.mkdir(exist_ok=True);shutil.copy2(R/folder/'SCIENTIFIC_EXPORT.zip',t/'SCIENTIFIC_EXPORT.zip')
t=D/'o7_integrate0170';t.mkdir(exist_ok=True);shutil.copy2(R/'o7_integrate0170/CATALOG_0148.json',t/'CATALOG_0148.json')
# Include every small catalog/admission and pinned runtime metadata input so
# future work need not retrieve the entire chain of predecessor handoffs.
inputs=dest/'inputs';inputs.mkdir(exist_ok=True);rebind={};sci={'scientific_part0','scientific_part1','parent_archive','pair_archive','node_archive','o2_archive','o3_archive','o4_archive','o5_archive','o6_archive','o7_archive','additional_archive'}
for x in load('SPEC.json')['inputs']+load('SPEC.json')['environment']['artifacts']:
 if x['logical_name'] not in sci:
  target=inputs/(x['logical_name']+'.bin');shutil.copy2(x['path'],target);rebind[x['logical_name']]={'relative_path':str(target.relative_to(D)),'sha256':x['sha256']}
dump(dest/'COMPACT_INPUT_REBINDINGS.json',rebind)
for name,hs in [('READBACKS.json',{x['sha256'] for x in load('PENDING.json')['pending_objects']}),('CHECKPOINT_READBACKS.json',{x['sha256'] for x in load('EXPORT.json')['dependencies']})]:
 mapping=load(name);dump(dest/name,{h:mapping[h] for h in sorted(hs)})
dump(D/'RECOVERY_DEPENDENCIES.json',{'master148':{'drive_file_id':'1pRZIf4KuJzajRIaruSGCUSxHXdmikNQA','sha256':'9269ae6ed7563a83e9beb59e918bd65c7e8a062d2100a5c73202e10d8e55b9f3'},'verified_export173':{'drive_file_id':'144Ndgi4TQfXjdIW03keA4MyI1yYHl1GT','sha256':'33d46578540a738bb65235373395e6a11e7a4a44183038452fa88f0a0f688085'},'plan_register171':{'drive_file_id':'1XDVS8ZQPTRAbyH-nohOVVeG308WOM2DQ','sha256':'fd8ffe43bc169ff7c697b24f94c19f11d8cebadec9ee1f173d00cd374c53468d'},'runtime':'six exact saved transfer parts pinned in RUNTIME_RECOVERY_TRANSPORT.json; bootstrap only,older science cursors superseded','native_restore':'Native EXPORT.json/CHECKPOINT_READBACKS.json pin exact saved dependency IDs/hashes. Rebind local paths only;restore checkpoint then reuse exact completion. Never regenerate.','compact_metadata':'COMPACT_INPUT_REBINDINGS.json includes predecessor catalogs/admissions/runtime metadata. Earlier large science is pinned in saved input readbacks,not copied.'})
shutil.copy2(R/'runtime/IG_DATA_NEW_CHAT_HANDOFF_TRANSPORT_2026-10-02.json',D/'RUNTIME_RECOVERY_TRANSPORT.json')
dump(D/'STATUS.json',s);(D/'READ_FIRST.txt').write_text(report+'\nVerify MANIFEST.json,then run pinned Python o7_additional_integrate0174/verify_saved.py BUNDLE.zip for standalone new-scope/catalog checks. Full predecessor route regression already passed in the sealed native result.\n');dump(D/'CONTINUATION_CURSOR.json',{'master_release':'MASTER_DATA_V1_0149','scientific_slices':149,'completed_gate':'0174_ADDITIONAL_O7_SCOPED_ADMISSION_AND_CATALOG_INTEGRATION','next_scope':s['next_scope'],'next_job_captured':False,'pending_bytes':0,'generation_calls':0})
(D/'MANIFEST.json').unlink(missing_ok=True);mh={str(p.relative_to(D)):{'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size} for p in D.rglob('*') if p.is_file()};dump(D/'MANIFEST.json',mh)
p=R/'IG_MASTER_DATA_V1_0149_ADDITIONAL_O7_HANDOFF_2026-10-07.zip'
with zipfile.ZipFile(p,'w',zipfile.ZIP_DEFLATED) as z:
 for name in sorted([*mh,'MANIFEST.json']):z.write(D/name,name)
with zipfile.ZipFile(p) as z:
 for name,x in mh.items():assert sha(z.read(name))==x['sha256']
meta={'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size,'manifest_files':len(mh)};dump(B/'DELIVERY_BINDINGS.json',meta)
(R/'IG_MASTER_DATA_V1_0149_ADDITIONAL_O7_START_2026-10-07.txt').write_text(report+'\nBundle:'+p.name+'\nBundle SHA256:'+meta['sha256']+'\n');(R/'CURRENT_START.txt').write_text('handoff0149_o7_additional/READ_FIRST.txt\n');print(json.dumps(meta))
