from pathlib import Path
import json,hashlib,datetime
B=Path(__file__).resolve().parent;R=B.parent;E=R/'o7_additional_export0173';sha=lambda b:hashlib.sha256(b).hexdigest();load=lambda p:json.loads(p.read_bytes())
n=load(E/'NATIVE_RESULT.json');cold=load(E/'COLD_REUSE_RESULT.json');ack=load(E/'CHECKPOINT_ACK.json');r=n['result']
assert n['status']=='COMPLETED' and n['evidence_status']=='VERIFIED' and r['outcome']=='PASS' and cold['reused'] and cold['completion_sha256']==n['completion_sha256'] and cold['result_sha256']==n['result_sha256'] and ack['outbox']['pending_bytes']==0
oldp=R/'o7_integrate0170/CATALOG_0148.json';old=load(oldp);oldsha=sha(oldp.read_bytes());assert oldsha=='21e55dac42946a8949fb0cb3a5ce2bd3a5bf0c9624c734c539d754a89b3a0712'
ad={'schema_id':'IG_MASTER_SCOPED_DATA_ADMISSION_V1','decision':'ACCEPTED_FOR_REUSE_WITHIN_ADDITIONAL_SAVED_O7_ROOT_AND_EXACT_CONTEXTUAL_COMPONENT_SCOPE','authority':'EXTERNAL_OPERATOR_DECISION_UNDER_USER_AUTHORIZED_MASTER_CAMPAIGN','admitted_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'dataset_id':'O7_ADDITIONAL_SAVED_HOM6_ROOTS_2_3_AND_COMPONENT_OCCURRENCES_V1','scientific_root_sha256':r['scientific_root_sha256'],'scientific_archive_sha256':r['archive_sha256'],'predecessor_catalog_sha256':oldsha,'counts':{k:r[k] for k in ['additional_whole_roots','additional_root_E7_edges','additional_root_O6_owner_occurrences','component_occurrences','distinct_exact_component_objects','component_E7_edge_occurrences','component_O6_owner_occurrences','distinct_source_root_references','available_source_root_references','unavailable_source_root_references','used_admitted_O6_prototype_bindings','used_external_O6_twin_bindings']},'scope':{'whole_roots':{'HOM6':[2,3],'records':24},'component_occurrences':{'HET4':70,'HOM6':97,'TWIN4':38},'external_O6_twins':'source_bound_external_adversarial_roots_not_admitted_O6_roots','source_whole_root_references':'96 available;68 external unavailable; no absent forests synthesized','profile_summaries':'source_evidence_only_full_Counter_unavailable','source_owner_index_mapping_available':False,'complete_derivation_lineage':False,'microscopic_O2_panels_missing':76},'identity':'ROOT_LANE_RANK_E7_DIGEST_PLUS_ORDERED_PARENT_CONTEXT_AND_LITERAL_HASH;COMPONENT_ORDERED_EXACT_PARENT_IDS_COLORS_E7_DIGEST_PLUS_PHYSICAL_PAYLOAD_HASH;205_OCCURRENCE_KEYS_RETAINED','native_capture_id':ack['capture_id'],'native_completion_sha256':n['completion_sha256'],'native_result_sha256':n['result_sha256'],'cold_reuse':True,'pending_bytes':0,'generator_calls':0,'o7_graduated':False,'automatic_o8_authorized':False,'not_covered':['absent whole HOM6 ranks4..6/TWIN4 forests','full direct Counter or fresh profile certification','complete action lineage or original source-owner mapping','global canonicality','historical graduation authority','microscopic O2 closure','geometry/full L0-G8 completion']}
p=B/'SCOPED_ADMISSION.json'
if p.exists():ad=load(p)
else:p.write_text(json.dumps(ad,indent=2)+'\n')
cat=json.loads(json.dumps(old));cat.update(release_id='MASTER_DATA_V1_0149',previous_release_id='MASTER_DATA_V1_0148',previous_catalog_sha256=oldsha);saved=load(E/'READBACKS.json')[r['archive_sha256']]
cat['slices'].append({'dataset_id':ad['dataset_id'],'scientific_root_sha256':r['scientific_root_sha256'],'format':'IG_ADDITIONAL_SAVED_O7_EXPORT_V1','identity_profile':ad['identity'],'scope':ad['scope'],'counts':ad['counts'],'scoped_admission_sha256':sha(p.read_bytes()),'scientific_dependencies':[{'role':'ADMITTED_O7_PREDECESSOR_AND_O6_COMPONENT_BINDINGS','catalog_sha256':oldsha,'scientific_root_sha256':old['slices'][-1]['scientific_root_sha256']},{'role':'EXTERNAL_ADVERSARIAL_O6_TWIN_ROOTS_WITH_ADMITTED_O5_BINDINGS','records':2,'O6_root_admission':False}],'archive':{'file_name':'IG_ADDITIONAL_SAVED_O7_SCIENTIFIC_EXPORT_2026-10-07.zip','sha256':r['archive_sha256'],'size_bytes':(E/'SCIENTIFIC_EXPORT.zip').stat().st_size,'drive_file_id':saved['id'],'drive_folder_id':'1ALFgcEwVXK7r4yzkP1tJQsOMUPilsAzZ'}})
cat['coverage_summary'].update(o7_additional_saved_roots_and_components=ad['counts'],o7_complete_derivation_lineage=False,o7_graduated=False)
(B/'CATALOG_0149.json').write_text(json.dumps(cat,indent=2)+'\n');pins={'CATALOG_SHA256':sha((B/'CATALOG_0149.json').read_bytes()),'PREVIOUS_SHA256':oldsha,'ADMISSION_SHA256':sha(p.read_bytes())};(B/'project/bindings.py').write_text('\n'.join(k+'='+repr(v) for k,v in pins.items())+'\n')
mh={str(p.relative_to(B/'project/previous_o7')):sha(p.read_bytes()) for p in (B/'project/previous_o7').rglob('*.py')}
for n,h in mh.items():assert sha((R/'o7_integrate0170/project'/n).read_bytes())==h
(B/'PREDECESSOR_SOURCE_HASHES.json').write_text(json.dumps(mh,indent=2)+'\n')
s=load(R/'recovery0174/REBOUND_PRIOR_SPEC.json');s.update(job_id='MASTER.O7.ADDITIONAL.SAVED.ROOT.COMPONENT.CATALOG.INTEGRATION.V1',project_source=str(B/'project'));s['question'].update(stage_id='MASTER:O7:ADDITIONAL:SAVED:ROOT:COMPONENT:CATALOG:INTEGRATION:V1',description='Additional saved O7 exact contextual scope integrates into0149;preserve all148 predecessor slices/routes',stopping_rule='Stop first unexplained identity,binding,typed incidence,route or predecessor byte mismatch;no generation')
s['inputs']=[x for x in s['inputs'] if x['logical_name'] not in ['new_catalog','predecessor_sources']]
for name,p in [('new_catalog',B/'CATALOG_0149.json'),('additional_admission',B/'SCOPED_ADMISSION.json'),('additional_archive',E/'SCIENTIFIC_EXPORT.zip'),('catalog0148',oldp),('predecessor_sources',B/'PREDECESSOR_SOURCE_HASHES.json'),('prior_o7_sources',R/'o7_integrate0170/PREDECESSOR_SOURCE_HASHES.json')]:s['inputs'].append({'logical_name':name,'path':str(p),'sha256':sha(p.read_bytes())})
checks={x['pointer']:x['equals'] for x in s['output_contract']['result_checks']};checks.update({'/all_additional_o7_root_routes_checked':24,'/all_additional_o7_component_occurrence_routes_checked':205,'/all_additional_o7_object_routes_checked':164,'/all_additional_o7_owner_routes_checked':677,'/prior_slices_unchanged':148,'/scientific_slices':149,'/release_id':'MASTER_DATA_V1_0149'})
s['output_contract']['result_checks']=[{'pointer':k,'equals':v} for k,v in checks.items()];(B/'SPEC.json').write_text(json.dumps(s,indent=2)+'\n');print(json.dumps(pins))
