from pathlib import Path
import json,hashlib,zipfile,shutil,datetime
B=Path('o3_readiness0153');v=json.load(open(B/'READINESS_VALIDATION.json'));assert v['status']=='BLOCKED_MISSING_EXACT_PARENT_PANELS';sha=lambda b:hashlib.sha256(b).hexdigest();D=Path('handoff0153_o3_readiness');D.mkdir(exist_ok=True);dest=D/B;dest.mkdir(exist_ok=True)
for n in ['validate.py','READINESS_VALIDATION.json','AVAILABLE_Q_WITNESSES.json','SOURCE_MANIFEST.json','package.py','CODE_MIRROR.json']:shutil.copy2(B/n,dest/n)
L=B/'sources/Infinity_Grid_SCOUT3_V1_0_FROZEN_LAUNCH_BUNDLE_2026-08-27';shutil.copytree(L,dest/'frozen_o3_launch',dirs_exist_ok=True);G=B/'sources/Infinity_Grid_SCOUT2B_V1_9_O2_GRADUATION_AUDIT_BUNDLE_2026-08-27';shutil.copytree(G,dest/'graduation_source',dirs_exist_ok=True)
P=dest/'bound_panels';P.mkdir(exist_ok=True);panels=[]
for ref in v['panel_refs']:
 p=B/ref['path'];target=P/p.name;shutil.copy2(p,target);panels.append({'k':ref['k'],'path':str(target.relative_to(D)),'sha256':ref['sha256'],'bytes':ref['bytes'],'original_source_path':ref['path']})
source_refs={'schema':'IG_O3_READINESS_RECOVERY_DEPENDENCIES_V1','master_handoff':{'name':'IG_MASTER_DATA_V1_0143_O2_HANDOFF_2026-10-06.zip','sha256':'625133b8b4cadbcf2df083d4930fe4b7762dba3dedb4644e925c0096316effcb','drive_file_id':'15pHttKvMJmR7NjqRK1Ji-zEVwMBG4FtY','bytes':31174244},'original_archive_sources':[{'name':'Infinity_Grid_SCOUT2B_V1_2_K128_AUDIT_BUNDLE_2026-08-27.zip','library_file_id':'libfile_e85b4a040720819185bd7b047e2ee606','sha256':'9b34c78a479a03b28eaabdd4e16f2106eddab28aa7f8f5fd323053d817b8fd5e'},{'name':'Infinity_Grid_SCOUT2B_V1_5_RESULT_BUNDLE_2026-08-27.zip','library_file_id':'libfile_afbaa2bd74348191b4be37ea50ef6431','sha256':'28fcc47308e363591b540dfebe43e60b4578da5f62df8d4da006191f93cf6a5d'},{'name':'Infinity_Grid_SCOUT2B_V1_9_O2_GRADUATION_AUDIT_BUNDLE_2026-08-27.zip','library_file_id':'libfile_537f920b62408191ae1dfaeb60b17801','sha256':'2334aba55e081ef840e23336f9892c795a7e22a1bc34f3013a04568d015b0435'}],'current_panel_payloads':panels,'missing_exact_panel_bytes':v['missing_k'],'original_full_validation_script':'o3_readiness0153/validate.py requires original archive recovery paths and master0143 dependencies; current compact verify_saved.py validates included recovery bytes','generator_calls':0};(dest/'RECOVERY_DEPENDENCIES.json').write_text(json.dumps(source_refs,indent=2))
report='INFINITY GRID O2-TO-O3 SOURCE-BOUND READINESS — 2026-10-06\n\nRECOVERED:Frozen O3 launch, original O2 graduation record/independent audit bundle, saved256-state Q source bank and128 O3 seed records. All payload science hashes and internal fields verified. Graduation science d138de3c6c906be3ab453c225ecce2e3fff5d3e4f91d220ed681ef5253a86bbb matches original authority byte-for-byte; no fresh graduation replay/certification claimed. Shared NODE primitive/spec bytes match admitted inputs.\nPASS:53 of129 original Scout2-B k panels match frozen source hashes;46948 carrier occurrences have exact identities/roles/capacity/typed-edge/size checks PASS. k0 has801 exact states/edges/roles identical to admitted d109, with source-declared metadata reset.71058 available adjacent parent links resolve;4632 parent links cross unavailable panel gaps.156/256 bank Q entries have available exact carrier witnesses.\nBLOCKED:76 exact panels missing from recovered sources: k18-31,k33-63,k65-95. Original full129-panel source-bank selection cannot be independently reproduced from available bytes. Saved bank and observer results do not replace exact missing carriers. No regeneration attempted.\nMASTER:MASTER_DATA_V1_0143,143 scientific slices unchanged; no new admission/job/generation.\nNEXT:Recover exact missing k panels by their129 frozen SHA256 references, or locate a saved complete Scout2-B run. Resume only missing recovery; do not recalculate completed constructions.\n'
(B/'REPORT.txt').write_text(report);(D/'READ_FIRST.txt').write_text(report+'\nCOMPACT RECOVERY:Verify MANIFEST.json and run verify_saved.py. Included:53 unique exact panels, frozen launch/code/inputs, independent graduation source, validation receipts/witness map. To restore full master, fetch exact0143 bundle from RECOVERY_DEPENDENCIES.json and verify its manifest; both bundles share current authoritative STATUS/cursor here. Full original archive manifest checks are recorded in READINESS_VALIDATION.json; recover original archives before rerunning validate.py.\n');s=json.load(open('CURRENT_STATUS.json'));s.update(status_as_of_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),next_scope=v['next'],next_scope_status=v['status'],o3_readiness='o3_readiness0153/READINESS_VALIDATION.json',o3_missing_panel_count=len(v['missing_k']),code_mirror=json.load(open(B/'CODE_MIRROR.json')));Path('CURRENT_STATUS.json').write_text(json.dumps(s,indent=2));(D/'STATUS.json').write_text(json.dumps(s,indent=2));(D/'CONTINUATION_CURSOR.json').write_text(json.dumps({'master_release':'MASTER_DATA_V1_0143','scientific_slices':143,'completed_action':'0153_O2_TO_O3_SOURCE_BOUND_RECOVERY_AND_PARTIAL_VALIDATION','next_scope':v['next'],'blocked_on_exact_missing_k':v['missing_k'],'next_job_captured':False,'generator_calls':0,'pending_bytes':0},indent=2));(D/'TEMPLATE_COMPLIANCE.json').write_text(json.dumps({'read_first':True,'status':True,'cursor':True,'source_bytes':'53 unique panels/frozen launch/independent graduation audit','original_source_and_master_recovery_refs':True,'manifest':True,'validation_receipts':True,'next_steps':True,'partial_readiness_explicit':True},indent=2))
shutil.copy2(B/'verify_saved.py',D/'verify_saved.py');(D/'MANIFEST.json').unlink(missing_ok=True);m={str(p.relative_to(D)):{'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size} for p in D.rglob('*') if p.is_file()};(D/'MANIFEST.json').write_text(json.dumps(m,indent=2));zpath=Path('IG_O2_O3_READINESS_RECOVERY_HANDOFF_2026-10-06.zip')
with zipfile.ZipFile(zpath,'w',zipfile.ZIP_DEFLATED) as z:
 for p in D.rglob('*'):
  if p.is_file():z.write(p,str(p.relative_to(D)))
with zipfile.ZipFile(zpath) as z:
 for n,x in m.items():assert sha(z.read(n))==x['sha256']
Path('CURRENT_START.txt').write_text('handoff0153_o3_readiness/READ_FIRST.txt\n');Path('IG_O2_O3_READINESS_RECOVERY_START_2026-10-06.txt').write_text(report+'\nBundle:'+zpath.name+'\nBundle SHA256:'+sha(zpath.read_bytes())+'\n');meta={'sha256':sha(zpath.read_bytes()),'bytes':zpath.stat().st_size,'manifest_files':len(m)};(B/'DELIVERY_BINDINGS.json').write_text(json.dumps(meta));print(meta)
