"""Preserve the read-only saved-source review and exact recovery references."""
from pathlib import Path
import json,hashlib,zipfile,datetime
B=Path(__file__).resolve().parent;W=B.parent
def sha(p):
    with p.open('rb') as f:return hashlib.file_digest(f,'sha256').hexdigest()
def main():
    r=json.loads((B/'REVIEW.json').read_text());a=json.loads((B/'AUDIT.json').read_text());pre=json.loads((B/'PREREGISTRATION.json').read_text())
    assert r['status']=='PASS_FULL_SAVED_G2_SOURCE_BINDING_REVIEW' and a['status']=='PASS_INDEPENDENT_STREAM_PIN_AND_SCOPE_AUDIT'
    assert sha(B/'REVIEW.json')==a['review_sha256']
    for n,h in pre['registered_scripts'].items():assert sha(B/n)==h
    report=W/'IG_MASTER152_G2_SAVED_SOURCE_BINDING_REVIEW0234_2026-10-09.txt'
    report.write_text('Checkpoint 0234: full saved G2 source binding review passed.\n\nMaster: 152. New admissions: 0. Generation: 0. New DAG decoding: 0. G2 promotion: false. Historical V1 replay depth remains 100.\n\nAll 580,351 saved repaired pair records and all 580,351 paired stored audits were streamed from exact recovered original bytes. Their compressed and uncompressed hashes match the admitted index manifest. Every left/right carrier reference joins the admitted 193-carrier historical G1 cohort. All 1,160,702 interface references and all 1,160,702 stored D4 continuation references match the pinned historical observations. The 1,351 continuation rows cover the 193 G1 references. No source authorities or recorded status fields were rewritten.\n\nThe exact census covers 18,721 unordered pairs including self-pairs and 31 bridge operators per pair, with no duplicate pair/operator key. It reproduces 576,785 outcome classes, 3,554 collision classes, maximum size 3 and zero stored observer splits.\n\nThe G2 stored producer-source authority and G1 historical authority remain distinct and explicitly retained. The record rows still contain their original D4_PLUS_Q2_CANDIDATE_PENDING_FULL_580351_CONGRUENCE_REAUDIT status strings. Matching stored references does not authenticate current-engine scientific realization or supply omitted Q2 payloads and reservation witnesses. The prior G2 saved-scope slice remains unchanged.\n\nThis is a preregistered read-only source-reference review, not a native construction or new admission task. An independent pin/scope audit rechecked the stored transport identities, manifest hashes, census algebra, admitted source binding and scope limits. No second row-level replay or new cold-native science qualification is claimed.\n\nThe 254 MB SQLite index was not restored; the 140 MB compressed original record/audit streams were sufficient. Two incomplete transport chunks were rejected by byte checks and only those chunks were refetched before the official review.\n\nReview SHA256:'+sha(B/'REVIEW.json')+'\nPreregistration SHA256:'+sha(B/'PREREGISTRATION.json')+'\nAdmitted G1 scientific root SHA256:'+r['admitted_G1_scientific_root_sha256']+'\n\nRecovery: verify handoff MANIFEST.json. Restore only the two original streams from bundled RAW_CHUNKS manifests and their exact Drive part IDs; place verified parts at drive_objects/SHA256.bin and run recover_streams.py. Retrieve the recorded historical continuation file using its saved Drive ID. The handoff includes the exact G1 public population, catalog and cold admission evidence in their original relative paths. Recover the 8.4 MB G1 sealed source from its recorded Drive file ID; the full 254 MB index is unnecessary. Use pinned CPython 3.13.5 with unchanged registered scripts.\n\nNext: preregister and preflight bounded G2 realization/Q2-witness checks from the admitted exact G1 parent source. Do not infer G2 graduation from the saved-reference review.\n')
    s=json.loads((W/'CURRENT_STATUS.json').read_text());s.update(status_as_of_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),latest_checkpoint=234,current_phase='G2_SAVED_SOURCE_BINDINGS_REVIEWED',master_slices=152,new_admissions=0,latest_audit=a,checkpoint0234=r,next_scope='G2_BOUNDED_REALIZATION_Q2_WITNESS_REGISTRATION_AND_PREFLIGHT',code_mirror=json.loads((B/'CODE_MIRROR.json').read_text()))
    (B/'STATUS_CANDIDATE.json').write_text(json.dumps(s,indent=2)+'\n')
    files=[p for p in sorted(B.iterdir()) if p.is_file() and p.suffix in ('.json','.py','.log','.txt') and p.name not in ('DELIVERABLES.json','SAVE_RECEIPT.json')]+[report]
    files += [W/'continuation0231/HISTORICAL_V1_INTERFACE_POPULATION.json',W/'continuation0233/CATALOG_0152.json',W/'continuation0233/SCOPED_ADMISSION.json',W/'continuation0233/AUDIT.json',W/'continuation0233/SAVE_RECEIPT.json',W/'continuation0232/SEAL_RECEIPT.json',W/'continuation0232/SEAL_DRIVE_SAVE.json',W/'continuation0231/RUNTIME_MANIFEST.json']
    manifest={str(p.relative_to(W)):dict(sha256=sha(p),bytes=p.stat().st_size) for p in files};out=W/'IG_MASTER152_G2_SAVED_SOURCE_BINDING_REVIEW0234_HANDOFF_2026-10-09.zip'
    with zipfile.ZipFile(out,'w',zipfile.ZIP_DEFLATED,compresslevel=6) as z:
        for p in files:z.write(p,str(p.relative_to(W)))
        z.writestr('MANIFEST.json',json.dumps(manifest,indent=2))
    with zipfile.ZipFile(out) as z:
        assert z.testzip() is None
        for n,v in manifest.items():assert hashlib.sha256(z.read(n)).hexdigest()==v['sha256']
    d=dict(checkpoint=234,master_slices=152,new_admissions=0,report=dict(path=str(report),sha256=sha(report),bytes=report.stat().st_size),handoff=dict(path=str(out),sha256=sha(out),bytes=out.stat().st_size))
    (B/'DELIVERABLES.json').write_text(json.dumps(d,indent=2)+'\n');print(json.dumps(d))
if __name__=='__main__':main()
