from pathlib import Path
import json,hashlib,datetime,shutil
B=Path(__file__).resolve().parent;R=B.parent;E=R/'g_public_export0180';P=R/'o7_additional_integrate0174'
sha=lambda b:hashlib.sha256(b).hexdigest();load=lambda p:json.loads(p.read_bytes())
def dump(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
n=load(E/'NATIVE_RESULT.json');cold=load(E/'COLD_REUSE_RESULT.json');r=n['result'];pins=load(E/'EXPORT_BINDINGS.json')
assert n['status']=='COMPLETED' and n['evidence_status']=='VERIFIED' and r['outcome']=='PASS' and cold['reused'] and cold['completion_sha256']==n['completion_sha256'] and cold['pending_bytes']==0
oldp=P/'CATALOG_0149.json';old=load(oldp);oldsha=sha(oldp.read_bytes());assert oldsha=='84641ecb46ea253c9a8cbbeaa418c6cd14bda93512a763c583ce3ed3af559f7c'
ad={'schema_id':'IG_MASTER_SCOPED_DATA_ADMISSION_V1','decision':'ACCEPTED_FOR_REUSE_WITHIN_SAVED_G1_PUBLIC_PROJECTION_SCOPE','authority':'EXTERNAL_OPERATOR_DECISION_UNDER_USER_AUTHORIZED_MASTER_CAMPAIGN','admitted_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'dataset_id':'G1_SAVED_PUBLIC_ONE_ENDPOINT_PROJECTIONS_V1','scientific_root_sha256':pins['root_sha256'],'scientific_archive_sha256':pins['archive_sha256'],'predecessor_catalog_sha256':oldsha,'counts':{k:r[k] for k in ['interfaces','interface_classes','reservation_rows','continuation_hashes']},'scope':{'authority':'SAVED_PUBLIC_PROJECTION_ONLY','carrier_ref':'opaque historical reference','interface_equivalence':'ONE_EXTERNAL_ENDPOINT_RESERVATION_FOR_WHOLE_CARRIER_PAIR_CONNECTION','exact_parent_DAG_available':False,'reservation_witnesses_available':False,'Q2_payload_available':False,'fresh_realization':False},'identity':'SOURCE_BYTE_PIN_PLUS_HISTORICAL_CARRIER_REF;OBSERVER_CLASS_INTERFACE_SHA256','native_completion_sha256':n['completion_sha256'],'native_result_sha256':n['result_sha256'],'cold_reuse':True,'generation_calls':0,'g2_graduated':False,'automatic_g_advance':False,'not_covered':['exact G1 states or ancestry','unbounded future interface','Q2 payloads','fresh observer realization','G2 graduation','full L0-G8 completion']}
p=B/'SCOPED_ADMISSION.json'
if p.exists():ad=load(p)
else:dump(p,ad)
cat=json.loads(json.dumps(old));cat.update(release_id='MASTER_DATA_V1_0150',previous_release_id='MASTER_DATA_V1_0149',previous_catalog_sha256=oldsha);saved=load(E/'SCIENTIFIC_EXPORT_SAVED.json')
cat['slices'].append({'dataset_id':ad['dataset_id'],'scientific_root_sha256':pins['root_sha256'],'format':'IG_SAVED_G1_PUBLIC_PROJECTION_EXPORT_V1','identity_profile':ad['identity'],'scope':ad['scope'],'counts':ad['counts'],'scoped_admission_sha256':sha(p.read_bytes()),'archive':{'file_name':'G1_SAVED_PUBLIC_PROJECTION_NATIVE_EXPORT0180.zip','sha256':pins['archive_sha256'],'size_bytes':pins['bytes'],'drive_file_id':saved['id'],'drive_folder_id':'1ALFgcEwVXK7r4yzkP1tJQsOMUPilsAzZ'}})
cat['coverage_summary'].update(g1_saved_public_projection=ad['counts'],g1_exact_parent_DAG_available=False,g1_Q2_payload_available=False);dump(B/'CATALOG_0150.json',cat)
for p in (P/'project').rglob('*.py'):
 target=B/'project/previous'/p.relative_to(P/'project');target.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(p,target)
(B/'project/projection').mkdir(exist_ok=True)
for name in ['reader.py','__init__.py']:shutil.copy2(R/'g_public_register0179/project'/name,B/'project/projection'/name)
mh={str(p.relative_to(B/'project/previous')):sha(p.read_bytes()) for p in (B/'project/previous').rglob('*.py')};dump(B/'PREDECESSOR_SOURCE_HASHES.json',mh)
bindings={'CATALOG_SHA256':sha((B/'CATALOG_0150.json').read_bytes()),'PREVIOUS_SHA256':oldsha,'ADMISSION_SHA256':sha((B/'SCOPED_ADMISSION.json').read_bytes())};(B/'project/bindings.py').write_text('\n'.join(k+'='+repr(v) for k,v in bindings.items())+'\n')
s=load(P/'SPEC.json');s.update(job_id='MASTER.G1.SAVED.PUBLIC.PROJECTION.CATALOG.INTEGRATION.V1',project_source=str(B/'project'));s['question'].update(stage_id='MASTER:G1:SAVED:PUBLIC:PROJECTION:CATALOG:INTEGRATION:V1',description='Projection-scoped Master150 integration; preserve all149 predecessor slices and reader bytes',stopping_rule='Stop source, identity, scope or delegation mismatch;no generation')
s['inputs']=[x for x in s['inputs'] if x['logical_name']!='new_catalog']
for name,p in [('new_catalog',B/'CATALOG_0150.json'),('g1_admission',B/'SCOPED_ADMISSION.json'),('g1_archive',E/'SCIENTIFIC_EXPORT.zip'),('catalog0149',oldp),('g1_predecessor_sources',B/'PREDECESSOR_SOURCE_HASHES.json'),('g1_population',R/'g_public_register0179/inputs/G2_S0_INTERFACE_POPULATION.json'),('g1_continuations',R/'g_public_register0179/inputs/POST_RESERVATION_CONTINUATION_HASHES.json')]:s['inputs'].append({'logical_name':name,'path':str(p),'sha256':sha(p.read_bytes())})
checks={'outcome':'PASS','release_id':'MASTER_DATA_V1_0150','scientific_slices':150,'prior_slices_unchanged':149,'prior_reader_bytes_unchanged':True,'all_g1_public_interface_routes_checked':193,'all_g1_public_class_routes_checked':192,'all_g1_public_reservation_routes_checked':1351,'all_g1_public_continuation_routes_checked':1351,'prior_additional_o7_delegation_routes_checked':24,'generation_calls':0,'authority':'SAVED_PUBLIC_PROJECTION_ONLY','g1_exact_parent_DAG_available':False,'g1_Q2_payload_available':False}
s['output_contract']['result_checks']=[{'pointer':'/'+k,'equals':v} for k,v in checks.items()];dump(B/'SPEC.json',s);print(json.dumps(bindings))
