from pathlib import Path
import json,hashlib,zipfile,shutil,datetime
B=Path('o2_recovery0154');x=json.load(open(B/'ARCHIVE_SEARCH.json'));assert not x['errors'] and not x['new_missing_panel_matches'];old=json.load(open('o3_readiness0153/READINESS_VALIDATION.json'));sha=lambda b:hashlib.sha256(b).hexdigest();refs=json.load(open(B/'LIBRARY_SEARCH_REFS.json'))
for r in refs['matched_restart_archives']:
 p=next(p for p in (B/'library_sources').rglob('*.zip') if p.name==r['name']);r['sha256']=sha(p.read_bytes())
refs['prior_verified_recovery_bundle']={'name':'IG_O2_O3_READINESS_RECOVERY_HANDOFF_2026-10-06.zip','sha256':'23483fe980ba90fd908397dc3eee0e50ba025a6404d476c2cbaee254f5c6476f','drive_file_id':'1qYKA1xE-GNR2iIT9zeI4ze2uMoB2uMn9','bytes':18496698,'contains':'53 exact panels, frozen O3 launch and independent graduation authority; master0143 restore reference'};(B/'RECOVERY_DEPENDENCIES.json').write_text(json.dumps(refs,indent=2))
report='INFINITY GRID EXACT O2 PANEL RECOVERY SEARCH — 2026-10-06\n\nSEARCH COMPLETE WITHIN DECLARED SCOPE:557 recursive archives checked,188 panel-name occurrences compared to129 frozen original source hashes,zero scanner errors. Scope:11 available producer/foundation/O/scout/decoder/chat attachment archives and2 saved Scout2-B restart bundles. No additional missing-panel hash matched. Restart panels are early k0/k1 with different frozen hashes; they do not supply the missing k18+ intervals.\nDrive returned1000 root items; no matching Scout2/IN12 source candidate in that bounded metadata sample. This is NOT an exhaustive proof of absence from all Drive storage. Library exact panel filename lookup and saved restart-bundle recovery found no missing panel bytes.\nCURRENT:53/129 exact original panels verified;76 still missing:k18-31,k33-63,k65-95. Master0143/143 scientific slices unchanged. No new constructions/admissions/registered scientific jobs;generator calls0,pending bytes0. Original Q bank256/O3 seeds128 remain saved and internally verified;full129-panel source-bank reproduction remains blocked.\nREQUIRED NEXT:Obtain a saved complete Scout2-B V1.2 optimized fresh k0..k128 snapshot or the exact76 panel files in MISSING_PANEL_REQUEST.json. Verify each frozen hash before binding. Do not regenerate completed constructions to fill missing bytes or substitute observer outputs for exact carriers.\n'
(B/'REPORT.txt').write_text(report);s=json.load(open('CURRENT_STATUS.json'));s.update(status_as_of_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),next_scope='EXACT_SCOUT2B_PANEL_RECOVERY_REQUIRES_ADDITIONAL_SAVED_SOURCE',next_scope_status='BLOCKED_AFTER_BOUNDED_ARCHIVE_SEARCH',o2_recovery_search='o2_recovery0154/ARCHIVE_SEARCH.json',o3_missing_panel_count=76)
if (B/'CODE_MIRROR.json').exists():s['code_mirror']=json.load(open(B/'CODE_MIRROR.json'))
Path('CURRENT_STATUS.json').write_text(json.dumps(s,indent=2));D=Path('handoff0154_recovery_search');D.mkdir(exist_ok=True);dest=D/B;dest.mkdir(exist_ok=True)
for p in B.iterdir():
 if p.is_file() and p.suffix in ['.json','.py','.txt']:shutil.copy2(p,dest/p.name)
(D/'READ_FIRST.txt').write_text(report+'\nRECOVERY:This is a compact search-receipt delta. Recover prior53 exact panels/frozen producer using RECOVERY_DEPENDENCIES.json; that bundle in turn pins full master0143 restore. Current STATUS/cursor override ancestor next-step prose. Do not repeat the same archive search without a new candidate source.\n');(D/'STATUS.json').write_text(json.dumps(s,indent=2));(D/'CONTINUATION_CURSOR.json').write_text(json.dumps({'master_release':'MASTER_DATA_V1_0143','scientific_slices':143,'completed_action':'0154_BOUNDED_MISSING_O2_EXACT_PANEL_ARCHIVE_SEARCH','next_scope':s['next_scope'],'new_source_required':True,'missing_k':old['missing_k'],'next_job_captured':False,'pending_bytes':0,'generator_calls':0},indent=2));(D/'TEMPLATE_COMPLIANCE.json').write_text(json.dumps({'read_first':True,'status':True,'cursor':True,'search_receipts':True,'scripts':True,'exact_missing_hash_request':True,'prior_verified_bytes_recovery_refs':True,'manifest':True,'scope_limits_explicit':True},indent=2));(D/'MANIFEST.json').unlink(missing_ok=True);m={str(p.relative_to(D)):{'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size} for p in D.rglob('*') if p.is_file()};(D/'MANIFEST.json').write_text(json.dumps(m,indent=2));p=Path('IG_MISSING_O2_PANEL_SEARCH_HANDOFF_2026-10-06.zip')
with zipfile.ZipFile(p,'w',zipfile.ZIP_DEFLATED) as z:
 for n in [*m,'MANIFEST.json']:z.write(D/n,n)
with zipfile.ZipFile(p) as z:
 for n,v in m.items():assert sha(z.read(n))==v['sha256']
Path('CURRENT_START.txt').write_text('handoff0154_recovery_search/READ_FIRST.txt\n');Path('IG_MISSING_O2_PANEL_SEARCH_START_2026-10-06.txt').write_text(report+'\nBundle:'+p.name+'\nBundle SHA256:'+sha(p.read_bytes())+'\n');meta={'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size,'manifest_files':len(m)};(B/'DELIVERY_BINDINGS.json').write_text(json.dumps(meta));print(meta)
