"""Package separately registered native recovery with predecessor provenance."""
from pathlib import Path
import json,hashlib,zipfile,datetime
B=Path(__file__).resolve().parent;W=B.parent
A=json.loads((B/'AUDIT.json').read_text());assert A['status']=='PASS_COLD_HISTORICAL_DEPTH86_CONTINUATION'
assert json.loads((B/'CHECKPOINT_PRESERVED.json').read_text())['pending_bytes']==0
report='Checkpoint 0226: historical depths 81–86 verified and natively completed.\n2026-10-08\n\nThe frozen capture starts from the exact independently restored bootstrap 80 earned in checkpoint 0225. Lossless gzip transport is bound by its compressed hash and the decoded bootstrap hash. Historical scientific helpers remain byte-identical to the qualified helpers; recipes, selection and candidate census are unchanged. The registered workspace budget is 4 GiB.\nSix committed native phase results each contain a census of 193 candidates and select 24 roots: 1,158 candidates across the committed results. A preservation backlog pause interrupted the first uncommitted depth 86 attempt; after exact raw readback and confirmation, the same frozen capture reused depths 81–85 and resumed depth 86. Candidate work in the interrupted uncommitted attempt is not measured; it is excluded from the committed census. All 24 depth 86 construction roots, resource skins and capacity vectors match the archived source. The initial terminal checkpoint refused the combined duplicate working and sealed trees at its frozen 2 GiB raw snapshot limit. The prepared completion and every sealed file were authenticated; ordinary working files matched exact bytes, and all SQLite schemas and rows matched the sealed databases. The entire original working tree was retained outside the capture, while immutable sealed evidence remained untouched. The same native controller then published the prepared completion without handler or candidate execution and without changing registration, source or policy. Completion is sealed, preserved and independently authenticated from the terminal checkpoint capsule.\nA fresh cold restore verifies all dependency bytes, six exact native identities and 144 root DAG roundtrips. No candidates are generated during audit. Bootstrap 86 is exported for the next tranche. Master remains 151, with zero new admissions. Terminal 100 comparison, Q2 and full L0–G8 replay remain incomplete.\nThe original checkpoint 0224 budget pause remains unchanged. Checkpoint 0225 separately completed its verification-only recovery; no original candidates were regenerated. PREDECESSOR_HANDOFF_REFERENCE.json identifies that saved recovery.\nNext: register depths 87–92 with adequate workspace budget, bind bootstrap 86 and the archived depth 92 reference, preserve before execution, stop on the first mismatch, and independently cold-audit before advancing.\nRecovery: verify MANIFEST.json, then retrieve the exact CHECKPOINT_EXPORT.json dependencies using READBACKS.json Drive IDs. restore_current.py restores the native checkpoint with the pinned CPython 3.13.5 / SQLite 3.51.3 runtime and frozen engine. Do not regenerate committed phases.\n'
(B/'REPORT.txt').write_text(report)
s=json.loads((W/'CURRENT_STATUS.json').read_text());s.pop('latest_handoff',None)
s.update(status_as_of_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),latest_checkpoint=226,latest_capture_id=json.loads((B/'POINTER.json').read_text())['capture_id'],current_phase='G1_HISTORICAL_DEPTH86_NATIVE_VERIFIED',in_flight_active=None,active_native_runtime=None,completed_depth=86,historical_verified_depth=86,historical_cold_audited_depth=86,historical_reconstructed_depth=86,historical_reconstruction_acceptance='THROUGH86_HISTORICAL_NATIVE_QUALIFIED',candidate_build_calls=1158,generator_calls=7,committed_generator_tasks=6,interrupted_generator_attempts=1,interrupted_candidate_work='NOT_MEASURED',native_verification_tasks=0,generator_calls_scope='0226:six committed phase tasks plus one interrupted depth86 attempt; 1158 committed candidate census; interrupted candidate work not measured; audit generated none',pending_bytes=0,master_slices=151,new_admissions=0,terminal_comparison='NOT_RUN_AFTER_HISTORICAL_REPAIR',next_scope='G1_HISTORICAL87_92',next_scope_status='READY_FOR_FRESH_CAPTURE',latest_audit=A,checkpoint0226=A)
s['checkpoint0224_original_native_status']='PAUSED_WORKSPACE_BUDGET_UNMODIFIED'
if (B/'CODE_MIRROR.json').exists():s['code_mirror']=json.loads((B/'CODE_MIRROR.json').read_text())
s['catalog_path']=str(B/'CATALOG_0151.json')
(W/'CURRENT_STATUS.json').write_text(json.dumps(s,indent=2));(B/'STATUS_CANDIDATE.json').write_text(json.dumps(s,indent=2))
files={str(p.relative_to(W)):p for p in sorted(B.rglob('*')) if p.is_file() and p.suffix in ('.py','.json','.txt','.zip','.log') and '__pycache__' not in p.parts and not p.name.startswith('private_') and p.name not in ('MIRROR_ELEMENTS.json','DELIVERABLES.json','SAVE_RECEIPT.json')}
boot=Path(json.loads((B/'BOOTSTRAP86_META.json').read_text())['path']);files['continuation0226/BOOTSTRAP86_HISTORICAL.json']=boot
manifest={k:{'bytes':p.stat().st_size,'sha256':hashlib.file_digest(p.open('rb'),'sha256').hexdigest()} for k,p in files.items()}
out=W/'IG_MASTER151_G1_HISTORICAL_CONTINUATION_0226_HANDOFF_2026-10-08.zip'
with zipfile.ZipFile(out,'w',zipfile.ZIP_DEFLATED,compresslevel=6) as z:
 for k,p in files.items():z.write(p,k)
 z.writestr('MANIFEST.json',json.dumps(manifest,indent=2))
with zipfile.ZipFile(out) as z:
 assert z.testzip() is None
 for k,v in manifest.items():assert hashlib.sha256(z.read(k)).hexdigest()==v['sha256']
r={'path':str(out),'sha256':hashlib.file_digest(out.open('rb'),'sha256').hexdigest(),'bytes':out.stat().st_size,'checkpoint':226,'status':A['status'],'historical_verified_depth':86,'native_completion_status':'VERIFIED' ,'prior0224_native_status':'PAUSED_WORKSPACE_BUDGET_UNMODIFIED','master_slices':151,'new_admissions':0,'native_pending_bytes':0,'next_scope':s['next_scope']}
(B/'DELIVERABLES.json').write_text(json.dumps(r,indent=2));print(json.dumps(r))
