from pathlib import Path
import json,hashlib,zipfile,shutil,datetime
B=Path('o3_export0156');load=lambda n:json.load(open(B/n));n=load('NATIVE_RESULT.json');c=load('COLD_REUSE_RESULT.json');assert n['status']=='COMPLETED' and n['evidence_status']=='VERIFIED' and n['result']['outcome']=='PASS' and c['status']=='PASS' and c['pending_bytes']==0 and load('CHECKPOINT_ACK.json')['outbox']['pending_bytes']==0
sha=lambda b:hashlib.sha256(b).hexdigest()
report='''INFINITY GRID REGISTERED SAVED O3 EXPORT/READER GATE0156 — 2026-10-06

PASS:COMPLETED/VERIFIED. Selected r1..r64 carriers4771; external r0 seeds96. All4867 saved carrier occurrence routes,6031 parent routes,25057 nested anonymous O2 Q-state routes and4927 nontrivial connected-component routes checked. Original panels and lane metadata retained losslessly. Typed edge multiset155458; frozen Q bank256states. Endpoint capacity, compatibility, component topology and resource identities pass. Original producer keys recomputed4803;64 symmetric fallback labels remain source-bound. Full literal payload hashes retained; no claim of independently canonicalized fallback IDs.

Missing/excluded routes, seed ancestry exclusion, copy isolation and closed reader checks pass. Capture and terminal checkpoint saved with raw byte readbacks. Cold restore and exact completion reuse PASS;pending bytes0;generation calls0. The76 missing microscopic O2 panels remain unresolved. Nested Q states are anonymous local(p,u2) resources, with microscopic O2 incidence and bank-selection reproduction outside this scope. Historical graduation is preserved as a reference, not newly certified.

MASTER:MASTER_DATA_V1_0143/143 slices unchanged; no new scoped admission.
NEXT:Issue scoped admission for saved O3 typed-incidence panels and nested external Q-bank states; register catalog/reader integration preserving all143 predecessor slices and routes. Do not regenerate completed constructions.
'''
(B/'REPORT.txt').write_text(report);s=json.load(open('CURRENT_STATUS.json'));s.update(status_as_of_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),next_scope='SAVED_O3_TYPED_INCIDENCE_SCOPED_ADMISSION_AND_CATALOG_INTEGRATION',next_scope_status='REGISTERED_EXPORT_READER_VERIFIED_PRESERVED_COLD_REUSED',o3_export_result='o3_export0156/NATIVE_RESULT.json',code_mirror=load('CODE_MIRROR.json'));Path('CURRENT_STATUS.json').write_text(json.dumps(s,indent=2));D=Path('handoff0156_o3_export');D.mkdir(exist_ok=True);dest=D/B;dest.mkdir(exist_ok=True)
for p in B.iterdir():
 if p.is_file() and p.suffix in ['.json','.py','.txt'] and not p.name.startswith('TO_SAVE'):shutil.copy2(p,dest/p.name)
shutil.copytree(B/'project',dest/'project',ignore=shutil.ignore_patterns('__pycache__'),dirs_exist_ok=True)
for name in ['SCIENTIFIC_EXPORT.zip','FINAL_CHECKPOINT_SLIM.zip']:shutil.copy2(B/name,dest/name)
# Only restore dependencies used by this capture, not unrelated historical readback maps.
for name,hashes in [('READBACKS.json',{r['sha256'] for r in load('PENDING.json')['pending_objects']}),('CHECKPOINT_READBACKS.json',{r['sha256'] for r in load('EXPORT.json')['dependencies']}|{load('EXPORT.json')['sha256']})]:
 m=load(name);(dest/name).write_text(json.dumps({h:m[h] for h in sorted(hashes)},indent=2))
refs={'master_restore':{'name':'IG_MASTER_DATA_V1_0143_O2_HANDOFF_2026-10-06.zip','sha256':'625133b8b4cadbcf2df083d4930fe4b7762dba3dedb4644e925c0096316effcb','drive_file_id':'15pHttKvMJmR7NjqRK1Ji-zEVwMBG4FtY'},'readiness_restore':{'name':'IG_O3_SAVED_SCOPE_READINESS_HANDOFF_2026-10-06.zip','sha256':'48053917643a7bbbf134c34105923dd427def2293e504bf7f4638ec3db2fe2ab','drive_file_id':'1GSWAUl11XQcZ6F953yf26HawvlwEFi5X'},'native_restore':'Use EXPORT.json and CHECKPOINT_READBACKS.json exact hash/ID dependencies; rebind local paths only. Restore checkpoint using pinned runtime, then cold reuse; do not execute generations.'};(D/'RECOVERY_DEPENDENCIES.json').write_text(json.dumps(refs,indent=2));(D/'READ_FIRST.txt').write_text(report);(D/'STATUS.json').write_text(json.dumps(s,indent=2));(D/'CONTINUATION_CURSOR.json').write_text(json.dumps({'master_release':'MASTER_DATA_V1_0143','scientific_slices':143,'completed_gate':'0156_SAVED_O3_EXPORT_READER','next_scope':s['next_scope'],'scientific_admission_issued':False,'capture_id':load('POINTER.json')['capture_id'],'completion_sha256':n['completion_sha256'],'result_sha256':n['result_sha256'],'pending_bytes':0,'generator_calls':0},indent=2));(D/'TEMPLATE_COMPLIANCE.json').write_text(json.dumps({'read_first':True,'status':True,'cursor':True,'source_bytes':True,'manifest':True,'native_checkpoint_and_dependency_receipts':True,'external_Qbank_boundary_explicit':True,'completed_constructions_regenerated':False},indent=2));(D/'MANIFEST.json').unlink(missing_ok=True);m={str(p.relative_to(D)):{'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size} for p in D.rglob('*') if p.is_file()};(D/'MANIFEST.json').write_text(json.dumps(m,indent=2));zpath=Path('IG_O3_GATE_0156_VERIFIED_HANDOFF_2026-10-06.zip')
with zipfile.ZipFile(zpath,'w',zipfile.ZIP_DEFLATED) as z:
 for name in [*m,'MANIFEST.json']:z.write(D/name,name)
with zipfile.ZipFile(zpath) as z:
 for name,x in m.items():assert sha(z.read(name))==x['sha256']
Path('CURRENT_START.txt').write_text(str(D/'READ_FIRST.txt')+'\n');Path('IG_O3_GATE_0156_START_2026-10-06.txt').write_text(report+'\nBundle:'+zpath.name+'\nBundle SHA256:'+sha(zpath.read_bytes())+'\nVerify MANIFEST.json before continuing.\n');meta={'sha256':sha(zpath.read_bytes()),'bytes':zpath.stat().st_size,'manifest_files':len(m)};(B/'DELIVERY_BINDINGS.json').write_text(json.dumps(meta,indent=2));print(meta)
