export const jobs=[
 {id:'SAMPLE.VALIDATION.01',name:'Engineering validation',question:'Check a fixed set of registered engineering requirements.',state:'Finished',outcome:'Not reported',evidence:'Verified · example',save:'Preserved · example',log:'Example only\nCapture prepared\nRequired objects saved\nRegistered checks finished\nEvidence verified'},
 {id:'SAMPLE.COMPARISON.02',name:'Comparison review',question:'Compare registered inputs and retain a negative outcome.',state:'Finished · save pending',outcome:'Negative · example',evidence:'Verified · example',save:'2 objects pending · example',log:'Example only\nRegistered comparison finished\nNegative outcome retained\nCheckpoint objects await save'},
 {id:'SAMPLE.PREPARED.03',name:'Prepared job',question:'Review the capture and its save obligations before execution.',state:'Prepared',outcome:'Not reported',evidence:'Not reported',save:'Capture save pending · example',log:'Example only\nTask version selected\nCapture prepared\nExecution has not started'}
];
export function filterJobs(query){const q=query.trim().toLowerCase();return jobs.filter(j=>(j.id+' '+j.name).toLowerCase().includes(q));}
export function taskReview(id){return id==='comparison'?{name:'Registered comparison',inputs:'Two fixed sample inputs',policy:'No automatic runtime deadline'}:{name:'Engineering validation',inputs:'Fixed sample engineering specification',policy:'No automatic runtime deadline'};}
if(typeof document!=='undefined'){
 const $=id=>document.getElementById(id),node=(tag,value,cls)=>{const n=document.createElement(tag);n.textContent=value;if(cls)n.className=cls;return n;};let selected=jobs[0];
 function show(screen){for(const id of ['jobs','prepare','run','results'])$(id).hidden=id!==screen;for(const b of document.querySelectorAll('[data-screen]'))b.setAttribute('aria-pressed',String(b.dataset.screen===screen));if(screen==='run'||screen==='results')details();$(screen).focus();}
 function details(){$('run-title').textContent=selected.name;$('run-question').textContent=selected.question;$('run-log').textContent=selected.log;$('results-title').textContent=selected.name;const facts=$('run-facts');facts.replaceChildren();for(const [name,value] of [['Sample job ID',selected.id],['Execution',selected.state],['Backend','Not connected']]){const d=node('div','');d.append(node('dt',name),node('dd',value));facts.append(d);}$('outcome').textContent=selected.outcome;$('evidence').textContent=selected.evidence;$('saved').textContent=selected.save;}
 function list(){const root=$('job-list');root.replaceChildren();for(const j of filterJobs($('search').value)){const b=node('button','','job-row');const identity=node('span','','job-identity');identity.append(node('span',j.name,'job-name'),node('span',j.question,'job-question'),node('span',j.id,'job-id'));b.append(identity,node('span',j.state,'job-state'),node('span','›','chevron'));b.addEventListener('click',()=>{selected=j;show('run');});root.append(b);}if(!root.children.length)root.append(node('p','No matching sample jobs.'));}
 for(const b of document.querySelectorAll('[data-screen]'))b.addEventListener('click',()=>show(b.dataset.screen));$('new-job').addEventListener('click',()=>show('prepare'));$('show-results').addEventListener('click',()=>show('results'));$('search').addEventListener('input',list);
 $('review').addEventListener('click',()=>{const r=taskReview($('task').value);$('review-content').replaceChildren(node('h2',r.name),node('p',r.inputs),node('p',r.policy),node('p','Preview only. No capture is created and no job is submitted.'));});
 list();details();$('offline-note').textContent=navigator.onLine?'Static preview · no sign-in required':'Offline · showing the installed preview';
 if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./'}).then(()=>navigator.serviceWorker.ready).then(()=>{$('offline-note').textContent='Preview ready for offline use. In Safari, use Share → Add to Home Screen.';}).catch(()=>{$('offline-note').textContent='Online preview ready. Offline installation is unavailable in this browser.';});
}
