from pathlib import Path
import json,hashlib,zipfile,shutil,datetime
B=Path('o3_integrate0157');load=lambda n:json.load(open(B/n));n=load('NATIVE_RESULT.json');cold=load('COLD_REUSE_RESULT.json');ack=load('CHECKPOINT_ACK.json');assert n['status']=='COMPLETED' and n['execution_status']=='FINISHED' and n['evidence_status']=='VERIFIED' and n['result']['outcome']=='PASS' and cold['reused'] and cold['pending_bytes']==0 and ack['outbox']['pending_bytes']==0
r=n['result'];expected={'all_o3_routes_checked':4867,'all_o3_parent_routes_checked':6031,'all_nested_Q_routes_checked':25057,'all_o3_component_routes_checked':4927,'all_o2_routes_checked':26267,'all_o2_parent_routes_checked':63885,'all_node_routes_checked':32545,'all_node_parent_routes_checked':134714,'prior_slices_unchanged':143,'all_pair_routes_checked':1458}
for k,x in expected.items():assert r[k]==x
sha=lambda b:hashlib.sha256(b).hexdigest();cat=load('CATALOG_0144.json');prev=json.load(open('o2_integrate0152/CATALOG_0143.json'));assert cat['slices'][:-1]==prev['slices']
v={'schema':'IG_SAVED_O3_INTEGRATION_RELEASE_V1','release_id':'MASTER_DATA_V1_0144','catalog_sha256':sha((B/'CATALOG_0144.json').read_bytes()),'scientific_slices':144,'status':'VERIFIED_PRESERVED_COLD_REUSED','counts':dict(expected,prior_reader_modules_checked=r['prior_reader_modules_checked']),'o3_scope':cat['slices'][-1]['scope'],'prior_reader_bytes_unchanged':True,'native_completion_sha256':n['completion_sha256'],'native_result_sha256':n['result_sha256'],'cold_reuse':True,'pending_bytes':0,'generation_calls':0,'full_l0_to_g8_complete':False};(B/'RELEASE_VERIFICATION.json').write_text(json.dumps(v,indent=2))
report='''INFINITY GRID MASTER_DATA_V1_0144 SAVED O3 ADMITTED/INTEGRATED — 2026-10-06

Release0144,144 scientific slices. Scoped admission for4771 saved O3 selected carriers r1..r64 with96 external r0 seeds,6031 parent links,155458 typed edges and256 nested frozen anonymous O2 Q states.4927 nontrivial connected-component occurrences remain readable as restrictions of preserved full forest roots. All original selected-row and lane metadata retained. Original keys recomputed4803;64 symmetric fallback labels remain source-bound, with full literal payload SHA256 and explicit identity limits.

Registered integration gate0157 COMPLETED/FINISHED/VERIFIED. All4867 O3 routes,6031 parents,25057 nested Q routes and4927 component routes pass. All26267 existing O2 routes/63885 parents and32545 NODE routes/134714 parents pass.143 predecessor catalog slices and prior reader source bytes unchanged;1458 pair object routes and recursive depth1/2 samples pass. Existing300696 J3/199579 recursive constructions retained. No fresh full legacy science replay claimed.

Capture and checkpoint saved with raw readbacks; cold restore/exact completion reuse PASS;pending bytes0;generation calls0. Master integration adds a saved-data slice, not a newly generated full O3 census or fresh graduation. The76 missing microscopic O2 panels remain unresolved. Anonymous local(p,u2) Q-bank resources do not reconstruct microscopic O2 incidence or close source-bank selection provenance. Full L0-G8 completion remains false.

NEXT:WP5 source-bound readiness for remaining original O carrier/action producers, including O4-O7. Inspect saved recipes and exact prerequisites; identify a finite executable scope against admitted data. Keep microscopic O2 recovery as a separate blocked lane; do not claim WP5 complete from this saved-data admission or regenerate completed constructions.
'''
(B/'REPORT.txt').write_text(report);(B/'READ_O3_ROUTES.txt').write_text('O3MasterReader adds lookup_o3(rank,exact_key),o3_parents(rank,exact_key),o3_components(rank,exact_key),o3_qstate(q_hash). All inherited O2/NODE/J3/pair/recursive routes delegate through byte-preserved previous readers. r0 is an external seed and ancestry queries fail closed. Q lookup returns anonymous local(p,u2) resource state with explicit microscopic boundary. Components preserve typed parallel edge multiplicities and original root index correspondence. Constructor pins0144 catalog,0143 predecessor, scoped admission, O3 export and inherited previous_arguments. Restore native dependency IDs/hashes in EXPORT/CHECKPOINT_READBACKS; rebind local paths only. No generation/repair path.\n')
s=json.load(open('CURRENT_STATUS.json'));s.update(status_as_of_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),latest_committed_release='MASTER_DATA_V1_0144',catalog_sha256=v['catalog_sha256'],catalog_path='o3_integrate0157/CATALOG_0144.json',scientific_slices=144,next_scope='WP5_REMAINING_O_PRODUCER_SOURCE_BOUND_READINESS',next_scope_status='NOT_PREPARED',admitted_o3_saved_typed_carriers={'ranks':[1,64],'external_seed_rank':0,'seed_carriers':96,'carriers':4771,'parent_links':6031,'typed_edges':155458,'bank_entries':256,'component_occurrences':4927,'microscopic_O2_source_closed':False,'missing_O2_panels':76,'status':'SCOPED_ADMITTED_AND_UNIFIED_READER_INTEGRATED'},o3_integration_result='o3_integrate0157/NATIVE_RESULT.json',code_mirror=load('CODE_MIRROR.json'));Path('CURRENT_STATUS.json').write_text(json.dumps(s,indent=2))
D=Path('handoff0144_o3');D.mkdir(exist_ok=True);dest=D/B;dest.mkdir(exist_ok=True)
for p in B.iterdir():
 if p.is_file() and p.suffix in ['.json','.py','.txt'] and not p.name.startswith('TO_SAVE'):shutil.copy2(p,dest/p.name)
shutil.copytree(B/'project',dest/'project',ignore=shutil.ignore_patterns('__pycache__'),dirs_exist_ok=True);shutil.copy2(B/'FINAL_CHECKPOINT_SLIM.zip',dest/'FINAL_CHECKPOINT_SLIM.zip');(D/'o3_export0156').mkdir(exist_ok=True);shutil.copy2('o3_export0156/SCIENTIFIC_EXPORT.zip',D/'o3_export0156/SCIENTIFIC_EXPORT.zip');(D/'o2_integrate0152').mkdir(exist_ok=True);shutil.copy2('o2_integrate0152/CATALOG_0143.json',D/'o2_integrate0152/CATALOG_0143.json')
for name,hashes in [('READBACKS.json',{r['sha256'] for r in load('PENDING.json')['pending_objects']}),('CHECKPOINT_READBACKS.json',{r['sha256'] for r in load('EXPORT.json')['dependencies']}|{load('EXPORT.json')['sha256']})]:
 m=load(name);(dest/name).write_text(json.dumps({h:m[h] for h in sorted(hashes)},indent=2))
refs={'master0143_base':{'name':'IG_MASTER_DATA_V1_0143_O2_HANDOFF_2026-10-06.zip','sha256':'625133b8b4cadbcf2df083d4930fe4b7762dba3dedb4644e925c0096316effcb','drive_file_id':'15pHttKvMJmR7NjqRK1Ji-zEVwMBG4FtY'},'O3_export_gate':{'name':'IG_O3_GATE_0156_VERIFIED_HANDOFF_2026-10-06.zip','sha256':'050aee691146721b595eb76fbb1f9460a9493453d30086626c6380c71bc6861f','drive_file_id':'1xwfSpglNBD5V_lOV5AjAA6SoZ4WdypOl'},'recovery':'This compact master delta includes0144 catalog/admission, all current reader code, new O3 scientific bytes and native checkpoint receipts. Restore0143 base for predecessor scientific bytes, then overlay this delta. Latest STATUS/cursor override ancestor prose. Native clean restore uses EXPORT dependencies with exact saved IDs/hashes, then completion reuse; never regenerate.'};(D/'RECOVERY_DEPENDENCIES.json').write_text(json.dumps(refs,indent=2));(D/'STATUS.json').write_text(json.dumps(s,indent=2));(D/'READ_FIRST.txt').write_text(report+'\nRestore instructions:RECOVERY_DEPENDENCIES.json. Check MANIFEST.json first.\n');(D/'CONTINUATION_CURSOR.json').write_text(json.dumps({'master_release':'MASTER_DATA_V1_0144','scientific_slices':144,'completed_gate':'0157_O3_SCOPED_ADMISSION_AND_CATALOG_INTEGRATION','next_scope':s['next_scope'],'next_job_captured':False,'pending_bytes':0,'generation_calls':0},indent=2));(D/'TEMPLATE_COMPLIANCE.json').write_text(json.dumps({'current_release':'MASTER_DATA_V1_0144','registered_gate':'0157','read_first':True,'status':True,'cursor':True,'code_and_new_scientific_bytes':True,'prior_scientific_bytes_pinned_restore_reference':True,'manifest':True,'native_checkpoint_receipts':True,'full_l0_to_g8_complete':False},indent=2));(D/'MANIFEST.json').unlink(missing_ok=True);m={str(p.relative_to(D)):{'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size} for p in D.rglob('*') if p.is_file()};(D/'MANIFEST.json').write_text(json.dumps(m,indent=2));p=Path('IG_MASTER_DATA_V1_0144_O3_HANDOFF_2026-10-06.zip')
with zipfile.ZipFile(p,'w',zipfile.ZIP_DEFLATED) as z:
 for name in [*m,'MANIFEST.json']:z.write(D/name,name)
with zipfile.ZipFile(p) as z:
 for name,x in m.items():assert sha(z.read(name))==x['sha256']
Path('CURRENT_START.txt').write_text(str(D/'READ_FIRST.txt')+'\n');Path('IG_MASTER_DATA_V1_0144_O3_START_2026-10-06.txt').write_text(report+'\nBundle:'+p.name+'\nBundle SHA256:'+sha(p.read_bytes())+'\n');meta={'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size,'manifest_files':len(m)};(B/'DELIVERY_BINDINGS.json').write_text(json.dumps(meta,indent=2));print(meta)
