from pathlib import Path
import json,hashlib,shutil,datetime
B=Path(__file__).resolve().parent;R=B.parent;E=R/'o3_export0156';sha=lambda b:hashlib.sha256(b).hexdigest();load=lambda p:json.load(open(p));n=load(E/'NATIVE_RESULT.json');cold=load(E/'COLD_REUSE_RESULT.json');ack=load(E/'CHECKPOINT_ACK.json');r=n['result'];assert n['status']=='COMPLETED' and n['evidence_status']=='VERIFIED' and r['outcome']=='PASS' and cold['reused'] and cold['completion_sha256']==n['completion_sha256'] and cold['result_sha256']==n['result_sha256'] and ack['outbox']['pending_bytes']==0
assert r['carriers']==4771 and r['seed_carriers']==96 and r['all_occurrence_routes_checked']==4867 and r['all_parent_routes_checked']==r['parent_links']==6031 and r['all_nested_Q_routes_checked']==25057 and r['all_component_routes_checked']==4927 and not r['microscopic_O2_source_closed']
oldp=R/'o2_integrate0152/CATALOG_0143.json';old=load(oldp);oldsha=sha(oldp.read_bytes());assert oldsha=='f39144bb1ee906f2a7ff1ae9d866aa99f20b9fb118bcf25d9006447e583bcead'
ad={'schema_id':'IG_MASTER_SCOPED_DATA_ADMISSION_V1','decision':'ACCEPTED_FOR_REUSE_WITHIN_SAVED_O3_TYPED_INCIDENCE_AND_EXTERNAL_QBANK_SCOPE','authority':'EXTERNAL_OPERATOR_DECISION_UNDER_USER_AUTHORIZED_MASTER_CAMPAIGN','admitted_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'dataset_id':'O3_SAVED_TYPED_CARRIERS_R1_R64_WITH_EXTERNAL_R0_SEED_AND_QBANK_V1','scientific_root_sha256':r['scientific_root_sha256'],'scientific_archive_sha256':r['archive_sha256'],'predecessor_catalog_sha256':oldsha,'scope':{'ranks':[1,64],'external_seed_rank':0,'population':'Immutable saved selected O3 typed incidence; nested frozen anonymous O2 Q states; nontrivial connected components retained as root restrictions','entity_boundary':'Anonymous local(p,u2) Q bank; microscopic O2 incidence and bank-selection reproduction external','missing_microscopic_O2_panels':76},'counts':{k:r[k] for k in ['carriers','seed_carriers','parent_links','typed_edges','bank_entries','components','all_occurrence_routes_checked','all_parent_routes_checked','all_nested_Q_routes_checked','all_component_routes_checked','recomputed_keys','source_bound_fallback_keys']},'identity':'RANK_QUALIFIED_FROZEN_PRODUCER_LABEL_PLUS_FULL_LITERAL_PAYLOAD_SHA256; TYPED_EDGE_MULTISET; FALLBACK_LABELS_SOURCE_BOUND','native_capture_id':ack['capture_id'],'native_completion_sha256':n['completion_sha256'],'native_result_sha256':n['result_sha256'],'cold_reuse':True,'pending_bytes':0,'generator_calls':0,'historical_audit_reexecuted':False,'not_covered':['Full O3 census','Microscopic O2 incidence closure and frozen Q-bank selection reproduction','Independent canonical relabeling of64 symmetric fallback identities','Fresh O3 graduation authority','Unique microscopic occurrence lineage','Geometry/actualization','Full L0-to-G8 completion'],'evidence':[]}
for p in [E/'NATIVE_RESULT.json',E/'COLD_REUSE_RESULT.json',E/'CHECKPOINT_ACK.json',E/'SAVE_RECEIPT.json',R/'o3_scope0155/SCOPE_CONTRACT.json',R/'o3_scope0155/READINESS_VALIDATION.json']:ad['evidence'].append({'file_name':str(p.relative_to(R)),'sha256':sha(p.read_bytes())})
p=B/'SCOPED_ADMISSION.json'
if p.exists():ad=load(p)
else:p.write_text(json.dumps(ad,indent=2))
cat=json.loads(json.dumps(old));cat.update(release_id='MASTER_DATA_V1_0144',previous_release_id='MASTER_DATA_V1_0143',previous_catalog_sha256=oldsha);a=load(E/'READBACKS.json')[r['archive_sha256']];v=load(R/'o3_scope0155/READINESS_VALIDATION.json');cat['slices'].append({'dataset_id':ad['dataset_id'],'scientific_root_sha256':r['scientific_root_sha256'],'format':'IG_SAVED_O3_TYPED_CARRIERS_EXPORT_V1','identity_profile':ad['identity'],'scope':ad['scope'],'counts':ad['counts'],'scoped_admission_sha256':sha(p.read_bytes()),'scientific_dependencies':[{'role':'PREDECESSOR_MASTER_CATALOG','catalog_sha256':oldsha},{'role':'EXTERNAL_FROZEN_ANONYMOUS_O2_Q_BANK','sha256':v['bank_sha256'],'records':256,'microscopic_O2_source_closed':False},{'role':'EXTERNAL_R0_SELECTED_SEED','panel_sha256':v['panels'][0]['sha256'],'records':96}],'archive':{'file_name':'IG_O3_SAVED_TYPED_CARRIER_SCIENTIFIC_EXPORT_2026-10-06.zip','sha256':r['archive_sha256'],'size_bytes':(E/'SCIENTIFIC_EXPORT.zip').stat().st_size,'drive_file_id':a['id'],'drive_folder_id':'1ALFgcEwVXK7r4yzkP1tJQsOMUPilsAzZ'}});cat['coverage_summary']['o3_saved_typed_carriers']=ad['counts'];cat['coverage_summary']['o3_microscopic_O2_source_closed']=False;(B/'CATALOG_0144.json').write_text(json.dumps(cat,indent=2)+'\n')
shutil.copytree(R/'o2_integrate0152/project',B/'project/previous_o2',ignore=shutil.ignore_patterns('__pycache__'),dirs_exist_ok=True)
for name in ['reader.py','frozen_audit.py','frozen_identity.py']:shutil.copy2(E/'project'/name,B/'project'/name)
(B/'project/__init__.py').write_text('');bindings={'CATALOG_SHA256':sha((B/'CATALOG_0144.json').read_bytes()),'PREVIOUS_SHA256':oldsha,'ADMISSION_SHA256':sha(p.read_bytes())};(B/'project/bindings.py').write_text('\n'.join(k+'='+repr(v) for k,v in bindings.items())+'\n')
manifest={str(p.relative_to(B/'project/previous_o2')):sha(p.read_bytes()) for p in (B/'project/previous_o2').rglob('*.py')};(B/'PREDECESSOR_SOURCE_HASHES.json').write_text(json.dumps(manifest,indent=2))
for name,h in manifest.items():assert sha((R/'o2_integrate0152/project'/name).read_bytes())==h
s=load(R/'o2_integrate0152/SPEC.json');s.update(job_id='MASTER.O3.SAVED.TYPED.CARRIERS.CATALOG.INTEGRATION.V1',project_source=str(B/'project'));s['question'].update(stage_id='MASTER:O3:SAVED:TYPED:CARRIERS:CATALOG:INTEGRATION:V1',description='Scoped-admitted saved O3 typed incidence and external Q bank integrate into0144; preserve143 predecessor slices/readers',stopping_rule='All saved O3 occurrences/parents/nested Q/component routes; all O2 and NODE routes; unchanged143 predecessor slices and reader bytes. Stop first mismatch; no generation.');s['execution']['parameters']={};s['inputs']=[x for x in s['inputs'] if x['logical_name'] not in ['new_catalog','predecessor_sources']]
for name,p in [('new_catalog',B/'CATALOG_0144.json'),('o3_admission',B/'SCOPED_ADMISSION.json'),('o3_archive',E/'SCIENTIFIC_EXPORT.zip'),('catalog0143',oldp),('predecessor_sources',B/'PREDECESSOR_SOURCE_HASHES.json')]:s['inputs'].append({'logical_name':name,'path':str(p),'sha256':sha(p.read_bytes())})
s['output_contract']['result_checks']=[{'pointer':'/'+k,'equals':v} for k,v in {'outcome':'PASS','all_o3_routes_checked':4867,'all_o3_parent_routes_checked':6031,'all_nested_Q_routes_checked':25057,'all_o3_component_routes_checked':4927,'all_o2_routes_checked':26267,'all_o2_parent_routes_checked':63885,'all_node_routes_checked':32545,'all_node_parent_routes_checked':134714,'prior_slices_unchanged':143,'prior_reader_bytes_unchanged':True,'generation_calls':0}.items()];(B/'SPEC.json').write_text(json.dumps(s,indent=2))
for name in ['operate.py','cold_ops.py']:shutil.copy2(E/name,B/name)
print(bindings)
