(()=>{
'use strict';
const $=id=>document.getElementById(id);
const UPPER=['O4','O5','O6','O7','G1','G2','G3','G4','G5','G6','G7','G8'];
const MAP={O4:'O4-O7',O5:'O4-O7',O6:'O4-O7',O7:'O4-O7',G1:'G1',G2:'G2',G3:'G3',G4:'G4',G5:'G5',G6:'G6',G7:'G7',G8:'G8'};
const TITLES={O4:'Historical O4 evidence',O5:'Historical O5 evidence',O6:'Historical O6 evidence',O7:'Historical O7 evidence',G1:'G1 science evidence',G2:'G2 science evidence',G3:'G3 science evidence',G4:'G4 science evidence',G5:'G5 science evidence',G6:'G6 science evidence',G7:'G7 closeout evidence',G8:'G8 + Components evidence'};
let INDEX=globalThis.__RM_UPPER_DATA?.index??null,PACKS=new Map(Object.entries(globalThis.__RM_UPPER_DATA?.packs??{})),upper=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function css(){if($('rm-upper-style'))return;const s=document.createElement('style');s.id='rm-upper-style';s.textContent=`
#all-data-open{border-color:#3c6c78;background:#163244}.data-badge{font-size:9px;margin-left:4px;color:#89f0d5}.upper-field{position:absolute;inset:0;overflow:auto;padding:22px;background:radial-gradient(ellipse at 45% 35%,#12243b 0,#08111f 74%)}.upper-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:13px;align-content:start}.upper-node{min-height:118px;text-align:left;background:#101f31;border:1px solid #33516a;border-radius:14px;padding:14px;color:#dceafa}.upper-node.current{border-color:#4baf9c}.upper-node.historical{border-color:#806f49}.upper-node .u-kind{font-size:9px;letter-spacing:1.1px;color:#7fd9c7}.upper-node .u-title{font-size:12px;font-weight:650;margin:7px 0;overflow-wrap:anywhere}.upper-node .u-meta{font-size:9px;color:#92a8bf;line-height:1.5}.upper-note{grid-column:1/-1;padding:12px 14px;background:#192b38;border-left:2px solid #58d8c0;border-radius:8px;font-size:11px;color:#bfd0df}.upper-gap{border-left-color:#d5a445;background:#302b20;color:#dfcda5}.adl{position:fixed;inset:0;z-index:10000;background:#07111def;color:#e9f2ff;display:none;backdrop-filter:blur(8px)}.adl.open{display:grid;grid-template-rows:auto 1fr}.adl-head{display:flex;gap:10px;align-items:center;padding:12px 14px;background:#0d1a2a;border-bottom:1px solid #2a4055;flex-wrap:wrap}.adl-head h2{font-size:18px;margin:0 12px 0 0}.adl-head select,.adl-head input{background:#101f31;color:#e9f2ff;border:1px solid #355066;border-radius:8px;padding:8px}.adl-head input{flex:1;min-width:150px}.adl-body{display:grid;grid-template-columns:minmax(230px,34%) 1fr;min-height:0}.adl-list{overflow:auto;border-right:1px solid #2a4055;padding:10px}.adl-detail{overflow:auto;padding:16px}.adl-card{display:block;width:100%;text-align:left;background:#101f31;color:#dceafa;border:1px solid #29445c;border-radius:10px;padding:10px;margin:6px 0}.adl-title{font-size:12px;font-weight:650;overflow-wrap:anywhere}.adl-sub{font-size:9px;color:#91a9c2;margin-top:4px}.adl-pill{display:inline-block;font-size:9px;border:1px solid #466176;border-radius:12px;padding:2px 6px;margin:3px 4px 0 0;color:#b9d7e9}.adl-detail pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#0a1624;border-radius:9px;padding:12px;font:10px/1.55 ui-monospace,SFMono-Regular,monospace}.adl-note{font-size:11px;color:#9db2c9;line-height:1.6}@media(max-width:700px){.upper-field{padding:13px}.upper-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.upper-node{min-height:105px;padding:10px}.adl-body{grid-template-columns:1fr}.adl-list{border-right:0;border-bottom:1px solid #2a4055;max-height:36vh}.adl-detail{padding:12px}.adl-head input{order:4;width:100%}}`;document.head.append(s)}
async function index(){if(INDEX)return INDEX;const r=await fetch('./data/index.json');if(!r.ok)throw Error('data index '+r.status);INDEX=await r.json();return INDEX}
async function pack(k){if(PACKS.has(k))return PACKS.get(k);const ix=await index(),info=ix.levels?.[k];let out=[];for(const p of info?.parts||[]){const r=await fetch('./data/'+p);if(!r.ok)throw Error(p+' '+r.status);const x=await r.json();out.push(...(x.entries||x))}PACKS.set(k,out);return out}
function auth(a){return /current|registered/.test(a||'')?'current':'historical'}
function sourcesFor(level){const k=MAP[level],a=[];for(const s of INDEX?.sources||[])if(s.level===k)a.push({...s,name:s.label||s.source,status:s.authority,source_name:s.source});for(const s of INDEX?.catalog_only?.[k]||[])a.push({...s,source_name:s.name});return a}
function entriesFor(level){return PACKS.get(MAP[level])||[]}
function updateNav(level){document.querySelectorAll('.level-stop').forEach(b=>{b.classList.toggle('active',b.dataset.level===level);if(UPPER.includes(b.dataset.level))b.classList.remove('pending')});if($('current-level'))$('current-level').textContent=level;const i=UPPER.indexOf(level);if($('level-out')){$('level-out').disabled=i===UPPER.length-1;$('level-out').textContent=i<UPPER.length-1?'− Zoom out → '+UPPER[i+1]:'Outermost bundled level'}if($('level-in')){$('level-in').disabled=false;$('level-in').textContent=i===0?'+ Zoom in → O3':'+ Zoom in → '+UPPER[i-1]}if($('level-scope'))$('level-scope').textContent='Evidence-backed '+level+' view. Cards represent stored source/evidence records; their screen placement is presentation-only and does not assert topology or containment.'}
function stats(level,sources,entries){const box=$('stats');if(!box)return;box.replaceChildren();for(const [n,l] of [[sources.length,'source families'],[entries.length,'embedded records']]){const x=document.createElement('span');x.innerHTML='<b>'+n+'</b>'+l;box.append(x)}}
function inspector(obj,level){const x=$('inspector-content');if(!x)return;x.innerHTML=`<span class="eyebrow">${esc(level)} · STORED EVIDENCE</span><h2>${esc(obj.name||obj.source_name||obj.path||obj.sha256||'Record')}</h2><p class="notice">This view exposes stored evidence. Card position and proximity have no algebraic or geometric meaning.</p><div class="id-text">${esc(obj.source_sha256||obj.sha256||obj.file_id||'')}</div><pre>${esc(JSON.stringify(obj,null,2))}</pre>`;if(innerWidth<=900)$('inspector')?.classList.add('open')}
async function renderUpper(level){upper=level;await index();await pack(MAP[level]);updateNav(level);document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab==='explore'));if($('scene-title'))$('scene-title').textContent=TITLES[level]||level;if($('scene-kicker'))$('scene-kicker').textContent=level+' · EVIDENCE FIELD';const src=sourcesFor(level),ent=entriesFor(level);stats(level,src,ent);
 for(const id of ['path-controls','comparison-controls','evidence-panel','breadcrumbs'])if($(id))$(id).hidden=true;if($('view-toolbar'))$('view-toolbar').hidden=true;if($('graph-area')){$('graph-area').hidden=false;let f=$('rm-upper-field');if(!f){f=document.createElement('div');f.id='rm-upper-field';f.className='upper-field';$('graph-area').append(f)}f.hidden=false;for(const c of $('graph-area').children)if(c!==f)c.style.visibility='hidden';const cards=[...src.map(x=>({type:'SOURCE',title:x.name||x.source_name,meta:(x.status||x.authority||'')+' · '+human(x.size||x.bytes),obj:x})),...ent.slice(0,120).map(e=>({type:'RECORD',title:e.references?.[0]?.path||e.sha256,meta:(e.content_status||e.kind||'record')+' · '+human(e.bytes),obj:e}))];f.innerHTML='<div class="upper-grid"><div class="upper-note'+(cards.length?'':' upper-gap')+'">'+esc(cards.length?`${level}: ${src.length} source families and ${ent.length} embedded records are available. Tap a card to inspect its exact provenance.`:`${level}: no byte-backed object adapter is available in this build. Indexed historical source evidence is shown without inventing structure.`)+'</div>'+cards.map((c,i)=>`<button class="upper-node ${auth(c.obj.status||c.obj.authority)}" data-u="${i}"><div class="u-kind">${esc(c.type)}</div><div class="u-title">${esc(c.title)}</div><div class="u-meta">${esc(c.meta)}</div></button>`).join('')+'</div>';[...f.querySelectorAll('[data-u]')].forEach((b,i)=>b.onclick=()=>inspector(cards[i].obj,level))}if($('projection-note'))$('projection-note').textContent='Evidence-field layout only — no unstored topology, metric, geometry, or lineage is inferred.';const cat=$('catalog-list');if(cat){cat.innerHTML='';const h=document.createElement('div');h.className='catalog-group';h.textContent=level+' SOURCES';cat.append(h);for(const s of src){const b=document.createElement('button');b.className='record-card';b.innerHTML=`<span class="name">${esc(s.name||s.source_name)}</span><span class="sub">${esc(s.status||s.authority||'source')}</span>`;b.onclick=()=>inspector(s,level);cat.append(b)}if(!src.length)cat.innerHTML+='<p class="small muted">No materialized source family at this level.</p>'}if($('scene-count'))$('scene-count').textContent=(src.length+ent.length)+' evidence records';inspector({name:TITLES[level],level,source_families:src.length,embedded_records:ent.length,scientific_note:'Stored evidence view; no synthetic topology.'},level)}
function human(n){if(!n)return'';if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';return(n/1048576).toFixed(1)+' MB'}
function leaveUpper(){upper=null;const f=$('rm-upper-field');if(f)f.hidden=true;if($('graph-area'))for(const c of $('graph-area').children)c.style.visibility='';}
function intercept(){document.addEventListener('click',ev=>{const stop=ev.target.closest?.('.level-stop');if(stop){const lev=stop.dataset.level;if(UPPER.includes(lev)){ev.preventDefault();ev.stopImmediatePropagation();renderUpper(lev).catch(console.error);return}else if(upper){leaveUpper();return}}
 if(ev.target.closest?.('#level-out')&&(upper||$('current-level')?.textContent==='O3')){ev.preventDefault();ev.stopImmediatePropagation();const next=upper?UPPER[UPPER.indexOf(upper)+1]:UPPER[0];if(next)renderUpper(next).catch(console.error);return}
 if(ev.target.closest?.('#level-in')&&upper){ev.preventDefault();ev.stopImmediatePropagation();const i=UPPER.indexOf(upper);if(i>0)renderUpper(UPPER[i-1]).catch(console.error);else{leaveUpper();document.querySelector('.level-stop[data-level="O3"]')?.click()}return}},true)}
async function decorate(){await index();for(const b of document.querySelectorAll('.level-stop')){const lev=b.dataset.level;if(!UPPER.includes(lev))continue;const k=MAP[lev],n=(INDEX.levels?.[k]?.entries||0)+(INDEX.catalog_only?.[k]?.length||0);b.classList.remove('pending');if(n&&!b.querySelector('.data-badge')){const s=document.createElement('span');s.className='data-badge';s.textContent=' ·'+n;b.append(s)}}}
function libraryUI(){const top=document.querySelector('.top-actions');if(top&&!$('all-data-open')){const b=document.createElement('button');b.id='all-data-open';b.textContent='All data';b.onclick=()=>openLibrary();top.insertBefore(b,top.firstChild)}const w=document.createElement('div');w.id='all-data-library';w.className='adl';w.innerHTML='<div class="adl-head"><h2>IG Data Library</h2><select id="adl-level"></select><input id="adl-search" type="search" placeholder="Find source, object, schema, witness…"><button id="adl-offline">Make all data offline</button><span id="adl-progress"></span><button id="adl-close">Close</button></div><div class="adl-body"><div class="adl-list" id="adl-list"></div><div class="adl-detail" id="adl-detail"><p class="adl-note">Select a source or record.</p></div></div>';document.body.append(w);$('adl-close').onclick=()=>w.classList.remove('open');$('adl-level').onchange=()=>libraryLevel($('adl-level').value);$('adl-search').oninput=renderLibrary;$('adl-offline').onclick=cacheAll}
async function openLibrary(level){await index();const w=$('all-data-library');w.classList.add('open');const s=$('adl-level');if(!s.options.length){const lv=['FOUNDATION','L2','NODE','O1-O3','O3','O4-O7','G1','G2','G3','G4','G5','G6','G7','G8'];for(const l of lv){const o=document.createElement('option');o.value=l;o.textContent=l;s.append(o)}}await libraryLevel(level||MAP[upper]||'L2')}
async function libraryLevel(level){$('adl-level').value=level;await pack(level);renderLibrary()}
function renderLibrary(){const level=$('adl-level').value,q=($('adl-search').value||'').toLowerCase(),cards=[];for(const s of INDEX.sources||[])if(s.level===level)cards.push({title:s.label||s.source,sub:s.authority,obj:s});for(const s of INDEX.catalog_only?.[level]||[])cards.push({title:s.name,sub:s.authority,obj:s});for(const e of PACKS.get(level)||[])cards.push({title:e.references?.[0]?.path||e.sha256,sub:(e.content_status||e.kind)+' · '+human(e.bytes),obj:e});const filt=q?cards.filter(c=>(c.title+' '+c.sub+JSON.stringify(c.obj).slice(0,1000)).toLowerCase().includes(q)):cards;$('adl-list').innerHTML='<p class="adl-note">'+filt.length+' records</p>'+filt.slice(0,3000).map((c,i)=>`<button class="adl-card" data-a="${i}"><div class="adl-title">${esc(c.title)}</div><div class="adl-sub">${esc(c.sub)}</div></button>`).join('');[...$('adl-list').querySelectorAll('[data-a]')].forEach((b,i)=>b.onclick=()=>{$('adl-detail').innerHTML='<h2>'+esc(filt[i].title)+'</h2><pre>'+esc(JSON.stringify(filt[i].obj,null,2))+'</pre>'})}
async function cacheAll(){await index();const urls=['./','./all-data.js','./data/index.json'];for(const v of Object.values(INDEX.levels||{}))for(const p of v.parts||[])urls.push('./data/'+p);try{const c=await caches.open('ig-rm-v0.3.1-data');let i=0;for(const u of urls){await c.add(u);i++;$('adl-progress').textContent=i+'/'+urls.length}$('adl-progress').textContent='Offline data cached'}catch(e){$('adl-progress').textContent='Cache failed: '+e.message}}
function setup(){css();libraryUI();intercept();decorate().catch(console.error)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
})();
