(()=>{
'use strict';
const $=id=>document.getElementById(id);
const ALIAS={L0:'L2',L1:'L2',L2:'L2',O1:'O1-O3',O2:'O1-O3',O3:'O3',O4:'O4-O7',O5:'O4-O7',O6:'O4-O7',O7:'O4-O7',G1:'G1',G2:'G2',G3:'G3',G4:'G4',G5:'G5',G6:'G6',G7:'G7',G8:'G8'};
const UPPER=new Set(['O4','O5','O6','O7','G1','G2','G3','G4','G5','G6','G7','G8']);
const DATA_SCRIPTS=['./datajs/index.js','./datajs/foundation-000.js','./datajs/l2-000.js','./datajs/l2-001.js','./datajs/l2-002.js','./datajs/l2-003.js','./datajs/l2-004.js','./datajs/l2-005.js','./datajs/l2-006.js','./datajs/l2-007.js','./datajs/node-000.js','./datajs/o1_o3-000.js','./datajs/o3-000.js','./datajs/o3-001.js','./datajs/o4_o7-000.js','./datajs/g8-000.js'];
let INDEX=null,PACKS=new Map(),active='L2',DATA_READY=null;
function ensureData(){if(DATA_READY)return DATA_READY;DATA_READY=(async()=>{for(const src of DATA_SCRIPTS)await new Promise((ok,fail)=>{const sc=document.createElement('script');sc.src=src;sc.onload=ok;sc.onerror=()=>fail(Error('data script '+src));document.head.append(sc)})})();return DATA_READY}
const human=n=>n==null?'':n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB';
async function index(){if(INDEX)return INDEX;await ensureData();INDEX=window.__IG_INDEX;if(!INDEX)throw Error('data index unavailable');decorate();return INDEX}
async function pack(level){await index();if(PACKS.has(level))return PACKS.get(level);const x={level,entries:(window.__IG_PACKS?.[level]||[])};PACKS.set(level,x);return x}
function css(){const s=document.createElement('style');s.textContent=`
#all-data-open{border-color:#3c6c78;background:#163244}.data-badge{font-size:9px;margin-left:4px;color:#89f0d5}.upper-atlas{height:100%;min-height:430px;overflow:auto;padding:18px;background:radial-gradient(circle at 50% 35%,#10263a 0,#091625 46%,#07111d 100%)}.upper-head{max-width:960px;margin:0 auto 14px}.upper-head h2{margin:0 0 5px;font-size:22px}.upper-note{color:#9db2c9;font-size:11px;line-height:1.55}.upper-grid{max-width:1000px;margin:auto;display:grid;grid-template-columns:repeat(auto-fit,minmax(185px,1fr));gap:12px}.upper-node{appearance:none;text-align:left;min-height:118px;padding:13px;border-radius:14px;border:1px solid #31516a;background:linear-gradient(145deg,#13283b,#0c1c2c);color:#e9f3ff;box-shadow:0 7px 22px #0005}.upper-node.current{border-color:#4ba894}.upper-node.historical{border-color:#8a7548}.upper-node .u-k{font-size:9px;color:#86a4bd;letter-spacing:.08em;text-transform:uppercase}.upper-node .u-t{font-size:12px;font-weight:700;margin:7px 0;overflow-wrap:anywhere}.upper-node .u-s{font-size:9px;color:#9db2c9;line-height:1.45}.upper-empty{max-width:760px;margin:50px auto;text-align:center;color:#a7bad0}.adl{position:fixed;inset:0;z-index:10000;background:#07111def;color:#e9f2ff;display:none;backdrop-filter:blur(8px)}.adl.open{display:grid;grid-template-rows:auto 1fr}.adl-head{display:flex;gap:9px;align-items:center;padding:11px 13px;background:#0d1a2a;border-bottom:1px solid #2a4055;flex-wrap:wrap}.adl-head h2{font-size:17px;margin:0 10px 0 0}.adl-head select,.adl-head input{background:#101f31;color:#e9f2ff;border:1px solid #355066;border-radius:8px;padding:8px}.adl-head input{flex:1;min-width:140px}.adl-body{display:grid;grid-template-columns:minmax(230px,34%) 1fr;min-height:0}.adl-list{overflow:auto;border-right:1px solid #2a4055;padding:10px}.adl-detail{overflow:auto;padding:16px}.adl-card{display:block;width:100%;text-align:left;background:#101f31;color:#dceafa;border:1px solid #29445c;border-radius:10px;padding:10px;margin:6px 0}.adl-title{font-size:12px;font-weight:650;overflow-wrap:anywhere}.adl-sub{font-size:9px;color:#91a9c2;margin-top:4px}.adl-detail pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#0a1624;border-radius:9px;padding:12px;font:10px/1.55 ui-monospace,SFMono-Regular,monospace}.adl-note{font-size:11px;color:#9db2c9;line-height:1.6}@media(max-width:700px){.adl-body{grid-template-columns:1fr}.adl-list{border-right:0;border-bottom:1px solid #2a4055;max-height:35vh}.upper-atlas{padding:12px}.upper-grid{grid-template-columns:1fr 1fr}.upper-node{min-height:105px;padding:10px}}
`;document.head.append(s)}
function statusClass(a){return /current|registered/.test(a||'')?'current':'historical'}
function cardsFor(ui,p){const level=ALIAS[ui], cards=[];for(const s of INDEX.sources||[])if(s.level===level)cards.push({type:'source',title:s.label||s.source,sub:s.source,authority:s.authority,size:s.bytes,obj:s});for(const s of INDEX.catalog_only?.[level]||[])cards.push({type:'catalog',title:s.name,sub:s.status||'indexed source',authority:s.authority,size:s.size,obj:s});for(const e of p?.entries||[]){const r=e.references?.[0]||{};cards.push({type:'entry',title:r.path||e.sha256,sub:(e.kind||'record')+' · '+human(e.bytes),authority:r.authority||'stored record',size:e.bytes,obj:e})}return cards}
async function showUpper(ui){if(!UPPER.has(ui))return;active=ALIAS[ui];await index();const p=await pack(active);const ga=$('graph-area');if(!ga)return;ga.hidden=false;$('evidence-panel').hidden=true;$('view-toolbar').hidden=true;$('breadcrumbs').hidden=true;$('path-controls').hidden=true;$('comparison-controls').hidden=true;$('graph-b-panel').hidden=true;$('graph-a-label').hidden=true;
 const cards=cardsFor(ui,p);ga.innerHTML='';const a=document.createElement('div');a.className='upper-atlas';const h=document.createElement('div');h.className='upper-head';const title=document.createElement('h2');title.textContent=ui+' · stored evidence atlas';const note=document.createElement('p');note.className='upper-note';note.textContent='Each tile is an actually stored source family or record associated with this display level. Position is presentation-only. No edges, containment, geometry or ancestry are inferred where the saved evidence does not supply them.';h.append(title,note);a.append(h);const grid=document.createElement('div');grid.className='upper-grid';for(const c of cards){const b=document.createElement('button');b.className='upper-node '+statusClass(c.authority);b.innerHTML='<div class="u-k"></div><div class="u-t"></div><div class="u-s"></div>';b.querySelector('.u-k').textContent=c.authority||c.type;b.querySelector('.u-t').textContent=c.title;b.querySelector('.u-s').textContent=c.sub+(c.size?' · '+human(c.size):'');b.onclick=()=>openLibrary(active,c);grid.append(b)}if(!cards.length){const e=document.createElement('div');e.className='upper-empty';e.textContent='No stored record is mapped to this level yet.';grid.append(e)}a.append(grid);ga.append(a);$('scene-title').textContent=ui+' · stored evidence';$('scene-kicker').textContent='PROVENANCE-PRESERVING UPPER-LAYER VIEW';$('scene-count').textContent=cards.length+' records';$('projection-note').textContent='Evidence atlas only · no unstored topology inferred';}
function setupLibrary(){const top=document.querySelector('.top-actions');if(top&&!$('all-data-open')){const b=document.createElement('button');b.id='all-data-open';b.textContent='All data';b.onclick=()=>openLibrary(active);top.insertBefore(b,top.firstChild)}const w=document.createElement('div');w.id='all-data-library';w.className='adl';w.innerHTML='<div class="adl-head"><h2>IG Data Library</h2><select id="adl-level"></select><input id="adl-search" type="search" placeholder="Find source, object, schema, witness…"><button id="adl-close">Close</button></div><div class="adl-body"><div class="adl-list" id="adl-list"></div><div class="adl-detail" id="adl-detail"><p class="adl-note">Select a stored record.</p></div></div>';document.body.append(w);$('adl-close').onclick=()=>w.classList.remove('open');$('adl-search').oninput=renderList;$('adl-level').onchange=async e=>{active=e.target.value;await pack(active);renderList()}}
async function openLibrary(level,chosen){await index();active=level||active;await pack(active);const w=$('all-data-library');w.classList.add('open');const sel=$('adl-level');if(!sel.options.length){for(const l of [...new Set([...Object.keys(INDEX.levels||{}),...Object.keys(INDEX.catalog_only||{})])]){const o=document.createElement('option');o.value=l;o.textContent=l;sel.append(o)}}sel.value=active;renderList();if(chosen)show(chosen)}
function currentCards(){return cardsFor(active,PACKS.get(active));}
function renderList(){const box=$('adl-list');if(!box||!INDEX)return;const q=($('adl-search').value||'').toLowerCase(),cs=currentCards().filter(c=>!q||(c.title+' '+c.sub+' '+c.authority+JSON.stringify(c.obj).slice(0,1200)).toLowerCase().includes(q));box.innerHTML='<p class="adl-note">'+cs.length+' records · '+active+'</p>';for(const c of cs.slice(0,3000)){const b=document.createElement('button');b.className='adl-card';b.innerHTML='<div class="adl-title"></div><div class="adl-sub"></div>';b.children[0].textContent=c.title;b.children[1].textContent=(c.authority||'')+' · '+c.sub;b.onclick=()=>show(c);box.append(b)}}
function show(c){const d=$('adl-detail');d.innerHTML='';const h=document.createElement('h2');h.textContent=c.title;d.append(h);const p=document.createElement('p');p.className='adl-note';p.textContent=(c.authority||'')+' · '+c.sub;d.append(p);const pre=document.createElement('pre');if(c.type==='entry'&&c.obj.kind==='text'&&c.obj.text!=null){let x=c.obj.text;try{x=JSON.stringify(JSON.parse(x),null,2)}catch{}pre.textContent=x}else pre.textContent=JSON.stringify(c.obj,null,2);d.append(pre)}
function decorate(){for(const b of document.querySelectorAll('.level-stop')){const ui=b.dataset.level,m=ALIAS[ui],n=(INDEX.levels?.[m]?.entries||0)+(INDEX.catalog_only?.[m]?.length||0);if(n&&!b.querySelector('.data-badge')){const s=document.createElement('span');s.className='data-badge';s.textContent=' ·'+n;b.append(s);b.classList.remove('pending')}}}
function bindUpper(){document.addEventListener('click',ev=>{const b=ev.target.closest?.('.level-stop');if(b&&UPPER.has(b.dataset.level)){setTimeout(()=>showUpper(b.dataset.level).catch(console.error),0);return}if(ev.target.closest?.('#level-out,#level-in'))setTimeout(()=>{const ui=$('current-level')?.textContent?.trim();if(UPPER.has(ui))showUpper(ui).catch(console.error)},0)},true);const cur=$('current-level');if(cur)new MutationObserver(()=>{const ui=cur.textContent.trim();if(UPPER.has(ui))setTimeout(()=>showUpper(ui).catch(console.error),0)}).observe(cur,{childList:true,subtree:true,characterData:true})}
async function boot(){css();setupLibrary();bindUpper();try{await index()}catch(e){console.error('IG data library',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();