(()=>{
'use strict';
const $=id=>document.getElementById(id);
const DATA_SCRIPTS=["./datajs/index.js","./datajs/foundation-000.js","./datajs/l2-000.js","./datajs/l2-001.js","./datajs/l2-002.js","./datajs/l2-003.js","./datajs/l2-004.js","./datajs/l2-005.js","./datajs/l2-006.js","./datajs/l2-007.js","./datajs/node-000.js","./datajs/o1_o3-000.js","./datajs/o3-000.js","./datajs/o3-001.js","./datajs/o4_o7-000.js","./datajs/g8-000.js"];
let DATA_READY=null, INDEX=null, ACTIVE_LEVEL=null, ACTIVE_PACK=null;
function ensureDataScripts(){if(DATA_READY)return DATA_READY;DATA_READY=(async()=>{for(const src of DATA_SCRIPTS){await new Promise((ok,fail)=>{const sc=document.createElement('script');sc.src=src;sc.onload=ok;sc.onerror=()=>fail(Error('data script '+src));document.head.append(sc)})}})();return DATA_READY}
const levelAliases={L0:'L2',L1:'L2',L2:'L2',O1:'O1-O3',O2:'O1-O3',O3:'O3',O4:'O4-O7',O5:'O4-O7',O6:'O4-O7',O7:'O4-O7',G1:'G1',G2:'G2',G3:'G3',G4:'G4',G5:'G5',G6:'G6',G7:'G7',G8:'G8'};
function css(){const s=document.createElement('style');s.textContent=`
#all-data-open{border-color:#3c6c78;background:#163244}.data-badge{font-size:9px;margin-left:4px;color:#89f0d5}.adl{position:fixed;inset:0;z-index:10000;background:#07111def;color:#e9f2ff;display:none;backdrop-filter:blur(8px)}.adl.open{display:grid;grid-template-rows:auto 1fr}.adl-head{display:flex;gap:10px;align-items:center;padding:12px 14px;background:#0d1a2a;border-bottom:1px solid #2a4055;flex-wrap:wrap}.adl-head h2{font-size:18px;margin:0 12px 0 0}.adl-head select,.adl-head input{background:#101f31;color:#e9f2ff;border:1px solid #355066;border-radius:8px;padding:8px}.adl-head input{flex:1;min-width:150px}.adl-body{display:grid;grid-template-columns:minmax(230px,34%) 1fr;min-height:0}.adl-list{overflow:auto;border-right:1px solid #2a4055;padding:10px}.adl-detail{overflow:auto;padding:16px}.adl-card{display:block;width:100%;text-align:left;background:#101f31;color:#dceafa;border:1px solid #29445c;border-radius:10px;padding:10px;margin:6px 0}.adl-card:hover{background:#153047}.adl-title{font-size:12px;font-weight:650;overflow-wrap:anywhere}.adl-sub{font-size:9px;color:#91a9c2;margin-top:4px}.adl-pill{display:inline-block;font-size:9px;border:1px solid #466176;border-radius:12px;padding:2px 6px;margin:3px 4px 0 0;color:#b9d7e9}.adl-pill.current{border-color:#4baf9c;color:#8df4dc}.adl-pill.historical{border-color:#b59454;color:#edcf91}.adl-detail pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#0a1624;border-radius:9px;padding:12px;font:10px/1.55 ui-monospace,SFMono-Regular,monospace}.adl-kpi{display:flex;gap:9px;flex-wrap:wrap;margin:8px 0 14px}.adl-kpi span{background:#102238;border:1px solid #2d475f;border-radius:9px;padding:7px 9px;font-size:10px}.adl-note{font-size:11px;color:#9db2c9;line-height:1.6}.adl-offline{background:#214447!important;border-color:#488978!important}.adl-progress{font-size:10px;color:#8df4dc}@media(max-width:700px){.adl-body{grid-template-columns:1fr}.adl-list{border-right:0;border-bottom:1px solid #2a4055;max-height:36vh}.adl-detail{padding:12px}.adl-head{padding:9px}.adl-head h2{font-size:15px}.adl-head input{order:4;width:100%}}`;document.head.append(s)}
async function loadIndex(){if(INDEX)return INDEX;await ensureDataScripts();INDEX=window.__IG_INDEX;decorateLevels();return INDEX}
async function loadPack(level){await loadIndex();if(ACTIVE_LEVEL===level&&ACTIVE_PACK)return ACTIVE_PACK;ACTIVE_LEVEL=level;ACTIVE_PACK={level,entries:(window.__IG_PACKS&&window.__IG_PACKS[level])||[]};return ACTIVE_PACK}
function human(n){if(n==null)return'';if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';return(n/1048576).toFixed(1)+' MB'}
function authClass(a){return /current|registered/.test(a||'')?'current':'historical'}
function setup(){css();const top=document.querySelector('.top-actions');if(top){const b=document.createElement('button');b.id='all-data-open';b.textContent='All data';b.onclick=()=>open();top.insertBefore(b,top.firstChild)}
 const wrap=document.createElement('div');wrap.id='all-data-library';wrap.className='adl';wrap.innerHTML=`<div class="adl-head"><h2>IG Data Library</h2><select id="adl-level"></select><input id="adl-search" type="search" placeholder="Find source, object, schema, witness…"><button id="adl-offline" class="adl-offline">Make all data offline</button><span id="adl-progress" class="adl-progress"></span><button id="adl-close">Close</button></div><div class="adl-body"><div class="adl-list" id="adl-list"></div><div class="adl-detail" id="adl-detail"><p class="adl-note">Select a dataset or object. Exact text/JSON is shown when bundled; binary scientific payloads are represented by their exact hash, size and format until a dedicated renderer is added.</p></div></div>`;document.body.append(wrap);$('adl-close').onclick=()=>wrap.classList.remove('open');$('adl-search').oninput=renderList;$('adl-level').onchange=()=>selectLevel($('adl-level').value);$('adl-offline').onclick=cacheAll;
 document.addEventListener('click',ev=>{const b=ev.target.closest?.('.level-stop');if(!b)return;const ui=b.dataset.level;if(!ui)return;const mapped=levelAliases[ui];if(['O4','O5','O6','O7','G1','G2','G3','G4','G5','G6','G7','G8'].includes(ui)){ev.preventDefault();setTimeout(()=>open(mapped),0)}},true);
}
async function open(level){$('all-data-library').classList.add('open');await loadIndex();const sel=$('adl-level');if(!sel.options.length){const levels=[...new Set([...Object.keys(INDEX.levels),...Object.keys(INDEX.catalog_only||{})])];levels.forEach(l=>{const o=document.createElement('option');o.value=l;o.textContent=l;sel.append(o)})}await selectLevel(level||sel.value||'L2')}
async function selectLevel(level){await loadIndex();$('adl-level').value=level;ACTIVE_LEVEL=level;ACTIVE_PACK=null;$('adl-list').innerHTML='<p class="adl-note">Loading '+level+'…</p>';try{await loadPack(level)}catch(e){$('adl-list').innerHTML='<p class="adl-note">'+e.message+'</p>'}renderList()}
function allCards(){const q=($('adl-search')?.value||'').toLowerCase();const cards=[];for(const s of INDEX.sources||[]){if(s.level!==ACTIVE_LEVEL)continue;cards.push({type:'source',title:s.label||s.source,sub:s.source,authority:s.authority,size:s.bytes,obj:s})}for(const s of (INDEX.catalog_only?.[ACTIVE_LEVEL]||[])){cards.push({type:'catalog',title:s.name,sub:'Indexed source bundle · bytes not embedded in this build',authority:s.authority,size:s.size,obj:s})}for(const e of (ACTIVE_PACK?.entries||[])){const r=e.references?.[0]||{};const title=r.path||e.sha256;cards.push({type:'entry',title,sub:(e.kind==='text'?e.ext:'binary '+e.format)+' · '+human(e.bytes)+' · '+(e.levels||[]).join(','),authority:r.authority,size:e.bytes,obj:e})}return q?cards.filter(c=>(c.title+' '+c.sub+' '+c.authority+JSON.stringify(c.obj).slice(0,1500)).toLowerCase().includes(q)):cards}
function renderList(){if(!INDEX||!$('adl-list'))return;const cards=allCards();$('adl-list').innerHTML='';const h=document.createElement('div');h.className='adl-note';h.textContent=cards.length+' records at '+ACTIVE_LEVEL; $('adl-list').append(h);for(const c of cards.slice(0,3000)){const b=document.createElement('button');b.className='adl-card';b.innerHTML=`<div class="adl-title"></div><div class="adl-sub"></div><span class="adl-pill ${authClass(c.authority)}"></span>`;b.children[0].textContent=c.title;b.children[1].textContent=c.sub;b.querySelector('.adl-pill').textContent=c.authority||'source';b.onclick=()=>show(c);$('adl-list').append(b)}}
function summary(obj){if(!obj||typeof obj!=='object')return[];const a=[];if(obj.schema_id)a.push(['schema',obj.schema_id]);if(Array.isArray(obj.rows))a.push(['rows',obj.rows.length]);if(Array.isArray(obj.states))a.push(['states',obj.states.length]);if(Array.isArray(obj.collisions))a.push(['collisions',obj.collisions.length]);if(Array.isArray(obj.candidate_classes))a.push(['classes',obj.candidate_classes.length]);if(Array.isArray(obj.references))a.push(['provenance refs',obj.references.length]);if(obj.tid!==undefined)a.push(['tid',obj.tid]);return a}
function show(c){const d=$('adl-detail');d.innerHTML='';const h=document.createElement('h2');h.textContent=c.title;d.append(h);const sub=document.createElement('p');sub.className='adl-note';sub.textContent=c.sub;d.append(sub);if(c.type==='entry'){const e=c.obj;if(e.kind==='text'&&e.text!=null){let parsed=null;if(e.ext==='json'){try{parsed=JSON.parse(e.text)}catch{}}const k=document.createElement('div');k.className='adl-kpi';for(const [a,b] of summary(parsed||e)){const s=document.createElement('span');s.textContent=a+': '+b;k.append(s)}d.append(k);if(parsed&&Array.isArray(parsed.rows)&&parsed.rows.length>2000){const n=document.createElement('p');n.className='adl-note';n.textContent='Large exact table: '+parsed.rows.length.toLocaleString()+' rows. Inspector shows complete JSON below; future renderers can page this without changing source bytes.';d.append(n)}const pre=document.createElement('pre');pre.textContent=parsed?JSON.stringify(parsed,null,2):e.text;d.append(pre)}else{const note=document.createElement('p');note.className='adl-note';note.textContent=e.content_status==='indexed_exact_payload'?'Large exact payload: indexed by SHA-256, byte size, source path and provenance. Structural summary is bundled; raw expansion is intentionally deferred to keep the mobile microscope responsive.':'Binary payload: exact hash/size/provenance are bundled; a dedicated renderer can be added without changing identity.';d.append(note);const pre=document.createElement('pre');pre.textContent=JSON.stringify(e,null,2);d.append(pre)}}else{const pre=document.createElement('pre');pre.textContent=JSON.stringify(c.obj,null,2);d.append(pre)}}
async function cacheAll(){await loadIndex();$('adl-progress').textContent='All scientific viewer data scripts are loaded; the v0.3 service worker keeps them in the offline app cache.'}
function decorateLevels(){for(const b of document.querySelectorAll('.level-stop')){const ui=b.dataset.level,m=levelAliases[ui];const n=(INDEX.levels?.[m]?.entries||0)+(INDEX.catalog_only?.[m]?.length||0);if(n&&!b.querySelector('.data-badge')){const s=document.createElement('span');s.className='data-badge';s.textContent='·'+n;b.append(s)}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
})();