"""Slim exact handoff for a preserved native preflight refusal."""
from pathlib import Path
import json,hashlib,zipfile,datetime
B=Path(__file__).resolve().parent;W=B.parent;Q=W/'continuation0235'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 a=json.loads((B/'AUDIT.json').read_text());c=json.loads((B/'COLD_AUDIT.json').read_text());p=json.loads((B/'CHECKPOINT_PRESERVED.json').read_text());assert c['refusal_exact'] and not p['pending_objects'] and a['official_cases_executed']==0
 report=W/'IG_MASTER152_G2_NATIVE_PREFLIGHT_STOP0236_2026-10-09.txt'
 report.write_text('Checkpoint 0236: native capture preserved; official execution stopped at import preflight.\n\nMaster: 152. New admissions: 0. G2 promotion: false. Historical V1 replay depth: 100. Official G2 cases executed: zero. New G1 or G2 scientific realizations in this step: zero. The one-case dry result remains the separately scoped checkpoint0235 evidence.\n\nNative preflight refused importlib.import_module at infinity_grid/semantic_sentinel.py line 19. The static import path is project.worker -> infinity_grid.uplift_structural -> infinity_grid.theorem_registry -> infinity_grid.semantic_sentinel. The complete 22-module static audit found this single failing module. No registered scientific source or comparison criterion was changed.\n\nThe earlier checkpoint0235 local preflight inspected only five project modules because its source root omitted the engine directory. The native captured source includes the engine and traverses imports inside all functions, including functions not used by this probe. The refusal therefore occurred before warmup, DAG restoration, evaluator execution or official case construction. The dry PASS cannot be used to infer native import readiness.\n\nThe six new capture objects were saved to Drive and verified by exact raw readback. An explicit idle refusal snapshot was created because the guard stopped before an automatic execution checkpoint existed. All snapshot objects are preserved, pending bytes zero. Independent cold restoration verified dependency identities, restored the checkpoint and reproduced the exact refusal and all scientific source pins. This validates the stop and recovery evidence, not the scientific 62-case result.\n\nRefusal diagnosis SHA256: '+sha(B/'PREFLIGHT_DIAGNOSIS.json')+'\nComplete static audit SHA256: '+sha(B/'AUDIT.json')+'\nCold audit SHA256: '+sha(B/'COLD_AUDIT.json')+'\nNative checkpoint SHA256: '+c['checkpoint_sha256']+'\n\nRecovery: verify MANIFEST.json. Restore bundled NATIVE_CHECKPOINT_SLIM.zip using CHECKPOINT_EXPORT.json dependency hashes and READBACKS.json exact Drive IDs. Fetch only missing dependency bytes; no old theory files or full G2 SQLite index are needed. Use pinned CPython3.13.5 and the bundled runtime manifest. The historical G1 exact input and 62-case selection remain bound to checkpoint0235 preregistration.\n\nNext: repair complete native import preflight without changing scientific recipe. Check the legitimate semantic source-inspection dependency and its exact runtime boundary; do not disable guard checks globally or silently rewrite the frozen scientific source. Preregister any necessary engineering source change, rerun the complete captured-source check, then resume the still-unexecuted fixed62 probe through a new capture.\n')
 s=json.loads((W/'CURRENT_STATUS.json').read_text());s.update(status_as_of_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),latest_checkpoint=236,current_phase='G2_NATIVE_PREFLIGHT_STOPPED',master_slices=152,new_admissions=0,checkpoint0236=dict(audit=a,cold_audit=c),latest_capture_id=json.loads((B/'POINTER.json').read_text())['capture_id'],pending_bytes=0,next_scope=a['next_scope'],code_mirror=json.loads((B/'CODE_MIRROR.json').read_text()))
 (B/'STATUS_CANDIDATE.json').write_text(json.dumps(s,indent=2)+'\n')
 files=[p for p in B.iterdir() if p.is_file() and p.suffix in ('.json','.py','.log','.txt','.zip') and p.name not in ('DELIVERABLES.json','SAVE_RECEIPT.json','private_downloads.json')]+[report]
 files += [p for p in Q.rglob('*.py')]+[Q/n for n in ['PREREGISTRATION.json','SPEC.json','CASES.json','PREFLIGHT.json','DRY_RESULT.json','DRY_CASE.json','AUDIT.json','SAVE_RECEIPT.json']]
 files += [W/'continuation0231/RUNTIME_MANIFEST.json',W/'continuation0232/SEAL_DRIVE_SAVE.json',W/'continuation0232/SEAL_RECEIPT.json',W/'continuation0233/CATALOG_0152.json']
 manifest={str(p.relative_to(W)):{'sha256':sha(p),'bytes':p.stat().st_size} for p in sorted(files)}
 out=W/'IG_MASTER152_G2_NATIVE_PREFLIGHT_STOP0236_HANDOFF_2026-10-09.zip'
 with zipfile.ZipFile(out,'w',zipfile.ZIP_DEFLATED) as z:
  for p in sorted(files):z.write(p,str(p.relative_to(W)))
  z.writestr('MANIFEST.json',json.dumps(manifest,indent=2))
 with zipfile.ZipFile(out) as z:
  assert z.testzip() is None
  for n,v in manifest.items():assert hashlib.sha256(z.read(n)).hexdigest()==v['sha256'] and len(z.read(n))==v['bytes']
 d={k:{'path':str(p),'sha256':sha(p),'bytes':p.stat().st_size} for k,p in [('report',report),('handoff',out)]};(B/'DELIVERABLES.json').write_text(json.dumps(d,indent=2)+'\n');print(json.dumps(d))
if __name__=='__main__':main()
